const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../acoustics/cardioid-study.cjs')();
const C=(r=0,i=0)=>({r,i}),add=(a,b)=>C(a.r+b.r,a.i+b.i),mul=(a,b)=>C(a.r*b.r-a.i*b.i,a.r*b.i+a.i*b.r),scale=(a,s)=>C(a.r*s,a.i*s),div=(a,b)=>C((a.r*b.r+a.i*b.i)/(b.r*b.r+b.i*b.i),(a.i*b.r-a.r*b.i)/(b.r*b.r+b.i*b.i)),mag=z=>Math.hypot(z.r,z.i),pow=(a,b)=>a.r*b.r+a.i*b.i,near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t*Math.max(1e-12,Math.abs(a),Math.abs(b)),a+' != '+b),nearC=(a,b,t)=>{near(a.r,b.r,t);near(a.i,b.i,t);};
const meta={units:'Pa*s/m',phasor:'exp(+jωt)',amplitude:'RMS',direction:'inside-minus-outside/outward',scope:'sheet-only',temperatureC:20,provenance:'Independent test fixture',sampleConstruction:'10 mm felt at measured compression',levelRange:'85–95 dB SPL',flowRange:'0.01–0.2 m/s RMS'};
test('Sealed rear reduces to independently calculated motor, one compliance and finite compact radiation',()=>{const c=E.defaults();c.slots=[];const f=80,r=E.solve(c,f);assert.equal(r.available,true,r.reason);const d=c.drivers[0],w=2*Math.PI*f,rho=c.medium.densityKgM3,speed=c.medium.soundSpeedMS,k=w/speed,a=d.sourceRadiusM,ze=C(d.ReOhm,w*d.LeH),zm=C(d.RmsNsPerM,w*d.movingMassKg-1/(w*d.CmsMPerN)),zrad=C(rho*speed/(4*Math.PI*a*a)*Math.sin(k*a)**2,rho*speed/(8*Math.PI*a*a)*Math.sin(2*k*a)),zc=C(0,-rho*speed*speed/(w*c.rear.netVolumeM3)),z=add(add(scale(add(zm,div(C(d.BlNPerA**2),ze)),1/d.SdM2**2),zc),zrad),expected=div(div(scale(d.voltageRms,d.BlNPerA/d.SdM2),ze),z);nearC(r.flows[0],expected);assert.ok(Math.abs(r.frontToRearDb)<1e-12);assert.ok(Math.abs(r.relativePowerResidual)<1e-10);});
test('A pair of coherent motors shares one rear compliance, rather than duplicating whole rear volumes',()=>{const c=E.defaults();c.slots=[];c.drivers[0].positionM=[-.08,0,.1];c.drivers.push({...c.drivers[0],id:'second',positionM:[.08,0,.1]});const f=70,r=E.solve(c,f);assert.equal(r.available,true,r.reason);nearC(r.flows[0],r.flows[1]);const w=2*Math.PI*f,Cair=c.rear.netVolumeM3/(c.medium.densityKgM3*c.medium.soundSpeedMS**2);nearC(r.rearPressureRmsPa,mul(C(0,1/(w*Cair)),scale(r.flows[0],2)));const d=c.drivers[0],ze=C(d.ReOhm,w*d.LeH),motor=scale(add(C(d.RmsNsPerM,w*d.movingMassKg-1/(w*d.CmsMPerN)),div(C(d.BlNPerA**2),ze)),1/d.SdM2**2),load=add(add(r.exteriorImpedance[0][0],r.exteriorImpedance[0][1]),C(0,-2/(w*Cair))),expected=div(div(scale(d.voltageRms,d.BlNPerA/d.SdM2),ze),add(motor,load));nearC(r.flows[0],expected);});
test('Lossless open rear slots take the opposite cone volume flow in the low frequency limit',()=>{const c=E.defaults();c.slots.forEach(s=>{s.lengthM=0;s.material.specificResistancePaSM=0;});const r=E.solve(c,1);assert.equal(r.available,true,r.reason);const total=r.flows.reduce(add,C());assert.ok(mag(total)/mag(r.flows[0])<1e-4);assert.equal(r.materialLossW,0);});
test('Common exterior is reciprocal and radiates nonnegative power for arbitrary source phases',()=>{const c=E.defaults(),sources=[...c.drivers,...c.slots];for(const f of [10,70,130]){const Z=E.exterior(sources,f,c.medium);for(let i=0;i<Z.length;i++)for(let j=0;j<Z.length;j++)nearC(Z[i][j],Z[j][i]);for(let seed=0;seed<120;seed++){const q=sources.map((_,i)=>C(Math.sin(1+seed*(i+1.17)),Math.cos(.4+seed*(i+1.51)))),p=Z.map(row=>row.reduce((a,z,j)=>add(a,mul(z,q[j])),C())),radiation=p.reduce((v,z,i)=>v+pow(z,q[i]),0);assert.ok(radiation>=-1e-9,'negative common radiation power');}}});
test('Integrated coherent far-field power converges to the common radiation-matrix power',()=>{const c=E.defaults(),sources=[...c.drivers,...c.slots],r=E.solve(c,120);assert.equal(r.available,true,r.reason);function integrate(n){let sum=0;const d=20;for(let i=0;i<n;i++){const z=-1+(i+.5)*2/n,s=Math.sqrt(1-z*z);for(let j=0;j<2*n;j++){const phi=2*Math.PI*(j+.5)/(2*n),p=E.pressure(sources,r.flows,120,c.medium,[s*Math.cos(phi),s*Math.sin(phi),z],d);sum+=mag(p)**2;}}return sum*4*Math.PI/(2*n*n)*d*d/(c.medium.densityKgM3*c.medium.soundSpeedMS);}const coarse=integrate(24),fine=integrate(96);assert.ok(Math.abs(fine-r.radiatedPowerW)<Math.abs(coarse-r.radiatedPowerW));near(fine,r.radiatedPowerW,3e-5);});
test('Changing source phase changes coherent radiation and a global polarity reversal preserves powers',()=>{const c=E.defaults();c.drivers[0].positionM=[-.08,0,.1];c.drivers.push({...c.drivers[0],id:'second',positionM:[.08,0,.1]});const a=E.solve(c,100);c.drivers[1].voltageRms=C(-1);const b=E.solve(c,100);assert.equal(b.available,true,b.reason);assert.ok(Math.abs(a.radiatedPowerW-b.radiatedPowerW)>a.radiatedPowerW*.2);c.drivers.forEach(d=>d.voltageRms=scale(d.voltageRms,-1));const inv=E.solve(c,100);near(inv.inputPowerW,b.inputPowerW);near(inv.radiatedPowerW,b.radiatedPowerW);inv.flows.forEach((q,i)=>nearC(q,scale(b.flows[i],-1)));});
test('Reflecting geometry swaps front/rear while retaining source propagation phase',()=>{const c=E.defaults(),a=E.solve(c,100);[...c.drivers,...c.slots].forEach(s=>{s.positionM[2]*=-1;s.normal[2]*=-1;});const b=E.solve(c,100);near(a.frontSplDb,b.rearSplDb);near(a.rearSplDb,b.frontSplDb);near(a.frontToRearDb,-b.frontToRearDb);});
test('RMS electrical power balances coil, suspension, independent sheets and radiation across a sweep',()=>{const c=E.defaults();c.slots[1].material.specificResistancePaSM=240;c.slots[1].material.specificInertanceKgM2=.05;for(const f of [5,20,50,100,130]){const r=E.solve(c,f);assert.equal(r.available,true,r.reason);assert.ok(Math.abs(r.relativePowerResidual)<1e-10);assert.ok(r.slots.every(s=>s.lossPowerW>=0));assert.ok(r.radiatedPowerW>=0);}});
test('Measured complex material imports preserve SI area, phase and interpolation without extrapolation',()=>{const csv='frequency_hz,real,imag\n50,100,20\n150,200,-10',m=E.parseImpedanceCsv(csv,meta);nearC(E.sheetImpedance(m,100),C(150,5));assert.throws(()=>E.sheetImpedance(m,151),/no extrapolation/);const volume=E.parseImpedanceCsv('frequency_hz,real,imag\n50,10000,2000\n150,20000,-1000',{...meta,units:'Pa*s/m^3',sampleAreaM2:.01});nearC(E.sheetImpedance(volume,100),C(150,5));const c=E.defaults();c.slots[0].material=m;assert.equal(E.solve(c,100).available,true);assert.match(E.solve(c,20).reason,/no extrapolation/);});
test('Active, ambiguous or incomplete material data and duplicate duct loading are rejected',()=>{for(const m of [{...meta,phasor:'exp(-jωt)'},{...meta,amplitude:'peak'},{...meta,direction:'inward'},{...meta,scope:'whole-duct'},{...meta,provenance:''},{...meta,flowRange:''},{...meta,units:'Pa*s/m^3'}])assert.throws(()=>E.parseImpedanceCsv('frequency_hz,real,imag\n50,100,0\n150,120,10',m));assert.throws(()=>E.parseImpedanceCsv('frequency_hz,real,imag\n50,-1,0\n150,10,1',meta),/nonnegative/);const c=E.defaults();c.slots[0].outerEndCorrectionM=.02;assert.match(E.solve(c,100).reason,/already owns/);delete c.slots[0].outerEndCorrectionM;c.slots[0].material.includesDuct=true;assert.match(E.solve(c,100).reason,/duplicate/);});
test('Uniform-cavity, finite-aperture, overlap, far-field and flow validity are enforced',()=>{const c=E.defaults();assert.equal(E.solve(c,1000).available,false);c.slots[0].positionM=[...c.drivers[0].positionM];assert.match(E.solve(c,100).reason,/overlap/);const near=E.defaults();near.distanceM=.2;assert.equal(E.solve(near,100).available,false);const loud=E.defaults();loud.drivers[0].voltageRms=C(1000);const r=E.solve(loud,100);assert.equal(r.available,true,r.reason);assert.equal(r.directivityAvailable,false);assert.deepEqual(r.polar,[]);assert.equal(r.frontToRearDb,null);});
test('Muting the voltage retains a coupled passive motor rather than removing its impedance',()=>{const c=E.defaults();c.drivers[0].positionM=[-.08,0,.1];c.drivers.push({...c.drivers[0],id:'muted',positionM:[.08,0,.1],voltageRms:C()});const r=E.solve(c,100);assert.equal(r.available,true,r.reason);assert.ok(mag(r.flows[1])>1e-8);assert.ok(r.drivers[1].coilPowerW>0);assert.equal(r.drivers[1].inputPowerW,0);assert.ok(Math.abs(r.relativePowerResidual)<1e-10);});
test('Domain handoff preserves separate slot geometry, normals, phases and single rear compliance ownership',()=>{const c=E.defaults(),m=E.exportManifest(c);assert.equal(m.domains.filter(d=>d.id==='rear-air').length,1);assert.equal(m.interfaces.length,3);assert.equal(m.interfaces[1].outline.shape,'rectangle');assert.equal(m.interfaces[1].outline.widthM,.04);assert.equal(m.interfaces[1].outerEndCorrectionOwner,'compact exterior self impedance');assert.deepEqual(m.configuration.drivers[0].voltageRms,C(1));assert.match(m.qualification,/not a mesh/);});
test('Silent excitation has no defined polar field and numerical overflow fails closed',()=>{const zero=E.defaults();zero.drivers[0].voltageRms=C();const r=E.solve(zero,100);assert.equal(r.available,true,r.reason);assert.equal(r.inputPowerW,0);assert.equal(r.directivityAvailable,false);assert.deepEqual(r.polar,[]);assert.equal(r.frontSplDb,null);assert.match(r.directivityReason,/No finite nonzero/);const huge=E.defaults();huge.drivers[0].voltageRms=C(1e200);const bad=E.solve(huge,100);assert.equal(bad.available,false);assert.match(bad.reason,/Nonfinite/);});
test('Sealed systems also gate cone excursion and cone speed before reporting directivity',()=>{const c=E.defaults();c.slots=[];c.drivers[0].voltageRms=C(10000);const r=E.solve(c,100);assert.equal(r.available,true,r.reason);assert.equal(r.directivityAvailable,false);assert.match(r.directivityReason,/Cone speed or excursion/);assert.deepEqual(r.polar,[]);assert.equal(r.frontSplDb,null);const fast=E.defaults();fast.slots=[];fast.drivers[0].maxExcursionPeakM=10;fast.drivers[0].voltageRms=C(10000);assert.equal(E.solve(fast,100).directivityAvailable,false);});
test('Maximum frequency reports the short-slot limit and measured operating range remains unqualified',()=>{const c=E.defaults();c.slots[0].lengthM=.15;const sources=E.validate(c),regime=E.regimes(c,sources,100);near(regime.upperFrequencyHz,.3*c.medium.soundSpeedMS/(2*Math.PI*.15));const measured=E.defaults();measured.slots[0].material=E.parseImpedanceCsv('frequency_hz,real,imag\n50,100,0\n150,100,0',meta);assert.ok(E.solve(measured,100).warnings.some(w=>w.includes('not automatically enforced')));});

test('Restored material tables reject nonfinite frequency endpoints rather than extending coverage',()=>{const c=E.defaults(),m=E.parseImpedanceCsv('frequency_hz,real,imag\n50,100,0\n150,100,0',meta);m.rows[1].frequencyHz=Infinity;c.slots[0].material=m;assert.equal(E.solve(c,100).available,false);assert.throws(()=>E.exportManifest(c),/finite, ordered/);});

test('Impossible rear volume and understated cone aperture cannot bypass compactness gates',()=>{const tinyRear=E.defaults();tinyRear.rear.largestDimensionM=.001;assert.match(E.solve(tinyRear,100).reason,/volume exceeds/);const tinyAperture=E.defaults();tinyAperture.drivers[0].apertureExtentM=.001;assert.match(E.solve(tinyAperture,100).reason,/equal-area disk diameter/);const exact=E.defaults();exact.drivers[0].apertureExtentM=2*Math.sqrt(exact.drivers[0].SdM2/Math.PI);assert.equal(E.solve(exact,100).available,true);const cube=E.defaults();cube.rear.largestDimensionM=Math.cbrt(cube.rear.netVolumeM3);assert.equal(E.solve(cube,100).available,true);});
