// JSDOM behavior verification, not rendered browser QA.
const {test}=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const C=require('../acoustics/crossover-study.cjs')(),P=require('../acoustics/crossover-panel.cjs');
function harness(){const dom=new JSDOM('<!doctype html><details id="crossoverStudy"></details>'),host=dom.window.document.querySelector('details'),downloads=[],changes=[],state={count:2,gap:20},r={available:true,model:'Reduced model test fixture',inputState:{...state},options:{voltageRms:1,distanceM:1},rows:[100,200,300,500,700,1000,1400,2000].map(f=>({available:true,frequencyHz:f,splDb:90,phaseDeg:0}))};let analysis={p:state};const api={getDesign:()=>analysis,getBroadband:()=>structuredClone(r),onChange:s=>changes.push(s),download:(...x)=>downloads.push(x)},p=P({MEHCrossoverStudy:C}).init(host,api),q=s=>host.querySelector('[data-cs-'+s+']'),click=s=>q(s).click(),event=s=>q(s).dispatchEvent(new dom.window.Event('input',{bubbles:true}));return {dom,host,p,q,click,event,downloads,changes,r,state,setAnalysis:a=>analysis=a};}
test('synthetic example is immediately usable and remains labelled with protected references',()=>{
 const h=harness();h.click('example');assert.ok(h.p.result);assert.match(h.q('status').textContent,/synthetic/);assert.match(h.q('qualification').textContent,/not measured/);assert.equal(h.q('source="mid"').disabled,true);assert.equal(h.q('ref="mid:level"').disabled,true);assert.ok(h.q('plot').innerHTML.includes('<svg'));assert.ok(!/NaN|Infinity|undefined/.test(h.q('plot').innerHTML));h.click('export-result');assert.match(h.downloads[0][1],/synthetic/);h.p.dispose();
});
test('snapshot restores imported traces options references and explicit frozen baseline',()=>{
 const h=harness();h.click('example');h.click('freeze');h.q('option="gainHighDb"').value='-2';h.event('option="gainHighDb"');assert.equal(h.p.result,null);const saved=h.p.snapshot,h2=harness();assert.equal(h2.p.restore(saved),true);assert.equal(h2.p.snapshot.options.gainHighDb,-2);assert.deepEqual(h2.p.snapshot.traces.mid,saved.traces.mid);assert.ok(h2.p.snapshot.baselineMid);h2.click('calculate');assert.ok(h2.p.result);assert.match(h2.q('legend').textContent,/Frozen/);h2.p.restore();assert.equal(h2.p.snapshot.traces.mid,null);assert.equal(h2.p.snapshot.baselineMid,null);h.p.dispose();h2.p.dispose();
});
test('current model capture records geometry and invalidates after geometry or acoustic changes',()=>{
 const h=harness();h.click('capture');let saved=h.p.snapshot;assert.equal(saved.traces.mid.basis,'simulated');assert.equal(saved.traces.mid.provenance.linkedGeometry,true);const high=structuredClone(saved.traces.mid);high.name='Compatible HF test fixture';high.provenance={};saved.traces.high=high;h.p.restore(saved);h.click('calculate');assert.ok(h.p.result);h.click('freeze');const a={p:{...h.state,gap:30}};h.setAnalysis(a);h.p.update(a);assert.equal(h.p.result,null);assert.equal(h.p.snapshot.traces.mid.provenance.stale,true);assert.equal(h.p.snapshot.baselineMid.provenance.linkedGeometry,false);h.click('calculate');assert.match(h.q('status').textContent,/earlier geometry or acoustic settings/);
 h.r.inputState=a.p;h.click('capture');h.r.options.voltageRms=2;h.click('calculate');assert.equal(h.p.result,null);assert.equal(h.p.snapshot.traces.mid.provenance.stale,true);h.p.dispose();
});
test('search previews and explicitly applies tested controls, then exports provenance',()=>{
 const h=harness();h.click('example');h.q('bound="steps"').value=3;h.event('bound="steps"');h.click('search');assert.ok(h.p.search);assert.equal(h.p.search.evaluated,54);assert.equal(h.q('use-search').disabled,false);const best=h.p.search.best.options;h.click('export-result');assert.match(h.downloads[0][1],/generatedSynthetic/);h.click('use-search');assert.equal(h.p.snapshot.options.fcHz,best.fcHz);assert.ok(h.p.result);h.q('option="lowHz"').value='';h.event('option="lowHz"');h.click('calculate');assert.equal(h.p.result,null);assert.match(h.q('status').textContent,/finite/);h.p.dispose();
});
test('A/B mismatch blocks quantitative results and valid matching inputs compare',()=>{
 const h=harness(),e=C.example();const saved={version:1,traces:{a:e.mid,b:e.mid},mode:'compare',comparison:{lowHz:200,highHz:2000,polarHz:1000}};h.p.restore(saved);h.click('compare');assert.equal(h.p.result.metrics.rmsDifferenceDb,0);assert.match(h.q('metrics').textContent,/beamwidth.*unavailable/);saved.traces.b=structuredClone(e.mid);saved.traces.b.reference.voltageRms=2;h.p.restore(saved);h.click('compare');assert.equal(h.p.result,null);assert.equal(h.q('export-result').disabled,true);assert.match(h.q('status').textContent,/Different voltageRms/);h.click('template');h.click('protocol');assert.equal(h.downloads.length,2);assert.match(h.downloads[1][1],/same driver|SAME driver/);h.p.dispose();
});
test('malformed saved traces fail closed and hostile labels are escaped in plots',()=>{
 const h=harness();assert.equal(h.p.restore({version:1,traces:{mid:{rows:[]}}}),false);assert.equal(h.p.snapshot.traces.mid,null);assert.match(h.q('status').textContent,/2–20000/);const svg=P({}).plotSVG([{name:'<script>alert(1)</script>',rows:[{x:100,y:0},{x:200,y:1}]}]);assert.ok(!svg.includes('<script>'));assert.match(svg,/&lt;script&gt;/);h.p.dispose();
});
