'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
const F=require('../exports/formats.cjs'),Z=require('../exports/zip.cjs'),{context:c}=require('./load-editor.cjs')();
const a=c.MEH.analyze(JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/offset-insert-study.json'))).state);
const blank=()=>F.hornBlank(a,16,{tolerance:0});
function bounds(points){return [0,1,2].map(k=>[Math.min(...points.map(p=>p[k])),Math.max(...points.map(p=>p[k]))]);}
test('horn blank has opposite edge pairs, positive volume and the exact retained inner/outer meridian',()=>{const m=blank(),edges=new Map();let vol=0;for(const f of m.faces){const [a,b,c]=f.map(i=>m.vertices[i]);vol+=(a[0]*(b[1]*c[2]-b[2]*c[1])+a[1]*(b[2]*c[0]-b[0]*c[2])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6;for(let i=0;i<3;i++){const x=f[i],y=f[(i+1)%3],key=[Math.min(x,y),Math.max(x,y)].join(',');if(!edges.has(key))edges.set(key,[]);edges.get(key).push(x<y?1:-1);}}for(const values of edges.values())assert.deepEqual(values.sort(),[-1,1]);assert.ok(vol>0);assert.equal(m.vertices.length,a.pro.length*32);for(let i=0;i<a.pro.length;i++){assert.deepEqual(m.vertices[i*16],[a.pro[i].r,0,a.pro[i].z]);assert.deepEqual(m.vertices[(a.pro.length+i)*16],[a.pro[i].outerR,0,a.pro[i].outerZ]);}});
test('binary STL round trip retains triangle count, finite unit normals and mm bounds',()=>{const m=blank(),raw=F.stl([m]),v=new DataView(raw.buffer),n=v.getUint32(80,true),points=[];assert.equal(n,m.faces.length);assert.equal(raw.length,84+50*n);for(let i=0;i<n;i++){const offset=84+i*50,normal=[0,4,8].map(k=>v.getFloat32(offset+k,true));assert.ok(Math.abs(Math.hypot(...normal)-1)<1e-6);for(let j=0;j<3;j++)points.push([0,4,8].map(k=>v.getFloat32(offset+12+j*12+k,true)));}const expected=bounds(m.vertices),actual=bounds(points);for(let i=0;i<3;i++)for(let j=0;j<2;j++)assert.ok(Math.abs(actual[i][j]-expected[i][j])<.0001);});
test('OBJ retains distinct parts and correct global face indices',()=>{const m=blank(),text=F.obj([m,m]),vertices=text.split('\n').filter(l=>l.startsWith('v ')),faces=text.split('\n').filter(l=>l.startsWith('f '));assert.equal(vertices.length,m.vertices.length*2);assert.equal(faces.length,m.faces.length*2);for(const line of faces)for(const id of line.slice(2).split(' ').map(Number))assert.ok(id>=1&&id<=vertices.length);assert.ok(faces[m.faces.length].slice(2).split(' ').every(i=>Number(i)>m.vertices.length));});
test('quarter point cloud stays within the two declared mirror planes',()=>{const points=F.cloud([blank()],true).trim().split('\n').map(l=>l.split(' ').map(Number));assert.ok(points.length);assert.ok(points.every(p=>p[0]>=0&&p[1]>=0));assert.ok(points.some(p=>p[0]===0));assert.ok(points.some(p=>p[1]===0));});
test('STEP references resolve and solid vs surface semantics remain distinct',()=>{for(const m of [blank(),{...blank(),closed:false}]){const text=F.facetedStep([m]),ids=new Set([...text.matchAll(/^#(\d+)=/gm)].map(x=>x[1]));for(const ref of text.matchAll(/#(\d+)(?!\d)/g))assert.ok(ids.has(ref[1]),ref[1]);assert.match(text,/SI_UNIT\(.MILLI.,.METRE.\)/);assert.match(text,m.closed?/FACETED_BREP\(/:/SHELL_BASED_SURFACE_MODEL\(/);if(!m.closed)assert.doesNotMatch(text,/CLOSED_SHELL|FACETED_BREP/);}});
test('NURBS surfaces use exact rational circles and sampled profile without fabricated openings',()=>{const text=F.nurbsStep(a);assert.equal((text.match(/RATIONAL_B_SPLINE_SURFACE/g)||[]).length,2);assert.match(text,/B_SPLINE_SURFACE\(1,2/);assert.match(text,/no entry cuts/);assert.doesNotMatch(text,/MANIFOLD_SOLID_BREP|FACETED_BREP/);});
test('CSV supports decimal comma with semicolon columns',()=>{const csv=F.profileCSV(a,true);assert.equal(csv.split('\n')[0],'t;z_mm;radius_mm;outer_z_mm;outer_radius_mm');assert.equal(csv.split('\n')[1].split(';').length,5);assert.match(csv.split('\n')[1],/\d,\d/);});
test('appended kit is a valid ZIP; original compressed files and Unicode filenames survive',()=>{const original=require('../mesh-export/runner-package.cjs').buildPackage(),kit=Z.append(original.bytes,{'MEH-local-runner/design.json':'{"mouth":720}','MEH-local-runner/notes-é.txt':'Hello'}),dir=fs.mkdtempSync(path.join(os.tmpdir(),'meh-zip-')),file=path.join(dir,'kit.zip');try{fs.writeFileSync(file,kit);const result=cp.spawnSync('python3',['-c',"import zipfile,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; assert z.read('MEH-local-runner/design.json') == b'{\"mouth\":720}'; assert z.read('MEH-local-runner/notes-é.txt') == b'Hello'; assert len(z.read('MEH-local-runner/run.py'))>100",file],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('1D script has one real motor per mid and joins all entries to one retained axial station',()=>{const open=c.MEH.analyze({...a.p,frontFiller:'none',midDriver:'bc6ndl38'}),s=F.aks(open,c.MEHAcoustics,c.MEH);assert.equal((s.match(/Driver Def=/g)||[]).length,open.p.count);assert.equal((s.match(/Waveguide 'Entry /g)||[]).length,open.p.count);assert.equal((s.match(/Enclosure 'Shared sealed rear'/g)||[]).length,1);const nodes=[...s.matchAll(/Waveguide 'Entry \d+'\nNode=\d+=(\d+)/g)].map(m=>m[1]);assert.equal(new Set(nodes).size,1);assert.ok(!/PLACEHOLDER|NaN|Infinity/.test(s));assert.throws(()=>F.aks(a,c.MEHAcoustics,c.MEH),/open collectors/);});
