/* Guided interface. Geometry changes are explicit, cancellable and reversible. */
module.exports=function(root){
'use strict';
const F=root.MEHAssistedFlow,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number.isFinite(n)?n.toFixed(d):'—';
function init(host,api){
 const doc=host.ownerDocument,form=host.querySelector('#briefForm'),legacy=host.querySelector('#candidateResults');
 const view=doc.createElement('div');view.className='guided-flow';view.innerHTML=`
 <nav class="guided-steps" aria-label="Design steps"><button type="button" data-step="goals">1 Goals</button><button type="button" data-step="drivers">2 Drivers</button><button type="button" data-step="results" disabled>3 Designs</button><button type="button" data-step="refine" disabled>4 Refine</button></nav>
 <section data-stage="goals"><h3>Your goals</h3><div data-goal-fields class="brief-grid"></div><div class="brief-grid">
 ${number('maxWidthMM','Maximum assembly width / mm',1000,200,3000)}${number('maxDepthMM','Maximum assembly depth / mm',1000,100,3000)}${number('targetSPL','Target mid-band SPL / dB (optional)','',60,150)}${number('distanceM','Listening distance / m',3,.5,30,.1)}${number('budget','Driver budget (optional)','',0,100000)}
 <div class="brief-field"><label for="guided-priority">Design priority</label><select id="guided-priority" data-goal="priority"><option value="balanced">Balanced</option><option value="compact">Smaller assembly</option><option value="headroom">More modeled headroom</option></select></div></div>
 <p class="hint">Coverage is one nominal angle in all directions. Actual beamwidth and whole-speaker loudness still need verification.</p><button type="button" class="primary" data-action="drivers">Find driver options</button></section>
 <section data-stage="drivers" hidden><h3>Choose your drivers</h3><div class="guided-choice-mode"><button type="button" data-action="suggest">Suggested combinations</button><button type="button" data-action="own">Use my drivers</button></div><p data-shortlist-note class="hint"></p><div data-driver-choices class="guided-cards"></div><div data-driver-fields class="brief-grid"></div><details><summary>Driver quotes &amp; enclosure</summary><p class="hint">Use the same currency for budget and quotes. Driver costs exclude cabinet, DSP, amplifier and shipping.</p><div class="brief-grid">${number('midPrice','Price per cone mid (optional)','',0,100000)}${number('compressionPrice','Compression driver price (optional)','',0,100000)}</div><div data-enclosure-fields class="brief-grid"></div></details><p data-cost class="hint"></p><div class="guided-actions"><button type="button" data-action="goals">Back to goals</button><button type="button" class="primary" data-action="generate">Generate designs</button></div></section>
 <section data-stage="results" hidden><h3>Compare designs</h3><p class="hint">Best options from this bounded search. Preview the geometry, then apply the design you prefer.</p><div data-designs class="guided-cards"></div><div class="guided-actions"><button type="button" data-action="drivers">Change drivers</button><button type="button" data-action="restore" hidden>Exit preview</button></div></section>
 <section data-stage="refine" hidden><h3>Refine design</h3><div data-assessment></div><div class="guided-actions"><button type="button" data-action="analysis">Show analysis</button><button type="button" data-action="manual">Open in Manual</button></div><h4>What would you like to improve?</h4><div class="brief-field"><label for="guided-refine-priority">Priority</label><select id="guided-refine-priority"><option value="balanced">Smoother modeled response</option><option value="compact">Smaller assembly</option><option value="headroom">More modeled headroom</option></select></div>
 <div class="guided-locks"><label><input type="checkbox" data-lock="drivers" checked> Keep these drivers</label><label><input type="checkbox" data-lock="profile"> Keep horn dimensions</label><label><input type="checkbox" data-lock="entry"> Keep entry size and position</label></div><p class="hint">Ports, front space, driver placement and rear volume are recalculated together within your limits. Locked dimensions stay fixed.</p><div class="guided-actions"><button type="button" data-action="goals">Change goals</button><button type="button" class="primary" data-action="improve">Compare improvements</button><button type="button" data-action="undo" hidden>Undo applied change</button></div></section>
 <div class="guided-footer"><p data-status role="status" aria-live="polite"></p><button type="button" data-action="cancel" hidden>Cancel search</button><p class="hint">Design estimates for the cone mids. No complete HF, crossover or measured coverage prediction.</p></div>`;
 form.prepend(view);
 const $=s=>view.querySelector(s),$$=s=>[...view.querySelectorAll(s)];
 for(const [slot,keys]of [['goal',['coverage','lowHz','handoffHz','designDriveVoltageRms','count']],['driver',['midDriver','compressionDriver']],['enclosure',['rearLayout','rearConcept','sharedRearShape']]])for(const k of keys){const el=host.querySelector('#brief-'+k);$(`[data-${slot}-fields]`).append(el.closest('.brief-field'));}
 form.querySelector('.brief-actions').hidden=true;
 // Old results are retained for backwards-compatible exports; this panel owns presentation.
 legacy.hidden=true;host.querySelector('.setup-intro p').textContent='Goals → drivers → designs → refine.';
 let stage='goals',run=0,busy=false,result=null,baseline=null,active=null,undo=null,preview=false,own=false,refining=false;
 const goals=()=>Object.fromEntries($$('[data-goal]').map(el=>[el.dataset.goal,el.value]));
 const setGoals=g=>{for(const el of $$('[data-goal]'))el.value=g?.[el.dataset.goal]??F.defaults[el.dataset.goal]??'';};
 const signature=s=>JSON.stringify(Object.keys(s).sort().map(k=>[k,s[k]]));
 function status(text,error=false){$('[data-status]').textContent=text;$('[data-status]').classList.toggle('error',error);}
 function restorePreview(){if(preview){api.restorePreview();preview=false;}$('[data-action="restore"]').hidden=true;}
 function cancel(){run++;busy=false;host.removeAttribute('aria-busy');$('[data-action="cancel"]').hidden=true;for(const el of $$('[data-action="generate"],[data-action="improve"]'))el.disabled=false;}
 function show(next){if(next==='results'&&!result||next==='refine'&&!active)return;restorePreview();stage=next;for(const el of $$('[data-stage]'))el.hidden=el.dataset.stage!==stage;for(const b of $$('[data-step]')){b.setAttribute('aria-current',b.dataset.step===stage?'step':'false');b.disabled=b.dataset.step==='results'?!result:b.dataset.step==='refine'?!active:false;}host.querySelector('#setupTitle').textContent=stage==='refine'?'Refine design':'Assisted design';}
 function validateGoals(){const c=F.goals(goals());for(const el of $$('[data-goal]'))el.removeAttribute('aria-invalid');if(!c.ok){for(const e of c.errors)$(`[data-goal="${e.field}"]`)?.setAttribute('aria-invalid','true');status(c.errors.map(e=>e.message).join(' '),true);return null;}return c.value;}
 function updateCost(){const c=F.goals(goals());if(!c.ok)return;const q=F.cost(api.readBrief(),c.value);$('[data-cost]').textContent=q.known?`Quoted driver total: ${q.total.toFixed(2)}${q.within===true?' · within budget':q.within===false?' · over budget':''}.`:(c.value.budget!==null?'Budget is not yet checked: enter both unit prices.':'Add quotes if you want to compare cost.');}
 function suggestions(){const g=validateGoals();if(!g)return false;const r=F.driverChoices(api.readBrief(),g);$('[data-shortlist-note]').textContent=r.choices.length?r.scope:'No catalogue combination matches these goals. Try more space or another handoff frequency, or choose your drivers.';$('[data-driver-choices]').innerHTML=r.choices.map((d,i)=>`<article class="guided-card"><strong>${esc(d.midName)}</strong><p>+ ${esc(d.compressionName)}</p><p class="hint">Starting mouth ≈ ${fmt(d.seedWidthMM)} mm · recommended handoff ≥ ${d.minimumHandoffHz} Hz. ${esc(d.notes)}</p><div class="guided-actions"><button type="button" data-pair="${i}">Choose pair</button><a href="${esc(d.midSource)}" target="_blank" rel="noopener">Mid specs</a><a href="${esc(d.compressionSource)}" target="_blank" rel="noopener">HF specs</a></div></article>`).join('');for(const b of $$('[data-pair]'))b.onclick=()=>{const d=r.choices[Number(b.dataset.pair)],old=api.readBrief();api.writeBrief({...old,midDriver:d.midDriver,compressionDriver:d.compressionDriver});if(old.midDriver!==d.midDriver)$('[data-goal="midPrice"]').value='';if(old.compressionDriver!==d.compressionDriver)$('[data-goal="compressionPrice"]').value='';api.updateSuggestions();for(const card of $$('[data-pair]'))card.setAttribute('aria-pressed',String(card===b));status('Driver pair selected. Generate to check complete layouts.');invalidate();updateCost();};$('[data-driver-choices]').hidden=own;updateCost();return true;}
 function invalidate(){cancel();restorePreview();result=null;$('[data-designs]').innerHTML='';for(const b of $$('[data-step="results"]'))b.disabled=true;}
 function list(items){return '<ul>'+items.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';}
 function renderAssessment(){if(!active)return;const a=active.guided;$('[data-assessment]').innerHTML='<div class="guided-check"><h4>Checks passed</h4>'+list(a.passed)+'</div>'+(a.attention.length?'<div class="guided-check attention"><h4>Needs attention</h4>'+list(a.attention)+'</div>':'')+'<details><summary>Still to verify</summary>'+list(a.verify)+'</details>';$('#guided-refine-priority').value=goals().priority;$('[data-action="undo"]').hidden=!undo;}
 function changes(c){if(!active)return '';const a=active.guided,b=c.guided;return `<p class="guided-delta">Current → proposed<br>Width ${fmt(a.dimensions.widthMM)} → ${fmt(b.dimensions.widthMM)} mm<br>Depth ${fmt(a.dimensions.depthMM)} → ${fmt(b.dimensions.depthMM)} mm<br>Response variation ${fmt(active.acousticSummary.mouthPowerRippleDB,1)} → ${fmt(c.acousticSummary.mouthPowerRippleDB,1)} dB<br>Modeled drive headroom ${fmt(a.headroomDB,1)} → ${fmt(b.headroomDB,1)} dB</p>`;}
 function renderResults(){const g=result.guidedGoals;$('[data-designs]').innerHTML=result.candidates.map((c,i)=>{const d=c.guided.dimensions,q=c.acousticSummary;return `<article class="guided-card"><strong>${i===0?'Recommended starting point':'Alternative '+i}</strong><p>${fmt(d.widthMM)} mm wide × ${fmt(d.depthMM)} mm deep</p><p>Modeled response variation: ${fmt(q.mouthPowerRippleDB,1)} dB<br>Modeled drive headroom: ${fmt(c.guided.headroomDB,1)} dB</p>${changes(c)}<details><summary>Design details</summary><p>Entry Ø${fmt(c.state.port,1)} mm · tube ${fmt(c.state.neck+3,1)} mm · front air ${fmt(c.analysis.frontV)} cm³ per mid · rear ${fmt(q.rearNetVolumeTotalL,1)} L total.</p>${list(c.guided.attention)}</details><div class="guided-actions"><button type="button" data-preview="${i}">Preview</button><button type="button" class="primary" data-apply="${i}">Apply design</button></div></article>`;}).join('');for(const b of $$('[data-preview]'))b.onclick=()=>{if(!fresh())return;const c=result.candidates[Number(b.dataset.preview)];api.preview(c.state);preview=true;$('[data-action="restore"]').hidden=false;status('Preview only. Apply design to keep it; Exit preview restores your current horn.');};for(const b of $$('[data-apply]'))b.onclick=()=>apply(Number(b.dataset.apply));status(`${result.tested} layouts checked. ${result.candidates.length} options, ranked for ${g.priority==='compact'?'smaller size':g.priority==='headroom'?'modeled headroom':'the balanced acoustic objective'}.`);}
 function fresh(){api.flush();if(!baseline||signature(api.getState())!==signature(baseline)){invalidate();status('The current design changed. Generate fresh options before applying.',true);return false;}return true;}
 function apply(i){if(!fresh())return;const c=result.candidates[i];restorePreview();undo={state:{...api.getState()},brief:api.readBrief(),goals:goals(),active};active=c;api.apply(result,i);baseline={...api.getState()};renderAssessment();show('refine');status('Design applied. Refine it here or open Manual for individual dimensions.');}
 async function generate(improve=false){const g=validateGoals();if(!g)return;const valid=api.updateSuggestions();if(!valid.ok){status(valid.errors.join(' '),true);show('drivers');return;}if(improve&&!$('[data-lock="drivers"]').checked){own=false;suggestions();show('drivers');status('Choose another driver pair, then generate a new design.');return;}
  invalidate();api.flush();baseline={...api.getState()};const token=++run;busy=true;refining=improve;host.setAttribute('aria-busy','true');$('[data-action="cancel"]').hidden=false;for(const b of $$('[data-action="generate"],[data-action="improve"]'))b.disabled=true;status('Checking layouts…');
  try{const r=await F.generate(api.readBrief(),g,{currentState:baseline,lockProfile:improve&&$('[data-lock="profile"]').checked,lockEntry:improve&&$('[data-lock="entry"]').checked,shouldCancel:()=>token!==run,onProgress:p=>{if(token===run)status(`${p.stage}: ${p.tested} layouts checked…`);}});if(token!==run||r.cancelled)return;if(!r.ok){status((r.errors||['No candidate passed.']).join(' ')+' Your current design is unchanged.',true);return;}result=r;renderResults();show('results');}catch(e){if(token===run)status('Could not finish: '+e.message+'. Your current design is unchanged.',true);}finally{if(token===run){busy=false;host.removeAttribute('aria-busy');$('[data-action="cancel"]').hidden=true;for(const b of $$('[data-action="generate"],[data-action="improve"]'))b.disabled=false;}}
 }
 for(const b of $$('[data-step]'))b.onclick=()=>{cancel();show(b.dataset.step);};
 for(const b of $$('[data-action]'))b.onclick=()=>{const k=b.dataset.action;if(k==='cancel'){cancel();status('Search cancelled. Your current design is unchanged.');}else if(k==='restore')restorePreview();else if(k==='goals'){cancel();show('goals');}else if(k==='drivers'){cancel();if(suggestions())show('drivers');}else if(k==='suggest'){own=false;suggestions();}else if(k==='own'){own=true;$('[data-driver-choices]').hidden=true;$('[data-shortlist-note]').textContent='Choose from the catalogue below. Models without complete motor data remain available in Manual.';}else if(k==='generate')generate();else if(k==='improve'){$('[data-goal="priority"]').value=$('#guided-refine-priority').value;generate(true);}else if(k==='analysis')api.showAnalysis();else if(k==='manual'){cancel();restorePreview();api.manual();}else if(k==='undo'&&undo){const old=undo;cancel();restorePreview();active=old.active;undo=null;result=null;api.restore(old.state);api.writeBrief(old.brief);setGoals(old.goals);api.updateSuggestions();if(active){renderAssessment();show('refine');}else show('goals');status('Previous design restored.');}};
 form.onsubmit=e=>{e.preventDefault();stage==='goals'?(suggestions()&&show('drivers')):generate(stage==='refine');};
 form.oninput=form.onchange=e=>{if(!e.target.matches('input,select'))return;if(e.target.matches('[data-lock],#guided-refine-priority'))return;const id=e.target.id;if(id==='brief-midDriver')$('[data-goal="midPrice"]').value='';if(id==='brief-compressionDriver')$('[data-goal="compressionPrice"]').value='';invalidate();api.updateSuggestions();updateCost();status('Goals changed. Generate new options when ready.');};
 show('goals');
 return {get snapshot(){return {version:1,goals:goals(),brief:api.readBrief()};},get stage(){return stage;},get result(){return result;},generate,cancel,show,exitPreview:restorePreview,
  reset(saved){cancel();restorePreview();result=null;active=null;undo=null;setGoals(saved?.goals||F.defaults);if(saved?.brief)api.writeBrief(saved.brief);show('goals');status('Choose your goals to begin.');},
  onGeometryChange(){if(active&&signature(api.getState())!==signature(active.state)){active=null;if(stage==='refine')show('goals');status('Design changed outside Assisted. Generate fresh options to reassess it.');}if(busy&&baseline&&signature(api.getState())!==signature(baseline)){cancel();status('Design changed. Search cancelled.');}}
 };
}
function number(key,label,value,min,max,step=1){return `<div class="brief-field"><label for="guided-${key}">${label}</label><input id="guided-${key}" data-goal="${key}" type="number" value="${value}" min="${min}" max="${max}" step="${step}"></div>`;}
return {init};
};
