/* Guided interface. Presentation is independent of the unchanged physical solver. */
module.exports=function(root){
'use strict';
const F=root.MEHAssistedFlow,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number.isFinite(n)?n.toFixed(d):'—';
function init(host,api){
 const doc=host.ownerDocument,form=host.querySelector('#briefForm'),legacy=host.querySelector('#candidateResults');
 const view=doc.createElement('div');view.className='guided-flow';view.innerHTML=`
 <nav class="guided-steps" aria-label="Design steps"><button type="button" data-step="goals"><span>1</span>Goals</button><button type="button" data-step="drivers"><span>2</span>Drivers</button><button type="button" data-step="results" disabled><span>3</span>Designs</button><button type="button" data-step="refine" disabled><span>4</span>Refine</button></nav>
 <p class="guided-brief" data-brief-summary hidden></p>
 <section data-stage="goals"><h3 tabindex="-1">What should your horn do?</h3>
 <fieldset class="guided-group"><legend>Sound</legend><div data-band-fields class="brief-grid two"></div><div data-coverage-fields class="brief-grid"></div></fieldset>
 <fieldset class="guided-group"><legend>Space available</legend><div class="brief-grid two">${number('maxWidthMM','Max width / mm',1000,200,3000)}${number('maxDepthMM','Max depth / mm',1000,100,3000)}</div></fieldset>
 <div class="brief-field"><label for="guided-priority">What matters most?</label><select id="guided-priority" data-goal="priority"><option value="balanced">Balanced design</option><option value="compact">Smaller assembly</option><option value="headroom">More modeled headroom</option></select></div>
 <details data-optional-goals><summary>Output &amp; budget <span class="guided-optional">Optional</span></summary><div class="brief-grid two">${number('targetSPL','Mid-band target / dB','',60,150)}${number('distanceM','Distance / m',3,.5,30,.1)}</div><div data-drive-fields class="brief-grid"></div>${number('budget','Driver budget / your currency','',0,100000)}<p class="hint">Budget uses your quotes. Loudness is a mid-band estimate.</p></details></section>
 <section data-stage="drivers" hidden><h3 tabindex="-1">Choose a driver combination</h3><div class="guided-choice-mode" role="group" aria-label="Driver selection"><button type="button" data-action="suggest" aria-pressed="true">Explore options</button><button type="button" data-action="own" aria-pressed="false">Choose my own</button></div>
 <div class="guided-selected" data-selected-driver aria-live="polite"></div><div data-driver-choices class="guided-cards"></div><button class="guided-text-button" type="button" data-action="more" hidden>More combinations</button><p data-shortlist-note class="hint"></p><div data-driver-fields class="brief-grid" hidden></div>
 <details data-enclosure><summary>Driver count &amp; enclosure</summary><div data-enclosure-fields class="brief-grid"></div></details><details data-quotes><summary>Driver quotes <span data-quote-summary class="guided-optional">Optional</span></summary><p class="hint">Same currency as your budget; drivers only.</p><div class="brief-grid two">${number('midPrice','Price per cone mid','',0,100000)}${number('compressionPrice','Compression driver','',0,100000)}</div><p data-cost class="hint"></p></details></section>
 <section data-stage="results" hidden><h3 tabindex="-1">Choose your starting design</h3><p class="hint" data-result-intro></p><div data-designs class="guided-cards"></div><button type="button" class="guided-text-button" data-action="restore" hidden>Exit preview</button></section>
 <section data-stage="refine" hidden><h3 tabindex="-1">Make it yours</h3><div data-current-summary class="guided-current"></div><p class="guided-stale" data-goals-changed hidden>Your goals have changed. Compare new options to check them.</p><div data-assessment></div><button type="button" class="guided-text-button" data-action="analysis">Explore sound analysis ↗</button>
 <fieldset class="guided-group"><legend>Improve this design</legend><div class="brief-field"><label for="guided-refine-priority">Priority</label><select id="guided-refine-priority"><option value="balanced">Smoother modeled response</option><option value="compact">Smaller assembly</option><option value="headroom">More modeled headroom</option></select></div><details><summary>Keep parts of this design</summary><div class="guided-locks"><label><input type="checkbox" data-lock="drivers" checked> Keep these drivers</label><label><input type="checkbox" data-lock="profile"> Keep horn dimensions</label><label><input type="checkbox" data-lock="entry"> Keep entry size and position</label></div></details></fieldset>
 <div class="guided-actions"><button type="button" class="guided-text-button" data-action="manual">Edit individual dimensions ↗</button><button type="button" data-action="undo" hidden>Undo last change</button></div></section>
 <div class="guided-footer"><div class="guided-progress" data-progress hidden><span class="calculation-spinner" aria-hidden="true"></span><span>Finding a design that fits</span><button type="button" data-action="cancel">Cancel</button></div><p data-status role="status" aria-live="polite"></p><div class="guided-footer-actions"><button type="button" data-action="back" hidden>Back</button><button type="button" class="primary" data-action="next">Find driver options <span aria-hidden="true">→</span></button></div><p class="guided-scope">Estimates for the mids · full coverage &amp; crossover unverified</p></div>`;
 form.prepend(view);
 const $=s=>view.querySelector(s),$$=s=>[...view.querySelectorAll(s)];
 for(const [slot,keys]of [['band',['lowHz','handoffHz']],['coverage',['coverage']],['drive',['designDriveVoltageRms']],['driver',['midDriver','compressionDriver']],['enclosure',['count','rearLayout','rearConcept','sharedRearShape']]])for(const k of keys){$(`[data-${slot}-fields]`).append(host.querySelector('#brief-'+k).closest('.brief-field'));}
 for(const [key,text]of Object.entries({lowHz:'Low end / Hz',handoffHz:'Handoff / Hz',coverage:'Coverage angle / °',designDriveVoltageRms:'Design drive / V RMS per mid'}))host.querySelector(`label[for="brief-${key}"]`).textContent=text;
 form.querySelector('.brief-actions').hidden=true;legacy.hidden=true;host.querySelector('.setup-intro').hidden=true;
 // Keep the detailed evaluation description accessible through Methods, without repeating it under every step.
 for(const child of [...form.children])if(child!==view)child.hidden=true;
 let stage='goals',run=0,busy=false,result=null,baseline=null,active=null,undo=null,preview=false,own=false,more=false,choices=[],selected=0,appliedContext=null;
 const goals=()=>Object.fromEntries($$('[data-goal]').map(el=>[el.dataset.goal,el.value]));
 const setGoals=g=>{for(const el of $$('[data-goal]'))el.value=g?.[el.dataset.goal]??F.defaults[el.dataset.goal]??'';};
 const signature=s=>JSON.stringify(Object.keys(s).sort().map(k=>[k,s[k]]));
 const context=()=>({brief:{...api.readBrief()},goals:goals()});
 function status(text,error=false){$('[data-status]').textContent=text;$('[data-status]').classList.toggle('error',error);}
 function briefSummary(){const b=api.readBrief(),g=goals();$('[data-brief-summary]').textContent=`${b.lowHz}–${b.handoffHz} Hz · ${b.coverage}° · up to ${g.maxWidthMM} × ${g.maxDepthMM} mm`;$('[data-brief-summary]').hidden=stage==='goals';}
 function restorePreview(){if(preview){api.restorePreview();preview=false;}$('[data-action="restore"]').hidden=true;for(const card of $$('[data-design-card]'))card.removeAttribute('data-previewing');}
 function footer(){const b=$('[data-action="next"]');b.disabled=busy;b.removeAttribute('data-apply');b.innerHTML=stage==='goals'?'Find driver options <span aria-hidden="true">→</span>':stage==='drivers'?'Generate designs <span aria-hidden="true">→</span>':stage==='results'?'Use this design':'Compare improvements';if(stage==='results')b.dataset.apply=String(selected);$('[data-action="back"]').hidden=stage==='goals';$('[data-action="back"]').textContent=stage==='refine'?'Edit goals':'Back';$('[data-progress]').hidden=!busy;view.dataset.busy=String(busy);}
 function cancel(){run++;busy=false;host.removeAttribute('aria-busy');footer();}
 function show(next,{focus=true}={}){
  if(next==='results'&&!result||next==='refine'&&!active)return;restorePreview();stage=next;view.dataset.stage=stage;api.stageChanged?.(stage);
  for(const el of $$('[data-stage]'))el.hidden=el.dataset.stage!==stage;
  for(const b of $$('[data-step]')){b.setAttribute('aria-current',b.dataset.step===stage?'step':'false');b.disabled=b.dataset.step==='results'?!result:b.dataset.step==='refine'?!active:false;}
  if(stage==='refine')renderAssessment();briefSummary();footer();
  if(focus){$(`[data-stage="${stage}"] h3`).focus({preventScroll:true});host.closest('.controls')?.scrollTo?.({top:0,behavior:'smooth'});}
 }
 function validateGoals(){const c=F.goals(goals());for(const el of $$('[data-goal]'))el.removeAttribute('aria-invalid');if(!c.ok){show('goals');for(const e of c.errors){const el=$(`[data-goal="${e.field}"]`);el?.setAttribute('aria-invalid','true');const detail=el?.closest('details');if(detail)detail.open=true;}status(c.errors.map(e=>e.message).join(' '),true);$('[aria-invalid="true"]')?.focus();return null;}return c.value;}
 function updateCost(){const c=F.goals(goals());if(!c.ok)return;const q=F.cost(api.readBrief(),c.value);$('[data-cost]').textContent=q.known?`Total ${q.total.toFixed(2)}${q.within===true?' · within budget':q.within===false?' · over budget':''}.`:(c.value.budget!==null?'Add both unit prices to check your budget.':'Prices are optional.');$('[data-quote-summary]').textContent=q.known?q.total.toFixed(2):c.value.budget!==null?'Not checked':'Optional';}
 function selectedDriver(){const b=api.readBrief(),m=root.MEH.drivers.mid[b.midDriver],d=root.MEH.drivers.compression[b.compressionDriver];$('[data-selected-driver]').innerHTML=`<span class="guided-eyebrow">Selected combination</span><strong>${esc(b.count)} × ${esc(m?.name||'Choose a mid')}</strong><span>+ ${esc(d?.name||'Choose a compression driver')}</span>`;for(const button of $$('[data-pair]')){const c=choices[Number(button.dataset.pair)],on=c.midDriver===b.midDriver&&c.compressionDriver===b.compressionDriver;button.setAttribute('aria-pressed',String(on));button.textContent=on?'Selected':'Select';button.closest('article').classList.toggle('selected',on);}}
 function renderChoices(){
  $('[data-driver-choices]').innerHTML=choices.slice(0,more?6:3).map((d,i)=>`<article class="guided-card guided-driver"><div class="guided-card-top"><div><strong>${esc(d.midName)}</strong><p>+ ${esc(d.compressionName)}</p></div><button type="button" data-pair="${i}" aria-label="Select ${esc(d.midName)} with ${esc(d.compressionName)}">Select</button></div><p class="guided-driver-fit">Starting mouth ≈ ${fmt(d.seedWidthMM)} mm · handoff ≥ ${d.minimumHandoffHz} Hz</p><details><summary>Specs &amp; fit notes</summary><p>${esc(d.notes)}</p><div class="guided-actions"><a href="${esc(d.midSource)}" target="_blank" rel="noopener">Mid datasheet ↗</a><a href="${esc(d.compressionSource)}" target="_blank" rel="noopener">Compression driver ↗</a></div></details></article>`).join('');
  for(const b of $$('[data-pair]'))b.onclick=()=>{const d=choices[Number(b.dataset.pair)],old=api.readBrief();api.writeBrief({...old,midDriver:d.midDriver,compressionDriver:d.compressionDriver});if(old.midDriver!==d.midDriver)$('[data-goal="midPrice"]').value='';if(old.compressionDriver!==d.compressionDriver)$('[data-goal="compressionPrice"]').value='';api.updateSuggestions();invalidate();selectedDriver();updateCost();status('Combination selected. Ready to generate.');};
  $('[data-driver-choices]').hidden=own;$('[data-driver-fields]').hidden=!own;$('[data-action="more"]').hidden=own||choices.length<=3;$('[data-action="more"]').textContent=more?'Fewer combinations':`Show ${Math.max(0,choices.length-3)} more combinations`;
  for(const k of ['suggest','own'])$(`[data-action="${k}"]`).setAttribute('aria-pressed',String(k==='own'?own:!own));selectedDriver();
 }
 function suggestions(){const g=validateGoals();if(!g)return false;const r=F.driverChoices(api.readBrief(),g);choices=r.choices||[];renderChoices();$('[data-shortlist-note]').textContent=own?'Models without complete motor data can be explored in Manual.':choices.length?'Shortlisted by size and handoff. Generation checks the complete layout.':'No shortlist fits these goals. Try more space, change the handoff, or choose your own.';updateCost();return true;}
 function invalidate(){cancel();restorePreview();result=null;$('[data-designs]').innerHTML='';$('[data-step="results"]').disabled=true;}
 const list=items=>'<ul>'+items.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';
 function renderAssessment(){if(!active)return;const a=active.guided,changed=appliedContext&&signature(context())!==signature(appliedContext);$('[data-goals-changed]').hidden=!changed;$('[data-assessment]').innerHTML=`<details class="guided-check"><summary>${a.passed.length} checks passed</summary>${list(a.passed)}</details>${a.attention.length?'<details class="guided-check attention" open><summary>Needs attention</summary>'+list(a.attention)+'</details>':''}<details><summary>Still to verify</summary>${list(a.verify)}</details>`;$('[data-current-summary]').innerHTML=`<span class="guided-eyebrow">Current design</span><strong>${fmt(a.dimensions.widthMM)} <small>wide</small> × ${fmt(a.dimensions.depthMM)} <small>deep · mm</small></strong>`;$('#guided-refine-priority').value=goals().priority;$('[data-action="undo"]').hidden=!undo;}
 function changes(c){if(!active)return '';const a=active.guided,b=c.guided;return `<table class="guided-delta"><caption>Current → proposed</caption><tbody><tr><th>Width / mm</th><td>${fmt(a.dimensions.widthMM)}</td><td>${fmt(b.dimensions.widthMM)}</td></tr><tr><th>Depth / mm</th><td>${fmt(a.dimensions.depthMM)}</td><td>${fmt(b.dimensions.depthMM)}</td></tr><tr><th>Variation / dB</th><td>${fmt(active.acousticSummary.mouthPowerRippleDB,1)}</td><td>${fmt(c.acousticSummary.mouthPowerRippleDB,1)}</td></tr><tr><th>Headroom / dB</th><td>${fmt(a.headroomDB,1)}</td><td>${fmt(b.headroomDB,1)}</td></tr></tbody></table>`;}
 function selectDesign(i){selected=i;for(const card of $$('[data-design-card]'))card.classList.toggle('selected',Number(card.dataset.designCard)===i);footer();}
 function renderResults(){const g=result.guidedGoals;selected=0;$('[data-result-intro]').textContent=`${result.tested} layouts checked · ranked for ${g.priority==='compact'?'smaller size':g.priority==='headroom'?'modeled headroom':'balanced performance'}.`;$('[data-designs]').innerHTML=result.candidates.map((c,i)=>{const d=c.guided.dimensions,q=c.acousticSummary;return `<article class="guided-card guided-design" data-design-card="${i}"><div class="guided-card-top"><strong>${i===0?'Recommended':'Option '+(i+1)}</strong><span class="guided-option">${i+1} / ${result.candidates.length}</span></div><p class="guided-size">${fmt(d.widthMM)} <small>×</small> ${fmt(d.depthMM)} <small>mm</small></p><div class="guided-metrics"><span>Response variation<b>${fmt(q.mouthPowerRippleDB,1)} <small>dB</small></b></span><span>Drive headroom<b>${fmt(c.guided.headroomDB,1)} <small>dB</small></b></span></div>${changes(c)}<details><summary>Dimensions &amp; model notes</summary><p>Entry Ø${fmt(c.state.port,1)} mm · tube ${fmt(c.state.neck+3,1)} mm · front air ${fmt(c.analysis.frontV)} cm³ per mid · rear ${fmt(q.rearNetVolumeTotalL,1)} L total.</p>${list(c.guided.attention)}</details><button type="button" data-preview="${i}">Preview this design</button></article>`;}).join('');for(const b of $$('[data-preview]'))b.onclick=()=>{if(!fresh())return;const i=Number(b.dataset.preview),c=result.candidates[i];selectDesign(i);preview=true;api.preview(c.state,{label:i===0?'Recommended design':'Option '+(i+1),onApply:()=>apply(i),onClose:restorePreview});$(`[data-design-card="${i}"]`).dataset.previewing='true';$('[data-action="restore"]').hidden=false;status('Previewing. Use this design to keep it.');};selectDesign(0);status('Choose an option to preview, or use the recommended design.');}
 function fresh(){api.flush();if(!baseline||signature(api.getState())!==signature(baseline)){invalidate();status('The current design changed. Generate fresh options before applying.',true);return false;}return true;}
 function apply(i){if(!fresh())return;const c=result.candidates[i];restorePreview();undo={state:{...api.getState()},...(appliedContext||context()),active};active=c;api.apply(result,i);appliedContext=context();baseline={...api.getState()};renderAssessment();show('refine');status('Design applied.');}
 async function generate(improve=false){const g=validateGoals();if(!g)return;const valid=api.updateSuggestions();if(!valid.ok){show('drivers');own=true;renderChoices();status(valid.errors.join(' '),true);return;}if(improve&&!$('[data-lock="drivers"]').checked){own=false;suggestions();show('drivers');status('Choose another combination, then generate.');return;}
  invalidate();api.flush();baseline={...api.getState()};const token=++run;busy=true;host.setAttribute('aria-busy','true');footer();status('Checking layouts…');
  try{const r=await F.generate(api.readBrief(),g,{currentState:baseline,lockProfile:improve&&$('[data-lock="profile"]').checked,lockEntry:improve&&$('[data-lock="entry"]').checked,shouldCancel:()=>token!==run,onProgress:p=>{if(token===run)status(`${p.stage} · ${p.tested} checked`);}});if(token!==run||r.cancelled)return;if(!r.ok){status((r.errors||['No candidate passed.']).join(' ')+' Current design kept.',true);return;}result=r;renderResults();show('results');}catch(e){if(token===run)status('Could not finish: '+e.message+'. Current design kept.',true);}finally{if(token===run){busy=false;host.removeAttribute('aria-busy');footer();}}
 }
 function next(){if(busy)return;if(stage==='goals'){if(suggestions())show('drivers');}else if(stage==='drivers')generate();else if(stage==='results')apply(selected);else{$('[data-goal="priority"]').value=$('#guided-refine-priority').value;generate(true);}}
 function navigate(nextStage){cancel();if(nextStage==='drivers'){if(!suggestions())return;}show(nextStage);}
 for(const b of $$('[data-step]'))b.onclick=()=>navigate(b.dataset.step);
 for(const b of $$('[data-action]'))b.onclick=()=>{const k=b.dataset.action;if(k==='next')next();else if(k==='back')navigate(stage==='drivers'?'goals':stage==='results'?'drivers':'goals');else if(k==='cancel'){cancel();status('Search cancelled. Current design kept.');}else if(k==='restore'){restorePreview();status('Current design restored in the viewer.');}else if(k==='suggest'||k==='own'){own=k==='own';suggestions();}else if(k==='more'){more=!more;renderChoices();}else if(k==='analysis')api.showAnalysis();else if(k==='manual'){cancel();restorePreview();api.manual();}else if(k==='undo'&&undo){const old=undo;cancel();restorePreview();active=old.active;undo=null;result=null;api.restore(old.state);api.writeBrief(old.brief);setGoals(old.goals);api.updateSuggestions();appliedContext=active?context():null;show(active?'refine':'goals');status('Previous design restored.');}};
 form.onsubmit=e=>{e.preventDefault();next();};
 form.oninput=form.onchange=e=>{if(!e.target.matches('input,select'))return;if(e.target.matches('[data-lock],#guided-refine-priority')){invalidate();return;}const id=e.target.id;if(id==='brief-midDriver')$('[data-goal="midPrice"]').value='';if(id==='brief-compressionDriver')$('[data-goal="compressionPrice"]').value='';invalidate();api.updateSuggestions();updateCost();selectedDriver();briefSummary();if(stage==='drivers'&&id!=='brief-midDriver'&&id!=='brief-compressionDriver'&&e.type==='change')suggestions();status('Changes ready. Continue when you’re ready.');};
 show('goals',{focus:false});
 return {get snapshot(){return {version:1,goals:goals(),brief:api.readBrief()};},get stage(){return stage;},get result(){return result;},generate,cancel,show,exitPreview:restorePreview,
  reset(saved){cancel();restorePreview();result=null;active=null;undo=null;appliedContext=null;own=false;more=false;choices=[];setGoals(saved?.goals||F.defaults);if(saved?.brief)api.writeBrief(saved.brief);show('goals',{focus:false});status('');},
  onGeometryChange(){if(preview)restorePreview();if(active&&signature(api.getState())!==signature(active.state)){active=null;appliedContext=null;if(stage==='refine')show('goals');$('[data-step="refine"]').disabled=true;status('Design changed outside Assisted. Generate fresh options to reassess.');}if(busy&&baseline&&signature(api.getState())!==signature(baseline)){cancel();status('Design changed. Search cancelled.');}}
 };
}
function number(key,label,value,min,max,step=1){return `<div class="brief-field"><label for="guided-${key}">${label}</label><input id="guided-${key}" data-goal="${key}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" placeholder="Optional"></div>`;}
return {init};
};
