/* Browser-only crossover and A/B study UI. Does not measure sound or invent HF data. */
module.exports=function createCrossoverPanel(root){
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=x=>JSON.parse(JSON.stringify(x)),fmt=(x,d=2)=>Number.isFinite(x)?x.toFixed(d):'—';
function plotSVG(series,phase=false,polar=false){
 const available=series.filter(s=>s.rows?.length),all=available.flatMap(s=>s.rows);if(!all.length)return '';
 const L=62,R=690,T=25,B=240,W=720,H=285,minX=Math.min(...all.map(r=>r.x)),maxX=Math.max(...all.map(r=>r.x)),low=phase?-180:Math.floor(Math.max(-150,Math.min(...all.map(r=>r.y)))/10)*10,high=phase?180:Math.max(low+10,Math.ceil(Math.max(...all.map(r=>r.y))/10)*10),x=f=>L+(polar?(f-minX)/(maxX-minX||1):Math.log(f/minX)/Math.log(maxX/minX||2))*(R-L),y=v=>B-(Math.max(low,Math.min(high,v))-low)/(high-low)*(B-T);
 let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img"><title>${polar?'Normalized polar response':phase?'Summed acoustic phase':'Response comparison'}</title><rect width="${W}" height="${H}" fill="#fcfdfb"/>`;
 for(let i=0;i<=4;i++){const v=low+(high-low)*i/4;svg+=`<path d="M${L} ${y(v)}H${R}" stroke="#dce2dd"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
 for(let i=0;i<=5;i++){const f=polar?minX+(maxX-minX)*i/5:minX*(maxX/minX)**(i/5);svg+=`<text x="${x(f)}" y="263" text-anchor="middle">${fmt(f,0)}</text>`;}
 available.forEach((s,index)=>{let d='',previous=null;for(const r of s.rows){if(!Number.isFinite(r.y)){previous=null;continue;}d+=(previous===null||(phase&&Math.abs(r.y-previous)>180)?'M':'L')+x(r.x).toFixed(2)+' '+y(r.y).toFixed(2);previous=r.y;}svg+=`<path d="${d}" fill="none" stroke="${s.color||['#215e59','#c0693b','#6478aa','#92649b'][index%4]}" stroke-width="2"><title>${esc(s.name)}</title></path>`;});return svg+`<text x="8" y="18">${phase?'deg':'dB'}</text><text x="690" y="282" text-anchor="end">${polar?'Angle · degrees':'Frequency · Hz'}</text></svg>`;
}
function init(host,api={}){
 if(!host)return null;const C=root.MEHCrossoverStudy;if(!C)throw Error('Crossover study module is unavailable.');const document=host.ownerDocument;
 let traces={mid:null,high:null,a:null,b:null},baselineMid=null,result=null,baselineResult=null,abResult=null,search=null,analysis=null,revision=0,disposed=false;
 const refs=[['level','Level reference'],['voltageRms','Terminal voltage · V RMS'],['voltageBasis','Voltage test point / basis'],['distanceM','Distance · m'],['distanceOrigin','Distance / rotation origin'],['environment','Room / test environment'],['window','Gate / window / smoothing'],['calibration','Level calibration ID'],['plane','Polar plane'],['angleDeg','Sum angle · degrees'],['time','Timing reference'],['phasor','Phase convention']];
 const traceCard=(key,label)=>`<section class="cs-trace"><h3>${label}</h3><input type="file" accept=".csv,.json,text/csv,application/json" data-cs-file="${key}" aria-label="Import ${label}"><p data-cs-name="${key}">No trace loaded</p><details><summary>Source and measurement references</summary><div class="cs-controls"><label>Source<select data-cs-source="${key}"><option value="unspecified">Unspecified</option><option value="measured">Measured</option><option value="simulated">Simulated</option><option value="synthetic">Synthetic example</option></select></label>${refs.map(([k,title])=>`<label>${title}<input data-cs-ref="${key}:${k}" ${['voltageRms','distanceM','angleDeg'].includes(k)?'type="number" step="any"':'type="text"'}></label>`).join('')}<label class="cs-check"><input type="checkbox" data-cs-preserved="${key}">Original phase and common timing preserved</label></div></details><button type="button" class="small" data-cs-trace-export="${key}">Export this trace</button></section>`;
 const numeric=(key,label,value,step='any')=>`<label>${label}<input type="number" step="${step}" value="${value}" data-cs-option="${key}"></label>`;
 host.innerHTML=`<summary>Crossover and speaker comparison</summary><style>
 #crossoverStudy .cs-body{padding:5px 16px 18px;font-size:12px;color:#526360}#crossoverStudy p{line-height:1.5}#crossoverStudy .cs-controls,#crossoverStudy .cs-actions{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}#crossoverStudy label{display:flex;flex-direction:column;gap:5px}#crossoverStudy input,#crossoverStudy select{padding:6px;max-width:100%;border:1px solid #cbd5ce;border-radius:4px;background:#fff;color:#284c47}#crossoverStudy input[type=number]{width:90px}#crossoverStudy .cs-check{flex-direction:row;align-items:center}#crossoverStudy .cs-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}#crossoverStudy .cs-trace{padding:10px;border:1px solid #d9dfd9;border-radius:6px;min-width:0}#crossoverStudy .cs-trace h3{margin:4px 0 12px}#crossoverStudy .cs-trace input[type=file]{width:100%;box-sizing:border-box}#crossoverStudy .cs-trace label{max-width:100%}#crossoverStudy .cs-trace input[type=text]{width:220px}#crossoverStudy svg{width:100%;display:block;border:1px solid #d9dfd9;border-radius:5px}#crossoverStudy svg text{font:11px system-ui;fill:#526360}#crossoverStudy .cs-limit{color:#885b32}#crossoverStudy [hidden]{display:none!important}#crossoverStudy button:disabled{opacity:.5}#crossoverStudy .cs-legend{display:flex;gap:12px;flex-wrap:wrap}@media(max-width:650px){#crossoverStudy .cs-grid{grid-template-columns:1fr}}
 </style><div class="cs-body"><p>Use measured complex responses to study the crossover, or compare the same coax with and without a shared horn. The built-in mid model can be captured, but a compatible HF response must be supplied.</p>
 <div class="cs-controls"><label>Study<select data-cs-mode><option value="crossover">Mid + HF crossover</option><option value="compare">MEH versus conventional coax</option></select></label><button type="button" class="small" data-cs-template>Download import template</button><button type="button" class="small" data-cs-protocol>Download measurement protocol</button><button type="button" class="small" data-cs-import-study>Import study</button><input type="file" data-cs-study-file accept=".json" hidden></div>
 <div data-cs-xo><div class="cs-actions"><button type="button" class="small" data-cs-example>Try synthetic example</button><button type="button" class="small" data-cs-capture>Capture current mid model</button><button type="button" class="small" data-cs-freeze>Keep mid as baseline</button><button type="button" class="small" data-cs-clear-baseline>Clear baseline</button></div><p class="cs-limit" data-cs-baseline>No baseline retained. To compare chamber changes: capture the current mid, keep it as baseline, change the chamber in the editor, then capture the new mid.</p><p data-cs-front></p><div class="cs-grid">${traceCard('mid','Mid response')}${traceCard('high','HF / compression response')}</div>
 <details><summary>Filter and alignment settings</summary><div class="cs-controls"><label>Electrical filter<select data-cs-option="filter"><option value="none">None</option><option value="BW1">Butterworth 1st order</option><option value="LR2">Linkwitz–Riley 2nd order</option><option value="LR4" selected>Linkwitz–Riley 4th order</option></select></label>${numeric('fcHz','Crossover · Hz',700)}${numeric('gainMidDb','Mid gain · dB',0)}${numeric('gainHighDb','HF gain · dB',0)}${numeric('delayMidMs','Mid delay · ms',0)}${numeric('delayHighMs','HF delay · ms',0)}<label>Mid polarity<select data-cs-option="polarityMid"><option value="1">Normal</option><option value="-1">Inverted</option></select></label><label>HF polarity<select data-cs-option="polarityHigh"><option value="1">Normal</option><option value="-1">Inverted</option></select></label>${numeric('lowHz','Band low · Hz',300)}${numeric('highHz','Band high · Hz',1400)}${numeric('targetDb','Target level · imported dB',90)}${numeric('phaseWeight','Phase weight · dB/degree',.02)}<label class="cs-check"><input type="checkbox" data-cs-option="allowMixedBasis">Allow measured HF + simulated mid study</label></div><p>References must still match when mixing sources. Any normalization or timing translation must be established outside these files and documented; this tool does not invent that alignment. LR2 commonly needs opposite HF polarity, but the actual traces determine the sum. Gain and delay describe ideal DSP, not passive electrical components.</p></details>
 <div class="cs-actions"><button type="button" class="small" data-cs-calculate>Calculate sum</button><label>Plot<select data-cs-plot-mode><option value="magnitude">Magnitude</option><option value="phase">Summed phase</option></select></label></div><details><summary>Search within chosen limits</summary><div class="cs-controls">${[['fcLowHz','Crossover min · Hz',525],['fcHighHz','Crossover max · Hz',875],['gainLowDb','HF gain min · dB',-3],['gainHighDb','HF gain max · dB',3],['delayLowMs','HF delay min · ms',0],['delayHighMs','HF delay max · ms',.3],['steps','Steps per variable',9]].map(([k,l,v])=>`<label>${l}<input type="number" step="any" value="${v}" data-cs-bound="${k}"></label>`).join('')}<label class="cs-check"><input type="checkbox" data-cs-search-polarity checked>Try both HF polarities</label><button type="button" class="small" data-cs-search>Find best tested settings</button><button type="button" class="small" data-cs-use-search disabled>Use tested settings</button></div><p data-cs-search-status>Search ranks target-level error and component phase disagreement over the chosen band. It cannot validate hardware, distortion or coverage.</p></details></div>
 <div data-cs-ab hidden><p>A is the shared-horn MEH; B is the conventional coax. Use the same driver and declare matching measurement conditions. Response differences alone do not establish a better speaker.</p><div class="cs-grid">${traceCard('a','A · shared horn')}${traceCard('b','B · conventional coax')}</div><div class="cs-controls"><label>Band low · Hz<input data-cs-ab-low type="number" value="200"></label><label>Band high · Hz<input data-cs-ab-high type="number" value="2000"></label><label>Polar frequency · Hz<input data-cs-polar-hz type="number" value="1000"></label><button type="button" class="small" data-cs-compare>Compare responses</button></div></div>
 <p role="status" aria-live="polite" data-cs-status>Import traces or try the clearly synthetic example.</p><div data-cs-plot></div><p class="cs-legend" data-cs-legend></p><div data-cs-polar-plot></div><p data-cs-metrics></p><p class="cs-limit" data-cs-qualification></p><div class="cs-actions"><button type="button" class="small" data-cs-export-result disabled>Export result CSV</button><button type="button" class="small" data-cs-export-study>Export study JSON</button></div>
 <details><summary>Scope and methods</summary><p>Imports preserve frequency, magnitude and phase. Samples are interpolated in log frequency using dB magnitude and unwrapped phase; no extrapolation or interpolation across gaps greater than an octave. Dense sampling is essential when propagation delay causes rapid phase rotation. Phase wraps cannot recover information lost between sparse samples.</p><p>No SPL calibration is invented. Summation requires the same timing, level, voltage, distance, environment, window, calibration, angular plane and phase convention. A/B level comparisons require matching source bases and measurement references; timing is not required because the A/B calculation compares magnitudes. References are declarations supplied by the user, not independently verified measurements.</p><p>Reduced-model captures describe coupled mids and a simplified horn radiation model. HF motor behavior, passive components, distortion, compression and physical fit are not predicted here. A crossover can alter a modeled dip but cannot establish that a chamber resonance is harmless. Verify summed behavior at multiple angles.</p><p><a href="https://www.linkwitzlab.com/filters.htm" target="_blank" rel="noopener">Linkwitz filter transfer functions</a> · <a href="https://www.roomeqwizard.com/help/help_en-GB/html/makingmeasurements.html" target="_blank" rel="noopener">REW timing-reference guidance</a></p></details></div>`;
 const q=s=>host.querySelector('[data-cs-'+s+']'),all=s=>host.querySelectorAll(s),number=el=>el.value.trim()===''?NaN:Number(el.value),mode=()=>q('mode').value;
 function opts(){const out={};all('[data-cs-option]').forEach(el=>{const k=el.dataset.csOption;out[k]=el.type==='checkbox'?el.checked:k==='filter'?el.value:number(el);});return out;}
 function bounds(){const b={tryPolarity:q('search-polarity').checked};all('[data-cs-bound]').forEach(el=>b[el.dataset.csBound]=number(el));return b;}
 function signature(a){return JSON.stringify(a?.p||a?.state||a||null);}
 function syncCards(){for(const k of Object.keys(traces)){const t=traces[k];q(`name="${k}"`).textContent=t?`${t.name} · ${t.basis} · ${t.rows.length} rows${t.provenance?.stale?' · OUTDATED geometry':''}`:'No trace loaded';q(`source="${k}"`).value=t?.basis||'unspecified';q(`source="${k}"`).disabled=!!(t?.provenance?.generatedSynthetic||t?.provenance?.model&&t?.provenance?.inputState);for(const [r]of refs){q(`ref="${k}:${r}"`).value=t?.reference?.[r]??'';q(`ref="${k}:${r}"`).disabled=!!(t?.provenance?.generatedSynthetic||t?.provenance?.model&&t?.provenance?.inputState);}q(`preserved="${k}"`).checked=t?.reference?.phasePreserved===true;q(`preserved="${k}"`).disabled=!!(t?.provenance?.generatedSynthetic||t?.provenance?.model&&t?.provenance?.inputState);q(`trace-export="${k}"`).disabled=!t;}q('freeze').disabled=!traces.mid||traces.mid.provenance?.stale;q('clear-baseline').disabled=!baselineMid;q('baseline').textContent=baselineMid?'Frozen baseline: '+baselineMid.name+'. It retains its original geometry and references; the same HF and filter settings are used for both sums.':'No baseline retained. Capture the mid, keep it as baseline, change chamber geometry, then capture the new mid.';}
 // q accepts attribute fragments as well as ordinary data-cs names.
 function emit(){api.onChange?.(snapshot());}
 function invalidate(message='Settings changed. Calculate to refresh the result.'){revision++;result=null;baselineResult=null;abResult=null;search=null;q('plot').innerHTML='';q('polar-plot').innerHTML='';q('legend').textContent='';q('metrics').textContent='';q('qualification').textContent='';q('export-result').disabled=true;q('use-search').disabled=true;q('status').textContent=message;q('search-status').textContent='Search ranks target-level error and component phase disagreement over the chosen band.';}
 function download(name,text,type){if(api.download){api.download(name,text,type);return;}const URL=root.URL||globalThis.URL,Blob=root.Blob||globalThis.Blob,url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function activeResult(){return mode()==='compare'?abResult:result;}
 function draw(){const r=activeResult();if(!r)return;let series=[];
  if(mode()==='crossover'){const phase=q('plot-mode').value==='phase';series=phase?[{name:'Current sum',color:'#215e59',rows:r.rows.map(v=>({x:v.f,y:v.sumPhaseDeg}))}]:[['midDb','Mid','#6478aa'],['highDb','HF','#c0693b'],['sumDb','Current sum','#215e59']].map(([key,name,color])=>({name,color,rows:r.rows.map(v=>({x:v.f,y:v[key]}))}));if(baselineResult)series.push({name:'Frozen mid baseline sum',color:'#92649b',rows:baselineResult.rows.map(v=>({x:v.f,y:phase?v.sumPhaseDeg:v.sumDb}))});q('plot').innerHTML=plotSVG(series,phase);q('metrics').textContent=`Band variation ${fmt(r.metrics.rippleDb)} dB · target error ${fmt(r.metrics.rmsErrorDb)} dB RMS · overlap-weighted phase difference ${fmt(r.metrics.phaseRmsDeg,1)}° RMS.`+(baselineResult?` Baseline variation ${fmt(baselineResult.metrics.rippleDb)} dB; target error ${fmt(baselineResult.metrics.rmsErrorDb)} dB RMS.`:'');
  }else{series=[{name:'A · shared horn',color:'#215e59',rows:r.rows.map(v=>({x:v.f,y:v.aDb}))},{name:'B · conventional coax',color:'#c0693b',rows:r.rows.map(v=>({x:v.f,y:v.bDb}))}];q('plot').innerHTML=plotSVG(series);q('polar-plot').innerHTML=r.polar.length>1?plotSVG([{name:'A normalized',rows:r.polar.map(v=>({x:v.angle,y:v.aNormalizedDb}))},{name:'B normalized',rows:r.polar.map(v=>({x:v.angle,y:v.bNormalizedDb}))}],false,true):'';q('metrics').textContent=`Mean A−B ${fmt(r.metrics.meanDeltaDb)} dB at equal declared voltage · RMS difference ${fmt(r.metrics.rmsDifferenceDb)} dB. −6 dB beamwidth at ${fmt(r.polarHz,0)} Hz: A ${r.metrics.aBeamwidth?fmt(r.metrics.aBeamwidth.widthDeg,1)+'°':'unavailable'}; B ${r.metrics.bBeamwidth?fmt(r.metrics.bBeamwidth.widthDeg,1)+'°':'unavailable'}.`;}
  q('legend').innerHTML=series.map(s=>`<span style="color:${s.color}">— ${esc(s.name)}</span>`).join('');q('qualification').textContent=r.qualification+' '+r.warnings.join(' ');q('export-result').disabled=false;
 }
 function checkCurrent(){const t=traces.mid;if(t?.provenance?.linkedGeometry){const latest=api.getDesign?.()||analysis;if(t.provenance.geometrySignature!==signature(latest))t.provenance.stale=true;const fresh=api.getBroadband?.();if(!fresh?.available||JSON.stringify(fresh.options)!==JSON.stringify(t.provenance.options))t.provenance.stale=true;}if(t?.provenance?.stale){syncCards();throw Error('The captured mid belongs to earlier geometry or acoustic settings. Capture the current mid again, or import a deliberately frozen trace.');}}
 function calculate(){invalidate();try{checkCurrent();result=C.sum(traces.mid,traces.high,opts());let note='';if(baselineMid){try{baselineResult=C.sum(baselineMid,traces.high,opts());}catch(e){note=' Baseline cannot be summed: '+e.message;}}q('status').textContent=result.gate.basis+' study · '+result.rows.length+' samples. '+note;draw();return result;}catch(e){q('status').textContent=e.message;return null;}}
 function compare(){invalidate();try{abResult=C.compare(traces.a,traces.b,{lowHz:number(q('ab-low')),highHz:number(q('ab-high')),polarHz:number(q('polar-hz'))});if(!abResult.gate.allowed)throw Error(abResult.gate.reasons.join(' '));q('status').textContent=abResult.gate.basis+' A/B comparison. Only common frequency and angle samples are used.';draw();return abResult;}catch(e){abResult=null;q('status').textContent=e.message;return null;}}
 function applyValues(values){for(const [k,v]of Object.entries(values||{})){const el=host.querySelector('[data-cs-option="'+k+'"]');if(!el)continue;if(el.type==='checkbox')el.checked=v===true;else el.value=String(v);}}
 function snapshot(){return {version:1,traces:clone(traces),baselineMid:clone(baselineMid),options:opts(),bounds:bounds(),mode:mode(),comparison:{lowHz:number(q('ab-low')),highHz:number(q('ab-high')),polarHz:number(q('polar-hz'))}};}
 function restore(saved){invalidate();traces={mid:null,high:null,a:null,b:null};baselineMid=null;applyValues(C.defaults);q('mode').value='crossover';for(const [k,v]of Object.entries({fcLowHz:525,fcHighHz:875,gainLowDb:-3,gainHighDb:3,delayLowMs:0,delayHighMs:.3,steps:9}))q(`bound="${k}"`).value=v;q('search-polarity').checked=true;q('ab-low').value=200;q('ab-high').value=2000;q('polar-hz').value=1000;
  let error='';if(saved){try{if(saved.version!==1)throw Error('Unsupported crossover study version.');for(const key of Object.keys(traces))if(saved.traces?.[key])traces[key]=C.normalize(saved.traces[key]);if(saved.baselineMid)baselineMid=C.normalize(saved.baselineMid);applyValues(saved.options);for(const [k,v]of Object.entries(saved.bounds||{})){const el=host.querySelector('[data-cs-bound="'+k+'"]');if(el&&Number.isFinite(v))el.value=v;}q('search-polarity').checked=saved.bounds?.tryPolarity!==false;q('mode').value=saved.mode==='compare'?'compare':'crossover';for(const [key,id]of [['lowHz','ab-low'],['highHz','ab-high'],['polarHz','polar-hz']])if(Number.isFinite(saved.comparison?.[key]))q(id).value=saved.comparison[key];}catch(e){error=e.message;traces={mid:null,high:null,a:null,b:null};baselineMid=null;}}
  syncCards();q('xo').hidden=mode()!=='crossover';q('ab').hidden=mode()!=='compare';if(analysis)update(analysis);q('status').textContent=error||'Study restored. Calculate to refresh its results.';return !error;
 }
 function update(a){analysis=a;const t=traces.mid;if(t?.provenance?.linkedGeometry&&t.provenance.geometrySignature!==signature(a)){t.provenance.stale=true;invalidate('Geometry changed. Capture the current mid model again; the frozen baseline is retained.');syncCards();}const fs=api.getFrontStudy?.(),lc=fs?.cases?.[0]?.diagnostics?.lcHz;q('front').textContent=Number.isFinite(lc)?`Current chamber study bare LC reference: ${fmt(lc,0)} Hz. This reference is not the loaded dip or crossover optimum.`:'';}
 all('[data-cs-file]').forEach(el=>el.addEventListener('change',async()=>{const key=el.dataset.csFile,file=el.files?.[0];if(!file)return;const current=++revision;try{if(file.size>5e6)throw Error('Trace exceeds the 5 MB limit.');const t=C.parse(await file.text());if(disposed||current!==revision)return;if(t.name==='Unnamed trace')t.name=file.name;traces[key]=t;invalidate('Trace loaded. Complete its references, then calculate.');syncCards();emit();}catch(e){if(current!==revision)return;traces[key]=null;invalidate('Import failed: '+e.message);syncCards();emit();}el.value='';}));
 all('[data-cs-ref],[data-cs-source],[data-cs-preserved]').forEach(el=>el.addEventListener('change',()=>{const key=(el.dataset.csRef||el.dataset.csSource||el.dataset.csPreserved).split(':')[0],t=traces[key];if(!t)return;if(el.dataset.csRef){const field=el.dataset.csRef.split(':')[1];t.reference[field]=el.type==='number'?number(el):el.value.trim();}else if(el.dataset.csSource)t.basis=el.value;else t.reference.phasePreserved=el.checked;invalidate();syncCards();emit();}));
 all('[data-cs-option],[data-cs-bound],[data-cs-search-polarity],[data-cs-ab-low],[data-cs-ab-high],[data-cs-polar-hz]').forEach(el=>el.addEventListener('input',()=>{invalidate();emit();}));
 q('mode').addEventListener('change',()=>{q('xo').hidden=mode()!=='crossover';q('ab').hidden=mode()!=='compare';invalidate();emit();});q('plot-mode').addEventListener('change',draw);q('calculate').addEventListener('click',calculate);q('compare').addEventListener('click',compare);
 q('example').addEventListener('click',()=>{const e=C.example();traces.mid=e.mid;traces.high=e.high;baselineMid=null;applyValues(C.defaults);invalidate();syncCards();calculate();emit();});
 q('capture').addEventListener('click',()=>{try{const a=api.getDesign?.()||analysis,r=api.getBroadband?.();traces.mid=C.fromBroadband(r);traces.mid.provenance={...traces.mid.provenance,linkedGeometry:true,geometrySignature:signature(a),stale:false};analysis=a;invalidate('Simulated mid captured. Supply a compatible HF trace; its phase and level cannot be inferred from the driver name.');syncCards();emit();}catch(e){invalidate(e.message);}});
 q('freeze').addEventListener('click',()=>{if(!traces.mid||traces.mid.provenance?.stale)return;baselineMid=clone(traces.mid);baselineMid.provenance={...baselineMid.provenance,linkedGeometry:false,frozenBaseline:true};invalidate();syncCards();emit();});q('clear-baseline').addEventListener('click',()=>{baselineMid=null;invalidate();syncCards();emit();});
 q('search').addEventListener('click',()=>{invalidate();let r;try{checkCurrent();r=C.optimize(traces.mid,traces.high,opts(),bounds());search=r;q('search-status').textContent=`${r.evaluated} candidates tested. Baseline score ${fmt(r.baseline.metrics.score,3)}; best ${fmt(r.best.metrics.score,3)}. Crossover ${fmt(r.best.options.fcHz,1)} Hz · HF ${fmt(r.best.options.gainHighDb,2)} dB / ${fmt(r.best.options.delayHighMs,3)} ms / ${r.best.options.polarityHigh===1?'normal':'inverted'} polarity. ${r.qualification}`;q('use-search').disabled=false;result=r.best;q('status').textContent='Previewing best tested settings. Use tested settings to keep them.';draw();}catch(e){q('status').textContent=e.message;}});
 q('use-search').addEventListener('click',()=>{if(!search)return;applyValues(search.best.options);calculate();emit();});
 q('template').addEventListener('click',()=>download('MEH_response_template.json',JSON.stringify(C.template(),null,2),'application/json'));q('protocol').addEventListener('click',()=>download('MEH_vs_coax_measurement_protocol.txt',C.measurementProtocol(),'text/plain'));q('export-result').addEventListener('click',()=>{const r=activeResult();if(r)download(mode()==='compare'?'MEH_coax_comparison.csv':'MEH_crossover_sum.csv',C.resultCSV(r),'text/csv');});q('export-study').addEventListener('click',()=>download('MEH_crossover_study.json',JSON.stringify(snapshot(),null,2),'application/json'));
 all('[data-cs-trace-export]').forEach(el=>el.addEventListener('click',()=>{const t=traces[el.dataset.csTraceExport];if(t)download('MEH_'+el.dataset.csTraceExport+'_trace.csv',C.traceCSV(t),'text/csv');}));
 q('import-study').addEventListener('click',()=>q('study-file').click());q('study-file').addEventListener('change',async()=>{const file=q('study-file').files?.[0];if(!file)return;const id=++revision;try{if(file.size>12e6)throw Error('Study exceeds the 12 MB limit.');const saved=JSON.parse(await file.text());if(disposed||id!==revision)return;restore(saved);emit();}catch(e){if(id===revision)q('status').textContent='Study import failed: '+e.message;}q('study-file').value='';});
 syncCards();return {get snapshot(){return snapshot();},get result(){return activeResult();},get search(){return search;},restore,update,calculate,compare,dispose(){disposed=true;revision++;}};
}
return {init,plotSVG};
};
