/* Complex response studies. All pressure traces retain their declared references.
 * No measurement, phase reference, HF response or acoustic validation is inferred. */
module.exports=function createCrossoverStudy(){
'use strict';
const PI=Math.PI,rad=PI/180,clone=x=>JSON.parse(JSON.stringify(x)),finite=Number.isFinite;
const mul=(a,b)=>({re:a.re*b.re-a.im*b.im,im:a.re*b.im+a.im*b.re}),div=(a,b)=>{const d=b.re*b.re+b.im*b.im;return {re:(a.re*b.re+a.im*b.im)/d,im:(a.im*b.re-a.re*b.im)/d};},mag=z=>Math.hypot(z.re,z.im),db=z=>20*Math.log10(Math.max(1e-15,mag(z))),polar=(a,p)=>({re:a*Math.cos(p),im:a*Math.sin(p)}),wrap=d=>((d+180)%360+360)%360-180;
const referenceKeys=['level','voltageRms','voltageBasis','distanceM','distanceOrigin','environment','window','calibration','plane'];
const defaults={filter:'LR4',fcHz:700,gainMidDb:0,gainHighDb:0,delayMidMs:0,delayHighMs:0,polarityMid:1,polarityHigh:1,lowHz:300,highHz:1400,targetDb:90,phaseWeight:.02,allowMixedBasis:false};
function rows(input){
 if(!Array.isArray(input)||input.length<2||input.length>20000)throw Error('Provide 2–20000 frequency rows.');
 const out=input.map((r,i)=>{const f=r.f??r.frequency_hz,level=r.db??r.magnitude_db,phase=r.phase??r.phase_deg,angle=r.angle??r.angle_deg??0;if(![f,level,phase,angle].every(finite)||f<.001||f>1e6||Math.abs(level)>400||Math.abs(phase)>1e9||Math.abs(angle)>180)throw Error('Invalid frequency, magnitude, phase or angle at row '+(i+1)+'.');return {f,db:level,phase,angle};}).sort((a,b)=>a.angle-b.angle||a.f-b.f);
 if(out.some((r,i)=>i&&r.angle===out[i-1].angle&&r.f===out[i-1].f))throw Error('Duplicate angle/frequency rows are ambiguous.');
 return out;
}
function normalize(input){
 if(!input||typeof input!=='object')throw Error('Trace must be an object.');
 const basis=['measured','simulated','synthetic'].includes(input.basis)?input.basis:'unspecified';
 if(input.provenance?.generatedSynthetic&&basis!=='synthetic')throw Error('Generated example data must remain labelled synthetic.');
 if(input.provenance?.model&&input.provenance?.inputState&&basis!=='simulated')throw Error('Captured model data must remain labelled simulated.');
 return {version:1,name:String(input.name||'Unnamed trace').slice(0,150),basis,reference:clone(input.reference||{}),rows:rows(input.rows),provenance:clone(input.provenance||{})};
}
function parse(text,meta={}){
 if(String(text).length>5e6)throw Error('Trace exceeds the 5 MB limit.');
 const trimmed=String(text).trim();if(trimmed.startsWith('{'))return normalize({...JSON.parse(trimmed),...meta});
 let embedded={};const lines=trimmed.replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>{if(l.trim().startsWith('# meh_trace=')){embedded=JSON.parse(l.trim().slice(12));return false;}return l.trim()&&!l.trim().startsWith('#');});
 if(lines.length<3)throw Error('CSV needs a header and at least two rows.');
 const parts=l=>l.split(',').map(s=>s.trim().replace(/^"|"$/g,'')),header=parts(lines.shift()).map(s=>s.toLowerCase()),keys=['frequency_hz','magnitude_db','phase_deg'],ids=keys.map(k=>header.indexOf(k)),ai=header.indexOf('angle_deg');if(ids.some(i=>i<0))throw Error('CSV columns: frequency_hz,magnitude_db,phase_deg,angle_deg (angle optional).');
 const data=lines.map((l,i)=>{const a=parts(l),values=ids.map(j=>a[j]===undefined||a[j]===''?NaN:Number(a[j])),angle=ai<0?0:a[ai]===undefined||a[ai]===''?NaN:Number(a[ai]);return {f:values[0],db:values[1],phase:values[2],angle};});
 return normalize({...embedded,...meta,rows:data});
}
function traceCSV(trace){const t=normalize(trace),{rows:data,...meta}=t;return '# meh_trace='+JSON.stringify(meta)+'\nfrequency_hz,magnitude_db,phase_deg,angle_deg\n'+data.map(r=>[r.f,r.db,r.phase,r.angle].join(',')).join('\n');}
function referenceGate(a,b,kind='sum',allowMixedBasis=false){
 const reasons=[];for(const t of [a,b]){if(!t||!t.rows){reasons.push('Import both traces.');continue;}if(t.basis==='unspecified')reasons.push(t.name+': declare measured, simulated or synthetic source.');}
 if(!a?.rows||!b?.rows)return {allowed:false,reasons:[...new Set(reasons)]};
 if(a.basis!==b.basis&&!(kind==='sum'&&allowMixedBasis&&[a.basis,b.basis].every(x=>['measured','simulated'].includes(x))))reasons.push('Different source bases: measured and simulated traces require an explicit mixed-model study; A/B conclusions require matching bases.');
 const keys=kind==='sum'?[...referenceKeys,'time','phasor','angleDeg']:referenceKeys;
 for(const key of keys){const x=a.reference[key],y=b.reference[key],present=v=>typeof v==='number'?finite(v):typeof v==='string'&&v.trim().length>0;if(!present(x)||!present(y))reasons.push('Both traces need '+key+'.');else if(typeof x==='number'&&typeof y==='number'?Math.abs(x-y)>1e-6*Math.max(1,Math.abs(x),Math.abs(y)):x!==y)reasons.push('Different '+key+' references.');}
 for(const t of [a,b]){if(!(t.reference.voltageRms>0&&t.reference.distanceM>0))reasons.push('Positive drive voltage and distance are required.');if(kind==='sum'&&t.reference.phasor!=='exp(+j omega t)')reasons.push('Use exp(+j omega t) phase convention.');if(kind==='sum'&&t.reference.phasePreserved!==true)reasons.push(t.name+': confirm original phase and shared timing were preserved.');}
 return {allowed:!reasons.length,reasons:[...new Set(reasons)],basis:a.basis===b.basis?a.basis:'mixed measured / simulated',qualification:a.basis==='measured'&&b.basis==='measured'?'Calculation from user-declared measured traces; hardware and calibration not independently verified.':'Model study, not measured system performance.'};
}
function slice(trace,angle=0){const out=trace.rows.filter(r=>r.angle===angle).map(r=>({...r}));if(out.length<2)throw Error('At least two samples are required at '+angle+' degrees.');let previous=out[0].phase;for(let i=1;i<out.length;i++){out[i].phase=previous+wrap(out[i].phase-previous);previous=out[i].phase;}return out;}
function interpolate(data,f){
 if(f<data[0].f*(1-1e-10)||f>data.at(-1).f*(1+1e-10))throw Error('No extrapolation outside trace range.');
 let lo=0,hi=data.length-1;while(hi-lo>1){const m=(lo+hi)>>1;if(data[m].f>f)hi=m;else lo=m;}
 if(Math.abs(f-data[lo].f)<1e-9)return polar(10**(data[lo].db/20),data[lo].phase*rad);if(Math.abs(f-data[hi].f)<1e-9)return polar(10**(data[hi].db/20),data[hi].phase*rad);
 const a=data[lo],b=data[hi];if(b.f/a.f>2.000001)throw Error('Frequency gap exceeds one octave. Supply denser response samples.');const t=Math.log(f/a.f)/Math.log(b.f/a.f);return polar(10**((a.db+(b.db-a.db)*t)/20),(a.phase+(b.phase-a.phase)*t)*rad);
}
function filter(f,fc,kind='lp',family='LR4'){
 if(!['none','BW1','LR2','LR4'].includes(family)||!['lp','hp'].includes(kind)||!(f>=.001&&f<=1e6&&fc>=.001&&fc<=1e6))throw Error('Choose a supported filter and positive frequencies.');
 if(family==='none')return {re:1,im:0};const x=f/fc;
 if(family==='BW1'||family==='LR2'){const z=div(kind==='lp'?{re:1,im:0}:{re:0,im:x},{re:1,im:x});return family==='BW1'?z:mul(z,z);}
 const z=div({re:kind==='lp'?1:-x*x,im:0},{re:1-x*x,im:Math.SQRT2*x});return mul(z,z);
}
function options(input={}){const o={...defaults,...input};for(const k of Object.keys(defaults).filter(k=>typeof defaults[k]==='number'))if(!finite(o[k]))throw Error('Enter a finite '+k+'.');if(!(o.lowHz>=.001&&o.highHz>o.lowHz&&o.highHz<=1e6&&o.fcHz>=.001&&o.fcHz<=1e6)||o.phaseWeight<0||o.phaseWeight>1)throw Error('Use positive rising band edges, crossover and a phase weight from 0 to 1.');for(const k of ['gainMidDb','gainHighDb'])if(Math.abs(o[k])>60)throw Error('Gain must be within ±60 dB.');for(const k of ['delayMidMs','delayHighMs'])if(o[k]<0||o[k]>100)throw Error('Delay must be 0–100 ms.');for(const k of ['polarityMid','polarityHigh'])if(![-1,1].includes(o[k]))throw Error('Polarity must be +1 or −1.');filter(1,o.fcHz,'lp',o.filter);return o;}
function grid(low,high,n=101){return Array.from({length:n},(_,i)=>low*(high/low)**(i/(n-1)));}
function prepared(a,b,o){const gate=referenceGate(a,b,'sum',o.allowMixedBasis);if(!gate.allowed)throw Error(gate.reasons.join(' '));const am=slice(a,a.reference.angleDeg),bh=slice(b,b.reference.angleDeg);if(o.lowHz<Math.max(am[0].f,bh[0].f)*(1-1e-9)||o.highHz>Math.min(am.at(-1).f,bh.at(-1).f)*(1+1e-9))throw Error('The complete study band must be covered by both traces.');return {gate,samples:grid(o.lowHz,o.highHz).map(f=>({f,a:interpolate(am,f),b:interpolate(bh,f)}))};}
function evaluate(p,o){
 const scale=(z,f,gain,delay,polarity,kind)=>mul(mul(z,polar(polarity*10**(gain/20),-2*PI*f*delay/1000)),filter(f,o.fcHz,kind,o.filter));
 const out=p.samples.map(({f,a,b})=>{const m=scale(a,f,o.gainMidDb,o.delayMidMs,o.polarityMid,'lp'),h=scale(b,f,o.gainHighDb,o.delayHighMs,o.polarityHigh,'hp'),sum={re:m.re+h.re,im:m.im+h.im},phaseDifferenceDeg=wrap((Math.atan2(m.im,m.re)-Math.atan2(h.im,h.re))/rad),weight=2*Math.min(mag(m),mag(h))/(mag(m)+mag(h)||1);return {f,midDb:db(m),highDb:db(h),sumDb:db(sum),sumPhaseDeg:Math.atan2(sum.im,sum.re)/rad,phaseDifferenceDeg,phaseWeight:weight,cancellationDb:20*Math.log10(Math.max(1e-15,mag(sum)/(mag(m)+mag(h)||1))),re:sum.re,im:sum.im};});
 const levels=out.map(r=>r.sumDb),weight=out.reduce((s,r)=>s+r.phaseWeight,0),phaseRmsDeg=Math.sqrt(out.reduce((s,r)=>s+r.phaseWeight*r.phaseDifferenceDeg**2,0)/(weight||1)),rmsErrorDb=Math.sqrt(out.reduce((s,r)=>s+(r.sumDb-o.targetDb)**2,0)/out.length);
 return {version:1,kind:'complex-crossover',options:clone(o),gate:p.gate,rows:out,metrics:{rmsErrorDb,phaseRmsDeg,rippleDb:Math.max(...levels)-Math.min(...levels),minimumDb:Math.min(...levels),maximumDb:Math.max(...levels),worstCancellationDb:Math.min(...out.map(r=>r.cancellationDb)),score:rmsErrorDb+o.phaseWeight*phaseRmsDeg},qualification:p.gate.qualification,warnings:['Linear pressure summation at one angle and the declared test level. No excursion, thermal, distortion, power handling or passive component design is inferred.','Electrical filter shapes multiply imported acoustic traces; their total acoustic slopes need not be textbook slopes.','Phase is unwrapped by the shortest adjacent difference; phase sampling must be dense enough to resolve propagation delay.']};
}
function sum(a,b,input={}){a=normalize(a);b=normalize(b);const o=options(input);return {...evaluate(prepared(a,b,o),o),sources:[a,b].map(t=>({name:t.name,basis:t.basis,reference:t.reference,provenance:t.provenance}))};}
function optimize(a,b,input={},bounds={}){
 a=normalize(a);b=normalize(b);const o=options(input),p=prepared(a,b,o);
 const bnd={fcLowHz:o.fcHz*.75,fcHighHz:o.fcHz*1.25,gainLowDb:o.gainHighDb-3,gainHighDb:o.gainHighDb+3,delayLowMs:Math.max(0,o.delayHighMs-.3),delayHighMs:o.delayHighMs+.3,steps:9,tryPolarity:true,...bounds};
 if(![bnd.fcLowHz,bnd.fcHighHz,bnd.gainLowDb,bnd.gainHighDb,bnd.delayLowMs,bnd.delayHighMs].every(finite)||!Number.isInteger(bnd.steps)||bnd.steps<2||bnd.steps>12||bnd.fcLowHz<o.lowHz||bnd.fcHighHz>o.highHz||bnd.fcHighHz<bnd.fcLowHz||bnd.gainHighDb<bnd.gainLowDb||bnd.delayHighMs<bnd.delayLowMs)throw Error('Search requires ordered finite bounds, crossover inside the study band, and 2–12 steps.');
 const linear=(a,b)=>Array.from({length:bnd.steps},(_,i)=>a+(b-a)*i/(bnd.steps-1)),frequencies=grid(bnd.fcLowHz,bnd.fcHighHz,bnd.steps),gains=linear(bnd.gainLowDb,bnd.gainHighDb),delays=linear(bnd.delayLowMs,bnd.delayHighMs),polarities=bnd.tryPolarity?[-1,1]:[o.polarityHigh];
 options({...o,gainHighDb:bnd.gainLowDb,delayHighMs:bnd.delayLowMs});options({...o,gainHighDb:bnd.gainHighDb,delayHighMs:bnd.delayHighMs});
 const baseline=evaluate(p,o);let best=baseline,count=0;for(const fcHz of frequencies)for(const gainHighDb of gains)for(const delayHighMs of delays)for(const polarityHigh of polarities){const candidate=evaluate(p,{...o,fcHz,gainHighDb,delayHighMs,polarityHigh});count++;if(candidate.metrics.score<best.metrics.score)best=candidate;}
 const sources=[a,b].map(t=>({name:t.name,basis:t.basis,reference:t.reference,provenance:t.provenance}));baseline.sources=clone(sources);best.sources=clone(sources);
 return {kind:'bounded-crossover-search',baseline,best,evaluated:count,bounds:bnd,improvement:baseline.metrics.score-best.metrics.score,scoreMeaning:'RMS deviation from the chosen dB target + phase weight × component phase RMS weighted by their overlap, on an equal-log frequency grid.',qualification:'Best among the tested settings and baseline. Not a globally optimal crossover or a validated loudspeaker.'};
}
function fromBroadband(result){
 if(!result?.available||!result.rows?.length||result.rows.some(r=>!r.available||!finite(r.splDb)||!finite(r.phaseDeg)))throw Error('A complete broadband on-axis mid result is required; missing samples cannot be bridged.');
 return normalize({name:'Current MEH mid · reduced model',basis:'simulated',rows:result.rows.map(r=>({f:r.frequencyHz,db:r.splDb,phase:r.phaseDeg,angle:0})),reference:{level:'dB SPL re 20 uPa RMS',voltageRms:result.options.voltageRms,voltageBasis:'per-driver terminal RMS',distanceM:result.options.distanceM,distanceOrigin:'retained mouth plane',environment:'uniform circular aperture in infinite baffle',window:'steady-state model',calibration:'analytic pressure re 20 uPa RMS',plane:'horizontal',angleDeg:0,time:'terminal voltage t=0; includes propagation from retained mouth plane',phasor:'exp(+j omega t)',phasePreserved:true},provenance:{model:result.model,qualification:result.qualification,inputState:result.inputState,options:result.options}});
}
function angles(trace){return [...new Set(trace.rows.map(r=>r.angle))].sort((a,b)=>a-b);}
function beamwidth(pattern){
 const a=pattern.slice().sort((a,b)=>a.angle-b.angle),center=a.findIndex(r=>r.angle===0);if(center<0)return null;const cross=direction=>{let prev=a[center];for(let i=center+direction;i>=0&&i<a.length;i+=direction){const cur=a[i];if(Math.abs(cur.angle-prev.angle)>15.00001)return null;if(cur.normalizedDb<=-6)return prev.angle+(-6-prev.normalizedDb)/(cur.normalizedDb-prev.normalizedDb)*(cur.angle-prev.angle);prev=cur;}return null;},left=cross(-1),right=cross(1);return left===null||right===null?null:{leftDeg:left,rightDeg:right,widthDeg:right-left};
}
function compare(a,b,input={}){
 a=normalize(a);b=normalize(b);const gate=referenceGate(a,b,'compare');if(!gate.allowed)return {kind:'response-comparison',gate,rows:[],polar:[]};
 const low=input.lowHz??Math.max(slice(a)[0].f,slice(b)[0].f),high=input.highHz??Math.min(slice(a).at(-1).f,slice(b).at(-1).f);if(!(finite(low)&&finite(high)&&high>low&&low>0))throw Error('Choose a positive rising comparison band.');
 const ax=slice(a),bx=slice(b),data=grid(low,high).map(f=>({f,aDb:db(interpolate(ax,f)),bDb:db(interpolate(bx,f))})).map(r=>({...r,deltaDb:r.aDb-r.bDb}));
 const common=angles(a).filter(v=>angles(b).includes(v));let patterns=[];if(input.polarHz!==undefined){if(!finite(input.polarHz)||input.polarHz<=0)throw Error('Polar frequency must be positive.');const f=input.polarHz,az=db(interpolate(ax,f)),bz=db(interpolate(bx,f));patterns=common.map(angle=>({angle,aDb:db(interpolate(slice(a,angle),f)),bDb:db(interpolate(slice(b,angle),f))})).map(r=>({...r,aNormalizedDb:r.aDb-az,bNormalizedDb:r.bDb-bz}));}
 return {version:1,kind:'response-comparison',gate,sources:[a,b].map(t=>({name:t.name,basis:t.basis,reference:t.reference})),rows:data,polarHz:input.polarHz??null,polar:patterns,metrics:{meanDeltaDb:data.reduce((s,r)=>s+r.deltaDb,0)/data.length,rmsDifferenceDb:Math.sqrt(data.reduce((s,r)=>s+r.deltaDb**2,0)/data.length),aRippleDb:Math.max(...data.map(r=>r.aDb))-Math.min(...data.map(r=>r.aDb)),bRippleDb:Math.max(...data.map(r=>r.bDb))-Math.min(...data.map(r=>r.bDb)),aBeamwidth:beamwidth(patterns.map(r=>({angle:r.angle,normalizedDb:r.aNormalizedDb}))),bBeamwidth:beamwidth(patterns.map(r=>({angle:r.angle,normalizedDb:r.bNormalizedDb})))},qualification:gate.qualification,warnings:['A−B retains input calibration and the same voltage; this is not equal-power or maximum-output comparison.','Only matching angles are compared. Beamwidth requires −6 dB crossings on both sides with gaps no greater than 15 degrees. No full-sphere directivity index is inferred.','No distortion, compression or improvement conclusion follows from frequency-response differences alone.']};
}
function resultCSV(result){
 if(!result?.rows?.length)throw Error('Calculate a result first.');const names=result.kind==='complex-crossover'?['f','midDb','highDb','sumDb','sumPhaseDeg','phaseDifferenceDeg','cancellationDb']:['f','aDb','bDb','deltaDb'];const {rows:data,polar,...meta}=result;return '# meh_study='+JSON.stringify(meta)+'\n'+names.join(',')+'\n'+data.map(r=>names.map(k=>r[k]).join(',')).join('\n')+(polar?.length?'\n# polar\nangle_deg,a_db,b_db,a_normalized_db,b_normalized_db\n'+polar.map(r=>[r.angle,r.aDb,r.bDb,r.aNormalizedDb,r.bNormalizedDb].join(',')).join('\n'):'');
}
function example(){
 const reference={level:'synthetic relative dB',voltageRms:1,voltageBasis:'per-driver terminal RMS',distanceM:1,distanceOrigin:'fictional common origin',environment:'synthetic example',window:'synthetic continuous response',calibration:'synthetic only',plane:'horizontal',angleDeg:0,time:'synthetic shared zero',phasor:'exp(+j omega t)',phasePreserved:true};
 const make=(name,kind)=>normalize({name,basis:'synthetic',reference,provenance:{generatedSynthetic:true},rows:grid(100,5000,301).map(f=>{let z=polar(10**(90/20),-2*PI*f*.002);if(kind==='mid'){const x=f/900,notch=div({re:1-x*x,im:.12*x},{re:1-x*x,im:.7*x});z=mul(z,notch);}else z=mul(z,polar(10**(2/20),-2*PI*f*.0002));return {f,db:db(z),phase:Math.atan2(z.im,z.re)/rad};})});return {mid:make('Synthetic mid with a 900 Hz notch','mid'),high:make('Synthetic HF with +2 dB / +0.2 ms offset','high')};
}
function measurementProtocol(){return `MEH versus conventional coax: repeatable A/B measurement protocol\n\nPurpose: compare the SAME driver in a conventional baffle and the proposed manifold/horn; identify response, coverage and headroom tradeoffs. No measurement is supplied by this tool.\n\n1. Record driver serial, configuration, cabinet/ports, filters, geometry revision, temperature, microphone/interface/calibration, amplifier and gain. Keep rear loading identical if isolating front manifold effects; otherwise document this confound.\n2. Use the same location, acoustic datum, microphone distance and angular rotation origin for both configurations. Record distance from that datum, not from different cabinet faces. Use the same frequency window/gate, environment and smoothing. Check the window supports the lowest reported frequency. Repeat on-axis sweeps to estimate repeatability.\n3. Measure each branch separately without moving the microphone. Keep the common electrical or acoustic timing reference; do not independently remove driver delay, set separate impulse peaks to zero, replace phase with minimum phase, or normalize levels. Record the RMS voltage at each driver terminal. For DSP-equipped finished-system comparisons declare the test point and per-branch gains instead of claiming equal cone voltage.\n4. For a coax, measure its cone and HF separately with protective filters documented; leave protective filters in the trace. Repeating them in the study would double-filter the response.\n5. Measure complete systems at equal terminal voltage; label this equal-voltage, not equal-power or equal-loudness. Use calibrated SPL only when the microphone sensitivity/reference and signal path are calibrated. Record impedance separately if assessing equal power.\n6. Measure horizontal and vertical angles in separate files, preferably −90 to +90 degrees in steps no larger than 10 degrees. Keep the same angle convention and identify the plane. Capture on-axis in every dataset. Do not infer full-sphere sound power from one horizontal sweep.\n7. Repeat at increasing drive for distortion, noise and compression using appropriate hearing/driver protection. Stop at chosen limits; report those limits and repeats. This tool does not establish maximum output or safe drive.\n8. Export frequency_hz,magnitude_db,phase_deg,angle_deg rows. Provide full source/reference metadata. Compare only common valid bandwidth and angles; a missing result is unknown, never zero. Phase samples must be dense enough to resolve propagation delay.\n\nFor crossover work, verify summed response physically and repeat off-axis. A smooth model curve cannot prove a resonance is safely hidden by the crossover.\n`;
}
function template(){const {mid}=example();return {...mid,name:'Replace with your measured trace',basis:'unspecified',reference:{level:'',voltageRms:null,voltageBasis:'',distanceM:null,distanceOrigin:'',environment:'',window:'',calibration:'',plane:'horizontal',angleDeg:0,time:'',phasor:'exp(+j omega t)',phasePreserved:false},rows:[{f:100,db:0,phase:0,angle:0},{f:200,db:0,phase:0,angle:0}],provenance:{instruction:'Template placeholders only. Replace all rows and references with real data. Not speaker measurements.'}};}
return {defaults,normalize,parse,traceCSV,referenceGate,slice,interpolate,filter,sum,optimize,fromBroadband,compare,beamwidth,resultCSV,example,measurementProtocol,template};
};
