/* Browser presentation for the coupled system. No DOM access until init(). */
module.exports=function createSystemPanel(root){
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const modes={flow:['Mouth flow','L/s RMS',r=>r.mouthFlowRmsLS],power:['Mouth load power','W',r=>r.mouthPowerW],impedance:['Impedance / mid','Ω',r=>r.branches[0].impedanceOhm],excursion:['Cone travel / mid','mm peak',r=>r.branches[0].excursionPeakMM],velocity:['Entry speed / mid','m/s peak',r=>r.branches[0].entryVelocityPeakMS],pressure:['Entry pressure','Pa RMS',r=>r.branches[0].entryPressureRmsPa],phase:['Entry flow phase','degrees',r=>r.branches[0].entryPhaseDeg]};
function plotSVG(result,mode='flow'){
 if(!result?.available)return '';
 const [label,unit,value]=modes[mode]||modes.flow,rows=result.rows,good=rows.filter(r=>r.available),series=[{rows,color:'#315a55',label:'Current design'},...(result.baseline?.available?[{rows:result.baseline.rows,color:'#ad6037',label:'Open collector'}]:[])],values=series.flatMap(s=>s.rows.filter(r=>r.available).map(value)).filter(Number.isFinite);
 if(!values.length)return '';
 const minF=rows[0].frequencyHz,maxF=rows.at(-1).frequencyHz,W=680,H=260,L=62,R=660,T=28,B=218,lo=mode==='phase'?-180:0,hi=mode==='phase'?180:Math.max(1e-8,...values)*1.08;
 const x=f=>L+(f-minF)/Math.max(1,maxF-minF)*(R-L),y=v=>B-(v-lo)/(hi-lo)*(B-T);
 let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img"><title>${esc(label)} versus frequency, ${minF} to ${maxF} Hz</title><desc>Experimental model. Exact samples are listed below and in the CSV. Missing results break the curve. Lines connect samples; peaks between samples are unresolved.</desc>`;
 const ref=good[0].horn.transverseReferenceHz;if(ref<maxF)svg+=`<rect x="${x(Math.max(minF,ref))}" y="${T}" width="${R-x(Math.max(minF,ref))}" height="${B-T}" fill="#eee3d0"/><text x="${R-5}" y="18" text-anchor="end">Above first horn transverse-mode reference</text>`;
 for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;svg+=`<path d="M${L} ${y(v)}H${R}" stroke="#d9dfd9"/><text x="${L-7}" y="${y(v)+4}" text-anchor="end">${fmt(v,Math.abs(hi)<.1?4:Math.abs(hi)<5?2:0)}</text>`;const f=minF+(maxF-minF)*i/4;svg+=`<text x="${x(f)}" y="${B+21}" text-anchor="middle">${fmt(f,0)}</text>`;}
 for(const s of series){let path='',previous=null;for(const row of s.rows){const v=row.available?value(row):NaN;if(!Number.isFinite(v)){previous=null;continue;}const jump=mode==='phase'&&previous!==null&&Math.abs(v-previous)>180;path+=(previous===null||jump?'M':'L')+x(row.frequencyHz).toFixed(2)+' '+y(v).toFixed(2);previous=v;}
 svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2"${s.label==='Open collector'?' stroke-dasharray="6 3"':''}/>`;
 for(const row of s.rows.filter(r=>r.available)){const v=value(row);if(Number.isFinite(v))svg+=`<circle cx="${x(row.frequencyHz)}" cy="${y(v)}" r="2.3" fill="${s.color}"><title>${esc(s.label)} · ${row.frequencyHz} Hz: ${fmt(v,4)} ${esc(unit)}</title></circle>`;}}
 return svg+`<text x="5" y="17">${esc(unit)}</text><text x="${R}" y="254" text-anchor="end">Hz</text></svg>`;
}
function init(host){
 if(!host)return null;
 let analysis=null,result=null,timer=0,dataset=root.MEHSpatialResults||null,imported=false;
 host.innerHTML=`<style>#systemAcoustics .sa-body{padding:4px 16px 16px;font-size:12px;color:#526360}#systemAcoustics p{line-height:1.5;margin:10px 0}#systemAcoustics .sa-controls{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}#systemAcoustics label{display:flex;flex-direction:column;gap:5px}#systemAcoustics input[type=number]{width:100px;padding:6px}#systemAcoustics select{padding:6px;max-width:100%}#systemAcoustics svg{display:block;width:100%;border:1px solid #d9dfd9;border-radius:5px}#systemAcoustics svg text{font:11px system-ui;fill:#526360}#systemAcoustics table{border-collapse:collapse;width:100%;font-size:11px}#systemAcoustics td,#systemAcoustics th{padding:8px;text-align:right;border-bottom:1px solid #d9dfd9;white-space:nowrap}#systemAcoustics td:first-child,#systemAcoustics th:first-child{text-align:left}#systemAcoustics .sa-scroll{overflow:auto;margin:12px 0}#systemAcoustics .sa-actions{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}#systemAcoustics details{margin-top:14px}#systemAcoustics [hidden]{display:none!important}</style>
 <summary>System acoustics <span class="tag">Experimental</span></summary><div class="sa-body">
 <p data-sa-status role="status">Open this panel to calculate.</p>
 <div class="sa-controls"><label>Drive / mid (V RMS)<input data-sa-drive type="number" value="1" min=".05" max="100" step=".1"></label><label>Mouth boundary<select data-sa-mouth><option value="baffled">Baffled aperture</option><option value="matched">Matched</option></select></label><label>Throat boundary<select data-sa-throat><option value="closed">Closed</option><option value="matched">Matched</option></select></label><label>Show<select data-sa-mode>${Object.entries(modes).map(([key,m])=>`<option value="${key}">${m[0]}</option>`).join('')}</select></label></div>
 <div data-sa-plot></div><p data-sa-legend hidden><span style="color:#315a55">— Current design</span> &nbsp; <span style="color:#ad6037">– – Open collector</span></p><p data-sa-note></p><p data-sa-limits role="status" style="color:#8e5529" hidden></p>
 <div class="sa-scroll"><table><thead><tr><th data-sa-probe>Nearest probe sample</th><th>Position</th><th>Impedance</th><th>Travel</th><th>Entry speed</th><th>Pressure</th><th>Phase</th></tr></thead><tbody data-sa-branches></tbody></table></div>
 <div class="sa-actions"><button type="button" class="small" data-sa-export disabled>Export results</button><button type="button" class="small" data-sa-import>Load spatial result</button><input type="file" accept=".json,application/json" data-sa-file hidden></div><p data-sa-import-status role="status"></p>
 <details><summary>What is included</summary><p data-sa-scope></p><p>Each mid is solved separately with the horn pressure and shared rear load. All mids in this editor use the same axial entry position and voltage, so their results coincide. Rotating drivers around the horn does not resolve circumferential interactions in this model.</p><p>High-frequency driver handoff, off-axis coverage, local junction scattering and exterior radiation remain unsolved. Use calibrated, time-aligned measurements in the crossover workbench to assess the real handoff.</p></details>
 <details data-sa-field hidden><summary>700 Hz pressure map</summary><div data-sa-field-plot></div><p>One front passage under the current coupled load. Assumed cone and lossless air; pointwise field convergence has not been checked.</p></details>
 <details><summary>Assumptions &amp; numerical checks</summary><p data-sa-checks></p><p>Small-signal model. The insert uses a surrogate cone, rigid walls and lossless air; gap friction and nonlinear flow are omitted. Catalog moving mass includes free-air loading, so the spatial coupling still needs an audited moving-mass convention. Treat absolute levels as exploratory.</p><p>Shading marks the horn’s first transverse-mode reference: the 1D horn model cannot resolve those modes. A coarse frequency sweep can miss resonant peaks. Mesh convergence checks numerical consistency, not agreement with a physical loudspeaker.</p><p data-sa-provenance></p></details>
 <details><summary>Frequency samples</summary><div class="sa-scroll" data-sa-samples></div></details></div>`;
 const q=s=>host.querySelector(s);
 q('[data-sa-mode]').value='flow';
 function options(){return {hornLoad:'webster',voltageRms:q('[data-sa-drive]').value.trim()===''?NaN:Number(q('[data-sa-drive]').value),mouthTermination:q('[data-sa-mouth]').value,throatTermination:q('[data-sa-throat]').value};}
 function clear(message){result=null;q('[data-sa-status]').textContent=message;for(const key of ['plot','note','branches','scope','checks','provenance','samples'])q('[data-sa-'+key+']').innerHTML='';q('[data-sa-export]').disabled=true;q('[data-sa-legend]').hidden=true;q('[data-sa-field]').hidden=true;q('[data-sa-field-plot]').innerHTML='';q('[data-sa-limits]').hidden=true;}
 function drawField(){if(!result||!q('[data-sa-field]').open||q('[data-sa-field]').hidden)return;const field=root.MEHPressureField.combine(analysis,result,dataset,root.MEHPressureBasis);q('[data-sa-field-plot]').innerHTML=field.available?root.MEHPressureField.svg(field):'<p>'+esc(field.reason)+'</p>';}
 function render(){
  const good=result.rows.filter(r=>r.available),failed=result.rows.length-good.length,probe=good.reduce((best,r)=>Math.abs(r.frequencyHz-analysis.p.frequency)<Math.abs(best.frequencyHz-analysis.p.frequency)?r:best,good[0]),[label,unit,value]=modes[q('[data-sa-mode]').value]||modes.flow;
  q('[data-sa-status]').textContent=(result.spatial?'3D front passage':'Lumped front passage')+' · coupled mids · 1D horn · '+fmt(result.voltageRms,2)+' V RMS per mid · '+good.length+' sampled frequencies'+(failed?' · '+failed+' unavailable samples':'');
  q('[data-sa-plot]').innerHTML=plotSVG(result,q('[data-sa-mode]').value);q('[data-sa-legend]').hidden=!result.baseline?.available;
  q('[data-sa-note]').textContent=label+' · '+unit+'. '+(['flow','power'].includes(q('[data-sa-mode]').value)?'Total from all mids; not sound pressure level.':q('[data-sa-mode]').value==='velocity'?'Peak harmonic flow / tube area; not a local velocity maximum.':'Equal-drive mids coincide; shown per driver.');
  q('[data-sa-limits]').textContent=(result.warnings||[]).join(' ');q('[data-sa-limits]').hidden=!result.warnings?.length;
  q('[data-sa-probe]').textContent=probe.frequencyHz+' Hz (nearest probe)';
  q('[data-sa-branches]').innerHTML=probe.branches.map(b=>`<tr><td>${esc(b.id)}</td><td>${fmt(b.zMM,1)} mm</td><td>${fmt(b.impedanceOhm)} Ω</td><td>${fmt(b.excursionPeakMM,3)} mm</td><td>${fmt(b.entryVelocityPeakMS)} m/s</td><td>${fmt(b.entryPressureRmsPa)} Pa</td><td>${fmt(b.entryPhaseDeg,1)}°</td></tr>`).join('');
  q('[data-sa-scope]').textContent=result.spatial?'The spatial front calculation covers the cone gap, insert opening, collector and tube up to the curved horn-entry cap. Its matrix replaces the front compliance and neck inertance; no extra neck or end correction is added.':'The open front is represented by cavity compliance and tube inertance. It does not resolve local flow or wave patterns.';
  q('[data-sa-checks]').textContent='Maximum electrical/acoustic power residual: '+Math.max(...good.map(r=>Math.abs(r.relativePowerResidual))).toExponential(2)+'. '+(result.spatial?'Only qualified spatial frequencies are used. Geometry edits invalidate the passage result.':'This is a reduced-model sweep, not a spatial calculation.');
  q('[data-sa-provenance]').textContent=result.source?'Spatial mesh SHA-256: '+result.source.meshSha256:'';
  q('[data-sa-samples]').innerHTML='<table><thead><tr><th>Hz</th><th>'+esc(label)+' ('+esc(unit)+')</th>'+(result.baseline?.available?'<th>Open collector</th>':'')+'</tr></thead><tbody>'+result.rows.map(r=>{const b=result.baseline?.rows.find(b=>b.frequencyHz===r.frequencyHz);return `<tr><td>${r.frequencyHz}</td><td>${r.available?fmt(value(r),4):esc(r.reason)}</td>${result.baseline?.available?'<td>'+(b?.available?fmt(value(b),4):'Unavailable')+'</td>':''}</tr>`;}).join('')+'</tbody></table>';
  q('[data-sa-export]').disabled=false;q('[data-sa-field]').hidden=!root.MEHPressureBasis||!result.spatial||result.source?.meshSha256!==root.MEHPressureBasis.meshSha256;drawField();
 }
 function calculate(){clearTimeout(timer);timer=0;if(!host.open||!analysis)return;const useOpen=!imported&&analysis.p.frontFiller==='none'&&root.MEHSpatialBaseline&&root.MEHSpatialStudy.validate(root.MEHSpatialBaseline,analysis,options()).available,data=useOpen?root.MEHSpatialBaseline:dataset,r=root.MEHSpatialStudy.analyze(analysis,data,{...options(),...((useOpen||imported)?{useSpatialFront:true}:{})});if(!r.available){clear(r.reason);return;}
  if(r.spatial&&analysis.p.frontFiller!=='none'&&root.MEHSpatialBaseline){const open=root.MEH.analyze({...analysis.p,frontFiller:'none'}),baseline=root.MEHSpatialStudy.analyze(open,root.MEHSpatialBaseline,{...options(),useSpatialFront:true});if(baseline.available)r.baseline=baseline;}
  result=r;render();}
 function schedule(){clearTimeout(timer);clear('Updating system acoustics…');if(host.open)timer=setTimeout(calculate,180);}
 for(const selector of ['[data-sa-drive]','[data-sa-mouth]','[data-sa-throat]'])q(selector).addEventListener('input',schedule);
 q('[data-sa-mode]').addEventListener('change',()=>{if(result)render();});
 q('[data-sa-field]').addEventListener('toggle',drawField);
 host.addEventListener('toggle',()=>{if(host.open)calculate();else clearTimeout(timer);});
 q('[data-sa-import]').addEventListener('click',()=>q('[data-sa-file]').click());
 q('[data-sa-file]').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>10000000)throw Error('Result file exceeds 10 MB.');const next=JSON.parse(await file.text()),check=root.MEHSpatialStudy.validate(next,analysis,options());if(!check.available)throw Error(check.reason);dataset=next;imported=true;q('[data-sa-import-status]').textContent='Spatial result loaded for this passage.';schedule();}catch(error){q('[data-sa-import-status]').textContent='Result not loaded: '+error.message;}e.target.value='';});
 q('[data-sa-export]').addEventListener('click',()=>{if(!result)return;const url=URL.createObjectURL(new Blob([root.MEHSpatialStudy.csv(result)],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download='MEH_system_acoustics.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return {update(a){analysis=a;schedule();},setOptions(o={}){for(const [key,selector]of [['voltageRms','drive'],['mouthTermination','mouth'],['throatTermination','throat']])if(o[key]!==undefined)q('[data-sa-'+selector+']').value=String(o[key]);schedule();},get options(){return options();},get result(){return result;},dispose(){clearTimeout(timer);}};
}
return {init,plotSVG};
};
