/* Offline acoustic sizing panel. Numerical samples and native FEM points are
 * deliberately different series. No DOM activity until init(). */
module.exports=function createWorkbenchPanel(root){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=2)=>Number.isFinite(x)?x.toFixed(d):'—';
const modes={spl:['On-axis pressure','dB SPL',r=>r.splDb],power:['Power-equivalent level','dB SPL',r=>r.powerSplDb],impedance:['Electrical impedance / mid','Ω',r=>r.electricalImpedanceOhm],acoustic:['Entry acoustic impedance','MPa·s/m³',r=>r.acousticImpedanceMagnitudePaSM3/1e6],phase:['On-axis phase','degrees',r=>r.phaseDeg],excursion:['Maximum cone travel','mm peak',r=>r.excursionPeakMM],velocity:['Maximum entry speed','m/s peak',r=>r.portVelocityPeakMS]};
const colors=['#215e59','#c0693b','#6478aa','#92649b','#a18b32','#589092'];
function plotSVG(series,mode='spl'){
 const [label,unit,value]=modes[mode]||modes.spl,good=series.filter(s=>s.rows?.some(r=>r.available));
 const rows=good.flatMap(s=>s.rows.filter(r=>r.available&&Number.isFinite(value(r))));if(!rows.length)return '';
 const loF=Math.min(...rows.map(r=>r.frequencyHz)),hiF=Math.max(...rows.map(r=>r.frequencyHz));
 const values=rows.map(value),phase=mode==='phase',db=['spl','power'].includes(mode);let low=phase?-180:db?Math.floor(Math.min(...values)/10)*10:0,high=phase?180:db?Math.ceil(Math.max(...values)/10)*10:Math.max(...values)*1.1;
 if(!(high>low))high=low+1;
 const L=62,R=700,T=30,B=258,W=720,H=303,x=f=>L+Math.log(f/loF)/Math.log(hiF/loF||2)*(R-L),y=v=>B-(v-low)/(high-low)*(B-T);
 let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img"><title>${esc(label)}</title><desc>Lines are sampled reduced-model predictions. Separate dots are qualified local FEM passage samples coupled to the same one-dimensional horn. Neither is a measured loudspeaker response.</desc><rect width="${W}" height="${H}" fill="#fcfdfb"/>`;
 for(let i=0;i<=4;i++){const v=low+(high-low)*i/4;svg+=`<path d="M${L} ${y(v)}H${R}" stroke="#dce2dd"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${fmt(v,Math.abs(high)<5?2:0)}</text>`;}
 const ticks=[50,80,100,150,200,300,500,700,1000,1500,2000,3000].filter(f=>f>=loF&&f<=hiF);
 for(const f of ticks)svg+=`<path d="M${x(f)} ${T}V${B}" stroke="#edf0ed"/><text x="${x(f)}" y="${B+21}" text-anchor="middle">${f}</text>`;
 const ref=rows.find(r=>r.horn?.transverseReferenceHz)?.horn.transverseReferenceHz;
 if(ref&&ref>loF&&ref<hiF)svg+=`<path d="M${x(ref)} ${T}V${B}" stroke="#9d937f" stroke-dasharray="3 4"/><text x="${x(ref)+4}" y="22">Transverse-mode reference</text>`;
 good.forEach((s,i)=>{const color=s.color||colors[i%colors.length];let path='',previous=null;
  for(const r of s.rows){const v=r.available?value(r):NaN;if(!Number.isFinite(v)){previous=null;continue;}if(!s.pointsOnly){path+=(previous===null||(phase&&Math.abs(v-previous)>180)?'M':'L')+x(r.frequencyHz).toFixed(2)+' '+y(v).toFixed(2);previous=v;}else svg+=`<circle cx="${x(r.frequencyHz)}" cy="${y(v)}" r="3.5" fill="#fcfdfb" stroke="${color}" stroke-width="1.8"><title>${esc(s.label)} · ${r.frequencyHz} Hz · ${fmt(v,3)} ${esc(unit)}</title></circle>`;}
  if(path)svg+=`<path d="${path}" fill="none" stroke="${color}" stroke-width="2"/>`;
 });
 return svg+`<text x="7" y="18">${esc(unit)}</text><text x="${R}" y="297" text-anchor="end">Frequency · Hz</text></svg>`;
}
function init(host,callbacks={}){
 if(!host)return null;
 let analysis=null,result=null,sweep=null,reference=null,timer=0,revision=0,brief=null,selected=null;
 host.innerHTML=`<style>#acousticWorkbench .aw-body{padding:5px 16px 18px;color:#526360;font-size:12px}#acousticWorkbench p{line-height:1.5}#acousticWorkbench .aw-controls{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}#acousticWorkbench label{display:flex;flex-direction:column;gap:5px}#acousticWorkbench input,#acousticWorkbench select{padding:6px;max-width:100%;border:1px solid #cbd5ce;border-radius:4px;background:#fff;color:#284c47}#acousticWorkbench input[type=number]{width:88px}#acousticWorkbench svg{width:100%;display:block;border:1px solid #d9dfd9;border-radius:5px}#acousticWorkbench svg text{font:11px system-ui;fill:#526360}#acousticWorkbench details{margin-top:15px}#acousticWorkbench .aw-scroll{overflow:auto}#acousticWorkbench table{width:100%;border-collapse:collapse;font-size:11px}#acousticWorkbench th,#acousticWorkbench td{text-align:right;padding:8px;border-bottom:1px solid #d9dfd9;white-space:nowrap}#acousticWorkbench th:first-child,#acousticWorkbench td:first-child{text-align:left}#acousticWorkbench [hidden]{display:none!important}#acousticWorkbench .aw-note{color:#885b32}#acousticWorkbench .aw-legend{display:flex;flex-wrap:wrap;gap:14px}</style>
 <summary>Acoustic sizing <span class="tag">Research prototype</span></summary><div class="aw-body">
 <p data-aw-status role="status">Open to calculate the current design.</p>
 <div class="aw-controls"><label>Drive / mid · V RMS<input data-aw-drive type="number" value="1" min=".05" max="100" step=".1"></label><label>Distance · m<input data-aw-distance type="number" value="3" min=".2" max="100" step=".1"></label><label>Show<select data-aw-mode>${Object.entries(modes).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></label><button class="small" type="button" data-aw-export disabled>Export curves</button></div>
 <div data-aw-plot></div><p class="aw-legend" data-aw-legend></p><p data-aw-summary></p>
 <p class="aw-note">Broadband lines use an equivalent passage model. Dots use qualified 3D front-passage samples. Both use a 1D horn; four-side interference and HF crossover are unresolved. Current MEH–Hornresp agreement is pending.</p>
 <details><summary>Size entries and chambers</summary><div class="aw-controls"><label>Change<select data-aw-parameter><option value="portAreaMM2">Entry area · mm² / mid</option><option value="neckMM">Tube length setting · mm</option><option value="frontVolumeCM3">Front cavity · cm³ / mid</option><option value="entryZMM">Entry axial position · mm</option></select></label><label>Candidate values<input data-aw-values value="1200, 1450, 1650, 1900, 2200" size="34"></label><button class="small" type="button" data-aw-sweep>Compare</button></div><p data-aw-sweep-status role="status">Candidates recalculate the physical geometry. Cavity volume excludes the entry tube. Select a row to preview its curves. The physical tube includes an additional 3 mm land.</p><div class="aw-scroll"><table><thead><tr><th>Candidate</th><th>Area mm²</th><th>Front cm³</th><th>Band ripple dB</th><th>In-band travel mm</th><th>In-band speed m/s</th><th>Result</th></tr></thead><tbody data-aw-candidates></tbody></table></div><button type="button" class="small" data-aw-apply disabled>Use selected geometry</button><p>Ranking screens flatness in the selected band and travel/speed limits across the entire simulated range. It is conditional on this reduced model, not a global optimum.</p></details>
 <details><summary>Targets and model assumptions</summary><div class="aw-controls"><label>Band low · Hz<input data-aw-low type="number" value="200" min="80" max="1400" step="10"></label><label>Band high · Hz<input data-aw-high type="number" value="700" min="100" max="1500" step="10"></label><label>Travel limit · mm peak<input data-aw-travel type="number" value="1.75" min=".01" max="20" step=".05"></label><label>Speed limit · m/s peak<input data-aw-speed type="number" value="17" min=".1" max="100" step="1"></label><label>End correction · × radius<input data-aw-end type="number" value="0" min="0" max="3" step=".1"></label><label>Passage loss scale<input data-aw-loss type="number" value="1" min="0" max="10" step=".25"></label><label>Assumed Mms air subtraction · g<input data-aw-mass type="number" value="0" min="0" max="3" step=".1"></label></div>
 <p data-aw-target-note></p><p>Speed limit is a user screening target, not a turbulence threshold. Insert travel is also limited by the entered clearance minus a 1 mm allowance. No absolute SPL target is inferred from a saved zero.</p><p>RMS voltage, pressure and volume flow; excursion and entry speed are peak. On-axis SPL assumes a uniform circular mouth in an infinite baffle and uses the same mouth flow that loads the interior network. Distance is measured from the retained horn plane at maximum axial depth; the returning mouth lip is omitted. Power-equivalent SPL uses the solved mouth power over a hemisphere. Phase includes propagation delay. Mouth diffraction, directivity, rear-vent/front summation and cone breakup are outside scope.</p><p>Catalog Mms is retained by default. A nonzero subtraction is an explicit sensitivity assumption; suspension compliance and mechanical resistance retain their catalog-derived values. The new passage model starts with zero extra junction length. The saved legacy correction (1.4 radii) belongs to the older lumped model; it can be entered here as a sensitivity assumption. Loss and end-correction estimates are not fitted to the FEM points. Qualified FEM passage matrices already contain their entire front air domain and receive no additional passage/end correction.</p><p>Source phase offsets · degrees, in driver order<input data-aw-phases value="0, 0, 0, 0" size="28"></p><p data-aw-checks></p></details></div>`;
 const q=s=>host.querySelector('[data-aw-'+s+']');
 function number(key){const v=q(key).value.trim();return v===''?NaN:Number(v);}
 function options(){return {voltageRms:number('drive'),distanceM:number('distance'),minHz:80,maxHz:1500,points:121,endCorrection:number('end'),lossScale:number('loss'),movingMassCorrectionG:number('mass'),sourcePhasesDeg:q('phases').value.split(',').map(x=>x.trim()===''?NaN:Number(x.trim())),targets:{lowHz:number('low'),highHz:number('high'),maxExcursionMM:number('travel'),maxPortVelocityMS:number('speed')}};}
 function invalidate(){clearTimeout(timer);revision++;result=null;sweep=null;reference=null;selected=null;q('apply').disabled=true;q('plot').innerHTML='';q('legend').innerHTML='';q('summary').textContent='';q('candidates').innerHTML='';q('checks').textContent='';q('export').disabled=true;}
 function summary(r){const rows=r.rows.filter(x=>x.available&&x.frequencyHz>=number('low')&&x.frequencyHz<=number('high'));if(!rows.length)return 'No samples in the target band.';const levels=rows.map(x=>x.splDb);return `${fmt(number('low'),0)}–${fmt(number('high'),0)} Hz: ${fmt(Math.min(...levels),1)} to ${fmt(Math.max(...levels),1)} dB at ${fmt(r.options?.distanceM??number('distance'),1)} m · maximum travel ${fmt(Math.max(...rows.map(x=>x.excursionPeakMM)),3)} mm · entry speed ${fmt(Math.max(...rows.map(x=>x.portVelocityPeakMS)),2)} m/s peak.`;}
 function draw(candidate=selected){if(!result)return;const series=[{label:'Current · reduced model',rows:result.rows}];if(candidate?.result?.available)series.push({label:candidate.label||'Candidate',rows:candidate.result.rows});if(reference?.available)series.push({label:`Current geometry · lossless local FEM · ${reference.rows.filter(r=>r.available).length} points`,rows:reference.rows,pointsOnly:true,color:'#294b70'});q('plot').innerHTML=plotSVG(series,q('mode').value);q('legend').innerHTML=series.map((s,i)=>`<span style="color:${s.color||colors[i]}">${s.pointsOnly?'○':'—'} ${esc(s.label)}</span>`).join('');q('summary').textContent=summary(candidate?.result||result);}
 function calculate(){clearTimeout(timer);if(!analysis||!host.open)return;const opts=options();if(![opts.voltageRms,opts.distanceM,opts.endCorrection,opts.lossScale,opts.movingMassCorrectionG,...Object.values(opts.targets),...opts.sourcePhasesDeg].every(Number.isFinite)||opts.targets.lowHz>=opts.targets.highHz){q('status').textContent='Enter valid numbers and a rising target band.';return;}
  result=root.MEHBroadband.baseline({state:analysis.p,wizardBrief:brief},opts);if(!result.available){q('status').textContent=result.reason;result=null;return;}
  reference=root.MEHBroadband.sparseReference({state:analysis.p},analysis.p.frontFiller==='none'?root.MEHSpatialBaseline:root.MEHSpatialResults,opts);
  q('status').textContent=`${analysis.p.count} coupled mids · ${result.rows.filter(r=>r.available).length} reduced-model samples · ${fmt(opts.voltageRms,2)} V RMS / mid`;
  q('checks').textContent=`Radiation plane: ${fmt(result.geometry.mouthZMM,1)} mm axial; ${fmt(result.geometry.mouthRadiusM*2000,1)} mm effective diameter. Maximum relative power residual: ${Math.max(...result.rows.filter(r=>r.available).map(r=>Math.abs(r.powerResidual??r.relativePowerResidual??0))).toExponential(2)}. Geometry changes invalidate the FEM overlay. A muted source remains a passive coupled motor. ${reference?.available?'Matching local FEM data are shown only at solved frequencies.':reference?.reason||'No matching qualified FEM data.'}`;
  q('export').disabled=false;draw();
 }
 function schedule(){invalidate();q('status').textContent=host.open?'Updating acoustic sizing…':'Open to calculate the current design.';if(host.open)timer=setTimeout(calculate,180);}
 for(const key of ['drive','distance','low','high','travel','speed','end','loss','mass','phases'])q(key).addEventListener('input',schedule);
 q('mode').addEventListener('change',()=>draw());host.addEventListener('toggle',()=>{if(host.open)calculate();else clearTimeout(timer);});
 q('parameter').addEventListener('change',()=>{const g=result?.geometry;const defaults={portAreaMM2:'1200, 1450, 1650, 1900, 2200',neckMM:'3, 5, 8, 12, 16',frontVolumeCM3:g?[.9,.95,1,1.05,1.1].map(x=>fmt((g.frontCavityCM3||analysis.frontCavityV)*x,1)).join(', '):'180, 200, 220, 240',entryZMM:'120, 135, 147, 160, 175'};q('values').value=defaults[q('parameter').value];});
 q('sweep').addEventListener('click',()=>{if(!result)calculate();if(!result)return;const tokens=q('values').value.split(',').map(x=>x.trim()),values=tokens.map(Number);if(tokens.some(x=>!x)||!values.length||values.length>12||values.some(x=>!Number.isFinite(x)||x<=0)){q('sweep-status').textContent='Enter 1–12 positive candidate values, separated by commas.';return;}
  selected=null;q('apply').disabled=true;const currentRevision=revision;q('sweep-status').textContent='Calculating candidates…';q('sweep').disabled=true;setTimeout(()=>{try{if(revision!==currentRevision)return;sweep=root.MEHBroadband.sweep({state:analysis.p,wizardBrief:brief},{parameter:q('parameter').value,values},options());if(!sweep.available)throw Error(sweep.reason);q('candidates').innerHTML=sweep.candidates.map((c,i)=>{const rows=c.result?.rows?.filter(r=>r.available&&r.frequencyHz>=number('low')&&r.frequencyHz<=number('high'))||[],levels=rows.map(r=>r.splDb);return `<tr><td><button type="button" class="small" data-aw-preview="${i}" ${c.available?'':'disabled'}>${esc(c.label||c.value)}</button></td><td>${fmt(c.geometry?.nominalPortAreaMM2,0)}</td><td>${fmt(c.geometry?.frontCavityCM3,1)}</td><td>${levels.length?fmt(Math.max(...levels)-Math.min(...levels),2):'—'}</td><td>${rows.length?fmt(Math.max(...rows.map(r=>r.excursionPeakMM)),3):'—'}</td><td>${rows.length?fmt(Math.max(...rows.map(r=>r.portVelocityPeakMS)),2):'—'}</td><td>${esc(c.feasible?'Within limits':c.reason||'Limit exceeded')}</td></tr>`;}).join('');q('sweep-status').textContent=`${sweep.candidates.filter(c=>c.feasible).length} of ${sweep.candidates.length} candidates meet the geometry and selected acoustic limits. No geometry has been applied.`;}catch(e){q('sweep-status').textContent=e.message;}finally{q('sweep').disabled=false;}},10);
 });
 host.addEventListener('click',e=>{const b=e.target.closest?.('[data-aw-preview]');if(b&&sweep){const c=sweep.candidates[Number(b.dataset.awPreview)];if(c?.available){selected=c;q('apply').disabled=!c.feasible;draw(c);}}});
 q('apply').addEventListener('click',()=>{if(!selected?.feasible||!result)return;const accepted=callbacks.onApply?.(selected.state,selected.label,result.inputState);if(accepted===false)q('sweep-status').textContent='The design changed; calculate the comparison again.';});
 q('export').addEventListener('click',()=>{if(!result)return;const payload={format:'MEH-acoustic-workbench-v1',baseline:result,reference:reference?.available?reference:null,sweep};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='MEH_acoustic_sizing.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 return {update(a){const first=!analysis,changedCount=analysis?.p.count!==a.p.count;analysis=a;if(changedCount)q('phases').value=Array(a.p.count).fill('0').join(', ');if(first){q('distance').value=String(a.p.listeningDistance||3);q('low').value=String(a.p.lowTarget||200);q('travel').value=String(a.p.frontFiller==='none'?3:Math.max(.01,a.p.fillerClearance-1));q('phases').value=Array(a.p.count).fill('0').join(', ');}schedule();},setOptions(o={}){for(const [k,control]of Object.entries({voltageRms:'drive',distanceM:'distance',endCorrection:'end',lossScale:'loss',movingMassCorrectionG:'mass'}))if(o[k]!==undefined)q(control).value=String(o[k]);for(const [k,control]of Object.entries({lowHz:'low',highHz:'high',maxExcursionMM:'travel',maxPortVelocityMS:'speed'}))if(o.targets?.[k]!==undefined)q(control).value=String(o.targets[k]);if(o.sourcePhasesDeg)q('phases').value=o.sourcePhasesDeg.join(', ');schedule();},setBrief(b){brief=b||null;q('target-note').textContent=b?.lowHz?`Saved brief: ${b.lowHz}–${b.handoffHz||700} Hz. Current low target: ${analysis?.p.lowTarget||200} Hz. Choose the intended band above.`:'Default sizing band uses the current low target through 700 Hz; the upper edge is editable.';},get options(){return options();},get result(){return result;},dispose(){clearTimeout(timer);}};
}
return {init,plotSVG,modes};
};
