/* Browser-native printable material geometry. Canonical acoustic passages are inputs, never modified. */
(function(root){'use strict';
const SCHEMA='MEH-fabrication-v1',EPS=1e-5,TAU=2*Math.PI;
const cp=x=>JSON.parse(JSON.stringify(x)),add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>Math.hypot(...a),unit=a=>mul(a,1/norm(a));
const defaults={buildXMM:220,buildYMM:220,buildZMM:250,bedMarginMM:5,fitClearanceMM:.3,minimumWallMM:3,pinDiameterMM:3,pinDepthMM:6,segment:true,alignmentPins:true,includeRear:true,radialSegments:96};
const check=(b,s)=>{if(!b)throw Error(s);};
let runtimePromise;
async function runtime(deps={}){if(deps.manifold)return deps.manifold;if(!runtimePromise)runtimePromise=(async()=>{let binary=root.MEHFabricationWasm,Module=root.MEHManifoldModule;if(!binary&&root.MEHFabricationWasmBase64){const s=root.atob(root.MEHFabricationWasmBase64);binary=Uint8Array.from(s,c=>c.charCodeAt(0));}if(typeof require==='function'){Module=Module||require('./vendor/manifold.cjs');binary=binary||require('node:fs').readFileSync(require('node:path').join(__dirname,'vendor/manifold.wasm'));}check(Module&&binary,'The offline fabrication geometry engine is unavailable.');const w=await Module({wasmBinary:binary});w.setup();return w;})().catch(e=>{runtimePromise=null;throw e;});return runtimePromise;}
function options(input={}){const o={...defaults,...input};for(const k of ['buildXMM','buildYMM','buildZMM'])check(Number.isFinite(o[k])&&o[k]>=40&&o[k]<=2000,k+' must be 40–2000 mm.');for(const k of ['bedMarginMM','fitClearanceMM','minimumWallMM','pinDiameterMM','pinDepthMM'])check(Number.isFinite(o[k])&&o[k]>=0&&o[k]<=100,k+' must be a finite construction dimension.');check(o.minimumWallMM>=2,'Minimum construction wall must be at least 2 mm.');check(o.fitClearanceMM>=.05&&o.fitClearanceMM<=2,'Fit clearance must be 0.05–2 mm, diametral.');check(o.pinDiameterMM>=2&&o.pinDepthMM>=3,'Alignment pins require diameter ≥2 mm and engagement ≥3 mm.');check([48,64,96,128,192].includes(o.radialSegments),'Choose 48, 64, 96, 128 or 192 radial facets.');check(['segment','alignmentPins','includeRear'].every(k=>typeof o[k]==='boolean'),'Fabrication switches must be booleans.');check(Math.min(o.buildXMM,o.buildYMM,o.buildZMM)>2*o.bedMarginMM+20,'Bed margin leaves too little build space.');return o;}
function orient(mesh){let volume=0;for(const f of mesh.faces)volume+=dot(mesh.vertices[f[0]],cross(mesh.vertices[f[1]],mesh.vertices[f[2]]))/6;if(volume<0)for(const f of mesh.faces)[f[1],f[2]]=[f[2],f[1]];return mesh;}
function loft(rings){check(rings.length>=2&&rings.every(r=>r.length===rings[0].length),'Solid loft needs matching rings.');const n=rings[0].length,vertices=rings.flat().map(p=>Array.from(p)),faces=[];for(let k=0;k<rings.length-1;k++)for(let j=0;j<n;j++){const q=(j+1)%n,a=k*n+j,b=k*n+q,c=(k+1)*n+q,d=(k+1)*n+j;faces.push([a,b,c],[a,c,d]);}for(const [k,reverse]of [[0,true],[rings.length-1,false]]){const center=rings[k].reduce((a,p)=>add(a,mul(p,1/n)),[0,0,0]),id=vertices.length;vertices.push(center);for(let j=0;j<n;j++){let f=[id,k*n+j,k*n+(j+1)%n];if(reverse)f.reverse();faces.push(f);}}return orient({vertices,faces,closed:true});}

function shellLoft(outer,inner){check(outer.length===inner.length&&outer[0].length===inner[0].length,'Shell rings require matching samples.');const n=outer[0].length,k=outer.length,vertices=[...outer.flat(),...inner.flat()].map(p=>Array.from(p)),faces=[],quad=(a,b,c,d)=>faces.push([a,b,c],[a,c,d]);for(let i=0;i<k-1;i++)for(let j=0;j<n;j++){const q=(j+1)%n;quad(i*n+j,i*n+q,(i+1)*n+q,(i+1)*n+j);quad(k*n+i*n+j,k*n+(i+1)*n+j,k*n+(i+1)*n+q,k*n+i*n+q);}for(let j=0;j<n;j++){const q=(j+1)%n;quad(j,k*n+j,k*n+q,q);quad((k-1)*n+j,(k-1)*n+q,(2*k-1)*n+q,(2*k-1)*n+j);}return orient({vertices,faces,closed:true});}
function manifoldMesh(mesh,w){return new w.Manifold(new w.Mesh({numProp:3,vertProperties:new Float32Array(mesh.vertices.flat()),triVerts:new Uint32Array(mesh.faces.flat())}));}
function meshOf(s,name){const m=s.getMesh(),vertices=[],faces=[],remap=[],roots=Array.from({length:m.vertProperties.length/m.numProp},(_,i)=>i),find=i=>{while(roots[i]!==i){roots[i]=roots[roots[i]];i=roots[i];}return i;};for(let i=0;i<m.mergeFromVert.length;i++)roots[find(m.mergeFromVert[i])]=find(m.mergeToVert[i]);for(let i=0;i<m.triVerts.length;i+=3)for(let j=0;j<3;j++){const a=m.triVerts[i+j],b=m.triVerts[i+(j+1)%3],pa=Array.from(m.vertProperties.slice(a*m.numProp,a*m.numProp+3)),pb=Array.from(m.vertProperties.slice(b*m.numProp,b*m.numProp+3));if(norm(sub(pa,pb))<.0000001)roots[find(a)]=find(b);}const map=new Map();for(let i=0;i<roots.length;i++){const key=find(i);if(!map.has(key)){map.set(key,vertices.length);vertices.push(Array.from(m.vertProperties.slice(key*m.numProp,key*m.numProp+3)));}remap.push(map.get(key));}for(let i=0;i<m.triVerts.length;i+=3){const f=Array.from(m.triVerts.slice(i,i+3),j=>remap[j]);if(new Set(f).size===3)faces.push(f);}const groups=new Map();for(const f of faces){const k=f.slice().sort((a,b)=>a-b).join(',');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f);}const clean=[];for(const fs of groups.values()){if(fs.length===1)clean.push(fs[0]);else if(fs.length===2){const [a,b]=fs,j=b.indexOf(a[0]);check(b[(j+1)%3]===a[2],'Coincident export faces have inconsistent orientation.');}else throw Error('Unresolvable coincident export faces.');}const used=new Map(),compact=[];for(const f of clean)for(let i=0;i<3;i++){const old=f[i];if(!used.has(old)){used.set(old,compact.length);compact.push(vertices[old]);}f[i]=used.get(old);}return {name,vertices:compact,faces:clean,closed:true,units:'mm'};}
function basicChecks(s,label){check(s.status()==='NoError',label+': solid Boolean failed ('+s.status()+').');check(!s.isEmpty()&&s.volume()>EPS,label+': solid is empty.');const b=s.boundingBox();return {closed:true,engineStatus:s.status(),volumeMM3:s.volume(),triangleCount:s.numTri(),boundsMM:cp(b),sizeMM:b.max.map((x,i)=>x-b.min[i])};}
function transform(origin,x,y,z){return [...x,0,...y,0,...z,0,...origin,1];}
function selectedMounts(a,design,deps){const P=deps.mounting||root.MEHMountParts||(typeof require==='function'?require('./mounting.cjs'):null),M=deps.model||root.MEH;check(P,'Mounting engine unavailable.');const inspection=P.inspect(a,{model:M,land:deps.land||root.MEHMounting,settings:design.mountingParts||{}}),settings={};for(const k of ['mid','compression'])settings[k]={...inspection[k].defaults,...(design.mountingParts?.[k]||{}),enabled:true};const r=P.build(a,settings,{model:M,land:deps.land||root.MEHMounting});check(!r.errors.length,'Resolve driver mounting first: '+r.errors.join(' '));return r;}
async function build(a,design,deps={}){
 const M=deps.model||root.MEH,F=deps.formats||root.MEHFileFormats||(typeof require==='function'?require('./formats.cjs'):null),o=options(design.fabrication||{});check(M&&F&&a?.p,'An analyzed applied design is required.');check(!a.errors.length,'Resolve geometry errors: '+a.errors.join(' '));check(!a.directCouplingIssues?.length,'Resolve direct-coupling geometry before fabrication.');check(!a.frontFiller?.enabled||a.frontFiller.available&&a.frontFiller.valid,'The front insert is unavailable or invalid.');check(a.p.wall>=o.minimumWallMM,'The horn wall is thinner than the chosen minimum construction wall.');const mountResult=selectedMounts(a,design,deps),g=M.frontAdapterGeometry(a);check(!g.rootIntersectionFailures&&!a.hole.fail,'A branch cannot reach the horn.');
 if(a.p.rearLayout==='shared')check(a.sharedRear.valid&&a.sharedRear.smoothJoin,'Fabrication supports the smooth shared enclosure only.');else check(!M.mechanicalFitReasons(a).length,'Resolve individual enclosure fit: '+M.mechanicalFitReasons(a).join(' '));
 const w=await runtime(deps),S=w.Manifold,allocated=[],hold=s=>{allocated.push(s);return s;},keepCheck=(s,label)=>{hold(s);basicChecks(s,label);return s;},cylinder=(h,r,origin=[0,0,0],axis=[0,0,1],n=64)=>{const z=unit(axis),x=unit(Math.abs(z[2])<.9?cross([0,0,1],z):cross([0,1,0],z)),y=cross(z,x);return hold(hold(S.cylinder(h,r,r,n)).transform(transform(origin,x,y,z)));},solid=mesh=>keepCheck(manifoldMesh(mesh,w),'Canonical solid'),union=(x,y)=>hold(x.add(y)),cut=(x,y)=>hold(x.subtract(y)),intersect=(x,y)=>hold(x.intersect(y));
 const diagnostics=[],warnings=[],seams=[],mountManifest=mountResult.parts.map(p=>({id:p.id,driverId:p.driverId,spec:cp(p.spec),source:cp(p.source),transform:cp(p.transform)}));
 try{
  deps.onProgress?.('Cutting horn entries and joining collector walls…');
  let body=solid(F.hornBlank(a,o.radialSegments,{tolerance:.04}));const hornUncutVolume=body.volume(),airSolids=[],branchSolids=[];
  const midSpec=mountResult.parts.find(p=>p.kind==='mid').spec,frameR=Math.max(a.p.frame/2,...midSpec.outline.map(p=>Math.hypot(...p))),collarInner=frameR+o.fitClearanceMM/2,collarOuter=Math.max(collarInner+Math.max(a.p.wall,o.minimumWallMM),midSpec.outerDiameterMM/2+o.minimumWallMM),seat=midSpec.mountOffsetMM,plateThick=midSpec.thicknessMM;
  // Independent flange bolts remain open all the way through the rear support plate.
  function plate(spec,outer,origin,x,y,z){let p=cylinder(spec.thicknessMM,outer,origin,z,o.radialSegments);const c0=add(origin,mul(z,-1));p=cut(p,cylinder(spec.thicknessMM+2,spec.cutoutDiameterMM/2/Math.cos(Math.PI/128),c0,z,128));for(const c of spec.boltCenters){const q=add(origin,add(mul(x,c[0]),mul(y,c[1])));p=cut(p,cylinder(spec.thicknessMM+2,spec.boltHoleDiameterMM/2/Math.cos(Math.PI/48),add(q,mul(z,-1)),z,48));if(spec.hasCounterbores)p=cut(p,cylinder(spec.counterboreDepthMM+1,spec.counterboreDiameterMM/2/Math.cos(Math.PI/48),add(q,mul(z,spec.thicknessMM-spec.counterboreDepthMM)),z,48));}return p;}
  const podShells=[],separate=[],attachmentR=collarOuter+4,attachmentEar=6,attachmentHole=2.25;
  for(let i=0;i<a.poses.length;i++){
   const pose=a.poses[i],n=Array.from(pose.n),t=Array.from(pose.t),v=Array.from(pose.v),front=Array.from(pose.F),rotate=rings=>rings.map(r=>r.map(p=>Array.from(M.rotate(p,pose.a))));
   // Extend the cutter into the horn cavity. A diagnostic cap must never become material.
   const localInner=g.inner.map(r=>r.map(p=>Array.from(p))),depth=Math.max(3,a.p.wall*2),root=localInner[0].map(p=>sub(p,mul(a.n,depth))),airRings=[root,...localInner,localInner.at(-1).map(p=>add(p,mul(a.n,.02)))],air=solid(loft(rotate(airRings)));airSolids.push(air);
   const out=g.outer.map(r=>r.map(p=>Array.from(p)));for(let k=Math.max(1,out.length-2);k<out.length;k++){const center=k===out.length-1?a.F:sub(a.F,mul(a.n,6));out[k]=out[k].map(p=>{const d=sub(p,center),r=Math.hypot(dot(d,a.t),d[1]),scale=Math.max(1,collarOuter/r);return add(center,mul(d,scale));});}
   let b=cut(solid(loft(rotate(out))),air);
   let collar=cut(cylinder(seat+.5,collarOuter,sub(front,mul(n,.5)),n,o.radialSegments),cylinder(seat+2,collarInner,sub(front,mul(n,1)),n,o.radialSegments));
   let support=plate(midSpec,collarOuter,add(front,mul(n,seat)),t,v,n);const attachmentCenters=[];
   for(let j=0;j<4;j++){const q=add(front,add(mul(t,attachmentR*Math.cos(TAU*j/4)),mul(v,attachmentR*Math.sin(TAU*j/4))));attachmentCenters.push(q);collar=union(collar,cylinder(Math.min(6,seat+.5),attachmentEar,add(q,mul(n,Math.max(-.5,seat-6))),n,32));support=union(support,cylinder(plateThick,attachmentEar,add(q,mul(n,seat)),n,32));const drill=cylinder(plateThick+8,attachmentHole,add(q,mul(n,seat-7)),n,32);collar=cut(collar,drill);support=cut(support,drill);}
   b=union(b,collar);basicChecks(b,'Collector '+(i+1));branchSolids.push(b);body=union(body,b);
   separate.push({id:'driver_support_'+(i+1),name:'Removable driver support '+(i+1),solid:support,role:'driver-support',driverIndex:i,fasteners:{quantity:4,size:'M4 through bolts and nuts, independent of driver bolts',holeDiameterMM:4.5,boltCircleDiameterMM:2*attachmentR,sourceDriverBolts:midSpec.boltCount,access:'External collar ears; fit the driver through the full-frame collar opening, then install this rear support over its basket.'}});
   diagnostics.push({id:'mid_'+(i+1),canonicalAirCutterVolumeMM3:air.volume(),mountSeatMM:seat,frameClearanceDiametralMM:o.fitClearanceMM,collarInnerDiameterMM:2*collarInner,supportOuterDiameterMM:2*collarOuter});
   if(o.includeRear&&a.p.rearLayout!=='shared'){
    const rearStart=seat+plateThick+o.fitClearanceMM/2,inner=Math.max(a.podInner,collarInner),outer=Math.max(collarOuter,inner+o.minimumWallMM),end=a.podDepth,cap=Math.max(a.p.wall,o.minimumWallMM);check(end>rearStart+cap+10,'The rear chamber is too shallow for a removable enclosure.');check(attachmentR>outer+attachmentHole,'Rear enclosure wall blocks access to its attachment bolts. Increase the front frame clearance or reduce the pod radius.');
    let pod=cut(cylinder(end-rearStart+cap,outer,add(front,mul(n,rearStart)),n,o.radialSegments),cylinder(end-rearStart+.01,inner,add(front,mul(n,rearStart-.01)),n,o.radialSegments));
    for(const q of attachmentCenters){pod=union(pod,cylinder(cap,attachmentEar,add(q,mul(n,rearStart)),n,32));pod=cut(pod,cylinder(cap+2,attachmentHole,add(q,mul(n,rearStart-1)),n,32));}
    podShells.push({id:'rear_module_'+(i+1),center:add(front,mul(n,end)),axis:n,t,v,radius:outer,inner,driverIndex:i,solid:pod,cap,frontOrigin:add(front,mul(n,rearStart))});
   }
  }
  const beforeCut=body.volume();for(const air of airSolids)body=cut(body,air);const afterCut=body.volume();check(beforeCut-afterCut>EPS,'Entry cutters did not remove material from the horn.');
  // The throat adapter is a continuous open tube between the existing -12 mm mounting datum and the horn.
  const hf=mountResult.parts.find(p=>p.kind==='compression'),hs=hf.spec;check(Math.abs(hs.cutoutDiameterMM-a.p.throat)<.1,'The compression mounting opening differs from the horn throat.');check(hs.thicknessMM<12,'Compression flange must leave room within the 12 mm throat adapter.');
  let hfSupport=plate(hs,Math.max(hs.outerDiameterMM/2,a.p.throat/2+o.minimumWallMM),[0,0,-12],[1,0,0],[0,1,0],[0,0,1]);const outerThroat=Math.max(a.pro[0].outerR,a.p.throat/2+o.minimumWallMM);let tube=cut(cylinder(12,outerThroat,[0,0,-12]),cylinder(14,a.p.throat/2/Math.cos(Math.PI/o.radialSegments),[0,0,-13],[0,0,1],o.radialSegments));body=union(body,union(hfSupport,tube));
  function lid(desc){const cap=Math.max(a.p.wall,o.minimumWallMM),gap=o.fitClearanceMM/2,r=desc.radius,inner=desc.inner,z=desc.axis,C=desc.center;
   // Annular external bolt ears stay outside the rear acoustic cavity; removable lids use M4 through hardware.
   const boltR=r+5,earR=6,boltHole=2.25,earH=cap,base=sub(C,mul(z,cap)),pts=Array.from({length:4},(_,i)=>add(C,add(mul(desc.t,boltR*Math.cos(TAU*i/4)),mul(desc.v,boltR*Math.sin(TAU*i/4)))));
   let cover=cylinder(cap,r+1,add(C,mul(z,gap)),z,o.radialSegments),rim=cut(cylinder(cap,r+1,base,z,o.radialSegments),cylinder(cap+2,inner,sub(base,z),z,o.radialSegments));
   for(const q of pts){rim=union(rim,cylinder(earH,earR,sub(q,mul(z,cap)),z,32));cover=union(cover,cylinder(cap,earR,add(q,mul(z,gap)),z,32));const drill=cylinder(2*cap+gap+2,boltHole,sub(q,mul(z,cap+1)),z,32);rim=cut(rim,drill);cover=cut(cover,drill);}
   // Flat gasket faces and the four external bolt ears locate the service lid.
   if(a.p.rearConcept==='reflex'){
    const p=a.rearPort;check(p.valid&&p.lengthMM>=cap,'Resolve rear vent before fabrication.');let bore,duct;if(p.shape==='slot'){const width=p.innerWidthMM,height=p.innerHeightMM;check(Math.hypot(width,height)/2+p.wallMM<inner-o.minimumWallMM,'Rear slot does not fit the lid.');const frame=transform(add(C,mul(z,gap+cap-p.lengthMM)),desc.t,desc.v,z);bore=hold(hold(S.cube([width,height,p.lengthMM+2])).translate([-width/2,-height/2,-1]));bore=hold(bore.transform(frame));duct=hold(hold(S.cube([width+2*p.wallMM,height+2*p.wallMM,p.lengthMM])).translate([-width/2-p.wallMM,-height/2-p.wallMM,0]));duct=hold(duct.transform(frame));}else{const radius=p.innerWidthMM/2;check(radius+p.wallMM<inner-o.minimumWallMM,'Rear vent does not fit the lid.');const inlet=add(C,mul(z,gap+cap-p.lengthMM));bore=cylinder(p.lengthMM+2,radius,sub(inlet,z),z,64);duct=cylinder(p.lengthMM,radius+p.wallMM,inlet,z,64);}cover=cut(union(cover,duct),bore);}
   body=union(body,rim);separate.push({id:desc.id,name:'Detachable rear lid '+(desc.driverIndex===undefined?'':desc.driverIndex+1),solid:cover,role:'rear-lid',fasteners:{quantity:4,size:'M4 through bolts and nuts',holeDiameterMM:4.5,length:'Select after gasket and washer thickness are known.'}});
  }
  if(o.includeRear&&a.p.rearLayout==='shared'){
   const ext=a.sharedRear.outerProfile,inside=a.sharedRear.innerProfile;check(2*(inside[0].r-o.minimumWallMM)>2*(attachmentR+attachmentEar)+o.fitClearanceMM,'The shared rear service opening is too small for the removable driver supports; use a larger rear opening, smaller driver, individual pods, or exclude rear enclosures.');check(ext?.length>2&&inside?.length>2,'Shared shell profiles are unavailable.');
   const rings=profile=>profile.map(p=>Array.from({length:o.radialSegments},(_,j)=>[p.r*Math.cos(TAU*j/o.radialSegments),p.r*Math.sin(TAU*j/o.radialSegments),p.z]));
   let shell=solid(shellLoft(rings(ext),rings(inside)));body=union(body,shell);
   const q=ext[0],qi=inside[0],z=Math.min(q.z,qi.z);lid({id:'shared_rear_lid',center:[0,0,z],axis:[0,0,-1],t:[1,0,0],v:[0,1,0],radius:q.r,inner:qi.r-o.minimumWallMM});
  }else for(const p of podShells){let pod=p.solid;if(a.p.rearConcept==='reflex'){const r=a.rearPort;check(r.valid&&r.lengthMM>=p.cap,'Resolve rear vent dimensions.');const inlet=add(p.center,mul(p.axis,p.cap-r.lengthMM));let duct,bore;if(r.shape==='slot'){check(Math.hypot(r.innerWidthMM,r.innerHeightMM)/2+r.wallMM<p.inner-o.minimumWallMM,'Rear slot does not fit the enclosure.');const frame=transform(inlet,p.t,p.v,p.axis);duct=hold(hold(hold(S.cube([r.innerWidthMM+2*r.wallMM,r.innerHeightMM+2*r.wallMM,r.lengthMM])).translate([-r.innerWidthMM/2-r.wallMM,-r.innerHeightMM/2-r.wallMM,0])).transform(frame));bore=hold(hold(hold(S.cube([r.innerWidthMM,r.innerHeightMM,r.lengthMM+2])).translate([-r.innerWidthMM/2,-r.innerHeightMM/2,-1])).transform(frame));}else{check(r.innerWidthMM/2+r.wallMM<p.inner-o.minimumWallMM,'Rear vent does not fit the enclosure.');duct=cylinder(r.lengthMM,r.innerWidthMM/2+r.wallMM,inlet,p.axis,64);bore=cylinder(r.lengthMM+2,r.innerWidthMM/2,sub(inlet,p.axis),p.axis,64);}pod=cut(union(pod,duct),bore);}separate.push({id:p.id,name:'Removable rear enclosure '+(p.driverIndex+1),solid:pod,role:'rear-enclosure',fasteners:{quantity:4,size:'M4 through bolts and nuts',holeDiameterMM:4.5,boltCircleDiameterMM:2*attachmentR,access:'External ears. Remove this enclosure and its gasket to reach the separate driver support.'}});}
  const initial=basicChecks(body,'Joined horn assembly'),components=body.decompose();components.forEach(hold);check(components.length===1,'The horn, collars or enclosure have '+components.length+' disconnected material bodies ('+components.map(x=>Math.round(x.volume())+' mm³').join(', ')+'); adjust their joins.');
  // The real passages must remain void after every material union, including enclosure walls and mounting supports.
  for(let i=0;i<airSolids.length;i++){const intrusion=intersect(body,airSolids[i]);check(intrusion.volume()<Math.max(.005,airSolids[i].volume()*1e-6),'Material blocks front passage '+(i+1)+'; change the driver/collector placement.');}
  const wholeParts=[{id:'horn_assembly',name:'Joined horn, collectors and collar attachments',solid:body,role:'horn-assembly'},...separate];
  const frontProfile=M.frontBranch(F.simplifyProfile(a.pro,.04)),hornProbeRings=[{r:a.p.throat/2,z:-13},...frontProfile].map(q=>Array.from({length:o.radialSegments},(_,j)=>[(q.r-.1)*Math.cos(TAU*j/o.radialSegments),(q.r-.1)*Math.sin(TAU*j/o.radialSegments),q.z])),hornProbe=solid(loft(hornProbeRings));
  for(const p of wholeParts){basicChecks(p.solid,p.name);const components=p.solid.decompose();components.forEach(hold);check(components.length===1,p.name+' contains disconnected material.');check(intersect(p.solid,hornProbe).volume()<.1,p.name+' intrudes into the central horn passage; increase driver clearance.');}
  for(let i=0;i<wholeParts.length;i++)for(let j=i+1;j<wholeParts.length;j++){const x=wholeParts[i],y=wholeParts[j],a=x.solid.boundingBox(),b=y.solid.boundingBox();if(a.min.some((v,k)=>v>=b.max[k]-1e-5)||b.min.some((v,k)=>v>=a.max[k]-1e-5))continue;const intersection=intersect(x.solid,y.solid),overlap=intersection.volume();check(overlap<.1,x.name+' interferes with '+y.name+' ('+overlap.toFixed(3)+' mm³, '+JSON.stringify(intersection.boundingBox())+'). Increase the geometry spacing.');}
  for(const part of mountResult.parts){const axis=part.kind==='mid'?Array.from(a.poses[Number(part.id.split('_').at(-1))-1].n):[0,0,1],origin=part.transform.origin,x=part.transform.basisX,y=part.transform.basisY;for(const c of part.spec.boltCenters){const center=add(origin,add(mul(x,c[0]),mul(y,c[1]))),probe=cylinder(part.spec.thicknessMM*.8,part.spec.boltHoleDiameterMM*.4,add(center,mul(axis,part.spec.thicknessMM*.1)),axis,24);for(const p of wholeParts)check(intersect(p.solid,probe).volume()<.1,'Material blocks '+part.id+' source bolt holes.');}}

  const results=[],pins=[],usable=[o.buildXMM,o.buildYMM,o.buildZMM].map(x=>x-2*o.bedMarginMM);
  function newPin(center,axis,id){const length=2*o.pinDepthMM-o.fitClearanceMM;return {id,name:'Alignment dowel '+id,solid:cylinder(length,o.pinDiameterMM/2,sub(center,mul(axis,length/2)),axis,32),role:'alignment-pin',quantity:1};}
  function cutSeam(part,axis,offset,serial){const normal=[0,0,0];normal[axis]=1;let s=part.solid;const pair=s.splitByPlane(normal,offset).map(hold);if(pair.some(p=>p.isEmpty()))return [part];const positions=[];
   if(o.alignmentPins){const matrix=axis===0?[0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1]:axis===1?[0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1]:null;const flat=matrix?hold(s.transform(matrix)):s,section=flat.slice(offset);allocated.push(section);const inset=section.offset(-(o.pinDiameterMM+o.fitClearanceMM)/2-o.minimumWallMM/2);allocated.push(inset);const loops=inset.toPolygons();let tested=0;for(const loop of loops){for(let j=0;j<loop.length;j++){if(tested++>350||positions.length>=4)break;const a=loop[j],b=loop[(j+1)%loop.length],uv=[(a[0]+b[0])/2,(a[1]+b[1])/2],pos=axis===0?[offset,...uv]:axis===1?[uv[1],offset,uv[0]]:[...uv,offset];if(positions.some(p=>norm(sub(pos,p))<Math.max(30,o.pinDiameterMM*8)))continue;const prove=cylinder(2*o.pinDepthMM+1,(o.pinDiameterMM+o.fitClearanceMM)/2+o.minimumWallMM/2,sub(pos,mul(normal,o.pinDepthMM+.5)),normal,32),available=intersect(s,prove);if(Math.abs(available.volume()-prove.volume())>Math.max(.002,prove.volume()*1e-5))continue;positions.push(pos);s=cut(s,cylinder(2*o.pinDepthMM+.2,(o.pinDiameterMM+o.fitClearanceMM)/2,sub(pos,mul(normal,o.pinDepthMM+.1)),normal,32));pins.push(newPin(pos,normal,'pin_'+serial+'_'+positions.length));}if(positions.length>=4||tested>350)break;}}
   const final=s.splitByPlane(normal,offset).map(hold),id='seam_'+serial;seams.push({id,parent:part.id,axis:'XYZ'[axis],offsetMM:offset,alignmentCentersMM:positions,pinDiameterMM:o.pinDiameterMM,holeDiameterMM:o.pinDiameterMM+o.fitClearanceMM,engagementMM:o.pinDepthMM,connection:positions.length?'Bond and seal flat mating faces; printed dowels align the seam.':'Bond and seal flat mating faces; this thin/curved seam has no safe dowel site and needs manual alignment.',structuralRating:false});if(!positions.length)warnings.push(id+': no safe dowel placement; flat seam requires manual alignment while bonding.');return final.map((solid,i)=>({...part,id:part.id+'_'+(i?'minus':'plus')+serial,solid,seams:[...(part.seams||[]),id]}));}
  let serial=0;
  for(const original of wholeParts){deps.onProgress?.('Dividing '+original.name+' into build-volume sections…');let work=[original];if(o.segment){const box=original.solid.boundingBox();for(let axis=0;axis<3;axis++){const n=Math.ceil((box.max[axis]-box.min[axis])/usable[axis]);check(n<=20,'Build volume would require too many subdivisions.');for(let j=1;j<n;j++){const at=box.min[axis]+j*(box.max[axis]-box.min[axis])/n,next=[];for(const p of work)next.push(...cutSeam(p,axis,at,++serial));work=next;check(work.length<=160,'More than 160 sections required; increase the printer volume.');}}}
   for(const p of work){const bodies=p.solid.decompose();bodies.forEach(hold);for(let i=0;i<bodies.length;i++){const id=p.id+(bodies.length>1?'_island'+(i+1):''),raw=bodies[i];const s=hold(hold(raw.asOriginal()).setTolerance(.005)),checks=basicChecks(s,id);check(checks.volumeMM3>1,'A sub-millimetre material sliver appeared at a split; change the printer size or geometry.');const mesh=meshOf(s,id),b=checks.boundsMM,localMesh=meshOf(hold(s.translate(mul(b.min,-1))),id);const validator=deps.mounting||root.MEHMountParts||(typeof require==='function'?require('./mounting.cjs'):null);deps.inspectMesh?.(mesh);if(validator){checks.exportMesh=validator.checkMesh(mesh);checks.localExportMesh=validator.checkMesh(localMesh);for(const c of [checks.exportMesh,checks.localExportMesh])check(Math.abs(c.signedVolumeMM3-checks.volumeMM3)<=Math.max(.01,checks.volumeMM3*1e-5),'Float32 export volume changed beyond the 0.001% tolerance.');}checks.engineTriangleCount=checks.triangleCount;checks.triangleCount=localMesh.faces.length;for(const f of mesh.faces){const [x,y,z]=f.map(i=>mesh.vertices[i]);check(norm(cross(sub(y,x),sub(z,x)))>1e-12,'A degenerate export triangle remains; change the facet resolution.');}check(checks.sizeMM.every((x,i)=>x<=usable[i]+.002)||!o.segment,'A part exceeds the printer volume.');results.push({id,name:p.name,role:p.role,seams:p.seams||[],fasteners:p.fasteners||null,installedMesh:mesh,localMesh,placement:{translationMM:b.min,rotation:'identity'},checks});}}
  }
  for(const p of pins){const checks=basicChecks(p.solid,p.id),mesh=meshOf(p.solid,p.id),length=2*o.pinDepthMM-o.fitClearanceMM,local=meshOf(hold(cylinder(length,o.pinDiameterMM/2,[0,0,0],[0,0,1],32).translate([o.pinDiameterMM/2,o.pinDiameterMM/2,0])),p.id);check([o.pinDiameterMM,o.pinDiameterMM,length].every((x,i)=>x<=usable[i]),'Alignment dowels exceed the print volume; shorten their engagement.');checks.localExportMesh=(deps.mounting||root.MEHMountParts||(typeof require==='function'?require('./mounting.cjs'):null)).checkMesh(local);check(Math.abs(checks.localExportMesh.signedVolumeMM3-checks.volumeMM3)<Math.max(.01,checks.volumeMM3*1e-5),'Dowel export volume differs from installed geometry.');results.push({id:p.id,name:p.name,role:p.role,installedMesh:mesh,localMesh:local,checks,placement:{see:'Assembly OBJ and seam alignment centers',pinLengthMM:length}});}
  const limits=['Faceted material geometry with actual entry cuts and joins; not an acoustic solve or certification.','Print sections fit the chosen axis-aligned build volume; support material, orientation, layer settings and machine tolerances remain printer choices.','Bond and seal segmented horn seams. Alignment dowels are not structural fasteners. Removable lids use separately purchased bolts, nuts, washers and gaskets.','Drivers are retained by the removable rear clamp plates and independent external-ear bolts. The original driver bolt holes are retained, but optional added driver hardware needs its own front-head access/clearance check. Driver mounting dimensions retain their source/override. Frame contours and basket/cone envelopes are incomplete; test a mount coupon and actual driver before printing the full assembly.','Material strength, airtightness, heat, vibration, rigging, physical fit and acoustic performance require a prototype.','Support collars, plate thicknesses, removable lids and ducts displace rear air; the editor’s nominated rear volume is not automatically a verified final net cabinet volume.'];
  if(!o.includeRear)limits.push('Rear enclosures are excluded by choice. This package is the horn/front-chamber assembly; provide and seal the rear enclosure separately.');
  return {schema:SCHEMA,units:'mm',options:o,parts:results,seams,warnings:[...new Set(warnings)],mounts:mountManifest,diagnostics:{hornUncutVolumeMM3:hornUncutVolume,entryMaterialRemovedMM3:beforeCut-afterCut,joinedAssembly:initial,branches:diagnostics,engine:'Manifold 3.5.4 (Apache-2.0)',meshSimplificationToleranceMM:.005,profileSimplificationToleranceMM:.04,airPassagesChecked:true,centralHornProbeClearanceMM:.1,sourceBoltPassagesChecked:true,partInterferenceMaximumMM3:.1,driverSupport:'Removable rear plates with separate external M4 ear attachments; full-frame insertion clearance preserved.'},limitations:limits,scope:o.includeRear?'Joined front assembly with removable driver clamp plates, detachable rear enclosure modules or shared lid; segmented with alignment hardware.':'Joined front assembly with removable driver clamp plates; rear enclosures omitted.'};
 }finally{for(let i=allocated.length-1;i>=0;i--)try{allocated[i].delete();}catch(_){} }
}
function packageResult(a,design,result,deps={}){const F=deps.formats||root.MEHFileFormats||(typeof require==='function'?require('./formats.cjs'):null),files={},prefix='MEH-fabrication/';for(const p of result.parts){files[prefix+'parts/'+p.id+'.stl']=F.stl([p.localMesh]);files[prefix+'parts/'+p.id+'.step']=F.facetedStep([p.localMesh]);}files[prefix+'installed_assembly.obj']=F.obj(result.parts.map(p=>({...p.installedMesh,partId:p.id})));const manifest={...result,parts:result.parts.map(({localMesh,installedMesh,...p})=>({...p,stl:'parts/'+p.id+'.stl',step:'parts/'+p.id+'.step'})),designState:cp(a.p)};files[prefix+'fabrication.json']=JSON.stringify(manifest,null,2);files[prefix+'MEH_design_study.json']=JSON.stringify(design,null,2);files[prefix+'START_HERE.txt']=['MEH Studio browser-native fabrication package','','All STL and faceted STEP files use millimetres. Each local part is positioned at the print-bed origin. installed_assembly.obj preserves installed positions; fabrication.json maps each part to the assembly.','',result.scope,'','Assembly:','1. Print one removable driver support (all its sections) and one representative seam first; verify actual driver and dowel fit.','2. Print the parts in parts/. Choose orientations and supports in your printer’s normal workflow.','3. Dry-fit and align the numbered seam pairs in fabrication.json and installed_assembly.obj. Bond/seal all segmented seams; dowels only align.','4. Insert each driver through its full-frame collar opening. Install its separate rear support plate over the basket and attach the plate’s external ears with M4 through bolts/nuts. Source driver holes remain available. Then attach the removable rear enclosures or shared rear lid with gasket and M4 hardware. Choose bolt lengths for the actual stack.','5. Leak-test and measure the prototype before making an acoustic or load-bearing claim.','',...result.limitations.map(s=>'- '+s),'',...result.warnings.map(s=>'- '+s)].join('\n');return {files,manifest,result};}
async function kit(a,design,deps={}){return packageResult(a,design,await build(a,design,deps),deps);}
const api={SCHEMA,defaults,options,runtime,build,kit,packageResult,loft,meshOf,basicChecks};root.MEHFabrication=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
