/* Applied-design fabrication controls; geometry is generated on request, wholly offline. */
(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
function preview(canvas,result){let ctx;try{ctx=canvas.getContext('2d');}catch(_){return;}if(!ctx)return;const width=canvas.width=960,height=canvas.height=580,project=p=>[.82*p[0]-.57*p[1],.28*p[0]+.4*p[1]-.87*p[2],.5*p[0]+.72*p[1]+.5*p[2]],polygons=[],points=[];for(const part of result.parts){if(part.role==='alignment-pin')continue;const m=part.installedMesh,v=m.vertices.map(project);for(const point of v)points.push(point);for(const f of m.faces){const p=f.map(i=>v[i]),u=p[1].map((x,i)=>x-p[0][i]),q=p[2].map((x,i)=>x-p[0][i]),n=[u[1]*q[2]-u[2]*q[1],u[2]*q[0]-u[0]*q[2],u[0]*q[1]-u[1]*q[0]],length=Math.hypot(...n);if(n[2]<0)continue;polygons.push({p,z:p.reduce((s,p)=>s+p[2],0)/3,light:.4+.55*Math.abs((n[0]*.2-n[1]*.5+n[2]*.84)/(length||1)),role:part.role});}}
 if(!points.length)return;const min=[0,1].map(i=>points.reduce((s,p)=>Math.min(s,p[i]),Infinity)),max=[0,1].map(i=>points.reduce((s,p)=>Math.max(s,p[i]),-Infinity)),scale=Math.min((width-60)/(max[0]-min[0]),(height-60)/(max[1]-min[1]));ctx.fillStyle='#eef1f3';ctx.fillRect(0,0,width,height);polygons.sort((a,b)=>a.z-b.z);for(const q of polygons){ctx.beginPath();q.p.forEach((p,i)=>{const x=30+(p[0]-min[0])*scale,y=30+(p[1]-min[1])*scale;if(!i)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.closePath();const base=q.role==='rear-lid'?[101,139,167]:[162,147,191];ctx.fillStyle='rgb('+base.map(c=>Math.round(c*q.light)).join(',')+')';ctx.fill();}ctx.fillStyle='#24313d';ctx.font='16px system-ui';ctx.fillText('Generated material geometry · installed position · millimetres',20,height-15);}
function init(host,{getDesign,onChange,save}={}){if(!host||!getDesign)return null;const G=root.MEHFabrication;let settings=copy(G.defaults),result=null,currentKey=null,busy=false;host.innerHTML=`<summary>Printable assembly</summary><div style="padding:12px 2px"><p>Create joined horn walls, real entry cuts, driver support seats and removable rear lids. Download solid STL/STEP parts sized for your printer.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px"><label>Build width (mm)<input type="number" min="40" max="2000" data-fab="buildXMM"></label><label>Build depth (mm)<input type="number" min="40" max="2000" data-fab="buildYMM"></label><label>Build height (mm)<input type="number" min="40" max="2000" data-fab="buildZMM"></label><label>Bed margin (mm)<input type="number" min="0" max="100" data-fab="bedMarginMM"></label><label>Fit clearance, diametral (mm)<input type="number" min=".05" max="2" step=".05" data-fab="fitClearanceMM"></label><label>Minimum construction wall (mm)<input type="number" min="2" max="100" step=".5" data-fab="minimumWallMM"></label><label>Dowel diameter (mm)<input type="number" min="2" max="20" step=".5" data-fab="pinDiameterMM"></label><label>Dowel engagement per side (mm)<input type="number" min="3" max="100" step="1" data-fab="pinDepthMM"></label></div><p><label><input type="checkbox" data-fab="includeRear"> Include rear enclosures and removable lids</label> <label><input type="checkbox" data-fab="segment"> Split to build volume</label> <label><input type="checkbox" data-fab="alignmentPins"> Add alignment dowels at safe seam locations</label></p><p>Wall thickness follows the applied design. Driver seats use the source dimensions or confirmed measured overrides in Driver mounting. Shared rear enclosures must use a smooth shape. Segmented seams need bonding and sealing; dowels only align the parts.</p><button type="button" data-fab-generate>Generate assembly preview</button> <button type="button" data-fab-download disabled>Download fabrication ZIP</button><p data-fab-status role="status">Ready to generate from the applied design.</p><canvas data-fab-preview aria-label="Generated fabrication assembly" style="display:none;width:100%;max-height:360px;object-fit:contain;border-radius:10px"></canvas><p data-fab-summary></p><p>Prototype parts: verify driver fit, print tolerances, airtightness, material strength and acoustic performance before use. This export does not establish lifting or rigging safety.</p></div>`;
 const q=s=>host.querySelector(s),generate=q('[data-fab-generate]'),download=q('[data-fab-download]'),status=q('[data-fab-status]'),canvas=q('[data-fab-preview]'),summary=q('[data-fab-summary]');
 const key=d=>JSON.stringify({state:d.state,mounting:d.mountingParts,fabrication:settings});
 function fill(){host.querySelectorAll('[data-fab]').forEach(el=>{const v=settings[el.dataset.fab];if(el.type==='checkbox')el.checked=v===true;else el.value=v;});}
 function invalidate(){result=null;currentKey=null;download.disabled=true;canvas.style.display='none';summary.textContent='';status.textContent='Ready to generate from the applied design.';}
 function persist(){onChange?.(snapshot());}
 function snapshot(){return copy(settings);}
 function restore(value){settings={...copy(G.defaults),...(value&&typeof value==='object'?copy(value):{})};fill();invalidate();}
 function refresh(){if(busy)return;const d=getDesign();if(currentKey&&key(d)!==currentKey)invalidate();}
 async function run(asDownload=false){if(busy)return;busy=true;generate.disabled=true;download.disabled=true;try{const d={...getDesign(),fabrication:snapshot()},k=key(d);if(!result||k!==currentKey){status.textContent='Building material geometry…';await new Promise(r=>root.setTimeout(r,0));result=await G.build(root.MEH.analyze(d.state),d,{onProgress:message=>{status.textContent=message;}});if(key(getDesign())!==k){invalidate();status.textContent='Design changed during generation. Generate the current applied design again.';return null;}currentKey=k;preview(canvas,result);canvas.style.display='block';const main=result.parts.filter(p=>p.role!=='alignment-pin'),pins=result.parts.length-main.length;summary.textContent=`${main.length} solid print sections · ${pins} alignment dowels · ${result.seams.length} mating seams. ${result.warnings.join(' ')}`;status.textContent='Assembly generated. Every part is a closed material solid; driver and print fit still need a physical check.';}
 if(asDownload){status.textContent='Writing STL, STEP and assembly manifest…';await new Promise(r=>root.setTimeout(r,0));if(key(getDesign())!==k){invalidate();status.textContent='Design changed before export. Generate the current applied design again.';return null;}const kit=G.packageResult?G.packageResult(root.MEH.analyze(d.state),d,result):await G.kit(root.MEH.analyze(d.state),d);save?.('MEH_fabrication.zip',root.MEHDownloadZip.create(kit.files),'application/zip');status.textContent='Fabrication ZIP downloaded. Extract it and follow START_HERE.txt.';return kit;}return result;
 }catch(e){invalidate();status.textContent='Fabrication unavailable: '+e.message;}finally{busy=false;generate.disabled=false;download.disabled=!result;refresh();}}
 host.addEventListener('input',event=>{const el=event.target;if(!el.dataset.fab)return;settings[el.dataset.fab]=el.type==='checkbox'?el.checked:Number.isFinite(el.valueAsNumber)?el.valueAsNumber:null;invalidate();persist();});generate.addEventListener('click',()=>run(false));download.addEventListener('click',()=>run(true));fill();return {snapshot,restore,refresh,update:refresh,generate:()=>run(false),download:()=>run(true),get result(){return result;}};
}
const api={init,preview};root.MEHFabricationPanel=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
