/* Portable study exports. Coordinates are mm; CAD blanks deliberately have no entry cuts. */
(function(root){
'use strict';
const sub=(a,b)=>a.map((v,i)=>v-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],length=v=>Math.hypot(...v);
const num=v=>{if(!Number.isFinite(v))throw Error('Geometry contains a nonfinite coordinate.');return (Math.abs(v)<1e-12?0:v).toFixed(9);};
const safe=s=>String(s).replace(/[^a-zA-Z0-9_. -]/g,'_').replace(/[\r\n]/g,' ').slice(0,120);
function indexMesh(name,triangles){const vertices=[],faces=[],ids=new Map();for(const tri of triangles){if(tri.length!==3||tri.some(p=>p.length!==3||!p.every(Number.isFinite)))throw Error('Invalid triangle in '+name);if(length(cross(sub(tri[1],tri[0]),sub(tri[2],tri[0])))<1e-10)continue;faces.push(tri.map(p=>{const k=p.map(num).join(',');if(!ids.has(k)){ids.set(k,vertices.length);vertices.push(p);}return ids.get(k);}));}if(!faces.length)throw Error('No usable surfaces in '+name);return {name,vertices,faces};}
function displayMeshes(a,build){return build(a,false).filter(m=>m.data?.length&&m.kind!==4).map((m,index)=>{const tris=[];for(let i=0;i<m.data.length;i+=18)tris.push([0,6,12].map(j=>Array.from(m.data.slice(i+j,i+j+3))));return {...indexMesh(m.name,tris),partId:'part_'+String(index+1).padStart(3,'0'),provenance:{driverModelId:m.driverModelId||null,driverModelStatus:m.driverModelStatus||null,driverPartStatus:m.driverPartStatus||null,driverDatum:m.driverDatum||null,sourceIds:m.sourceIds||[]}};});}
function simplifyProfile(pro,tolerance=.05){if(tolerance<=0)return pro;const keep=new Set([0,pro.length-1]),point=p=>[p.r,p.z,p.outerR,p.outerZ],work=[[0,pro.length-1]];while(work.length){const [i,j]=work.pop(),a=point(pro[i]),b=point(pro[j]),v=sub(b,a),vv=v.reduce((s,x)=>s+x*x,0);let far=-1,dist=tolerance*tolerance;for(let k=i+1;k<j;k++){const p=point(pro[k]),t=Math.max(0,Math.min(1,sub(p,a).reduce((s,x,n)=>s+x*v[n],0)/(vv||1))),d=p.reduce((s,x,n)=>s+(x-a[n]-t*v[n])**2,0);if(d>dist){dist=d;far=k;}}if(far>=0){keep.add(far);work.push([i,far],[far,j]);}}return [...keep].sort((a,b)=>a-b).map(i=>pro[i]);}
function hornBlank(a,segments=96,{tolerance=.05}={}){const pro=simplifyProfile(a.pro,tolerance),vertices=[],faces=[],n=pro.length;if(!Number.isInteger(segments)||segments<8||segments>512)throw Error('Invalid angular sampling.');for(const outer of [false,true])for(const p of pro)for(let j=0;j<segments;j++){const angle=j*2*Math.PI/segments,r=outer?p.outerR:p.r;vertices.push([r*Math.cos(angle),r*Math.sin(angle),outer?p.outerZ:p.z]);}
const at=(o,i,j)=>o*n*segments+i*segments+(j%segments),quad=(a,b,c,d)=>faces.push([a,b,c],[a,c,d]);
for(let i=0;i<n-1;i++)for(let j=0;j<segments;j++){quad(at(0,i,j),at(0,i,j+1),at(0,i+1,j+1),at(0,i+1,j));quad(at(1,i,j),at(1,i+1,j),at(1,i+1,j+1),at(1,i,j+1));}
for(let j=0;j<segments;j++){quad(at(0,0,j),at(1,0,j),at(1,0,j+1),at(0,0,j+1));quad(at(0,n-1,j),at(0,n-1,j+1),at(1,n-1,j+1),at(1,n-1,j));}
let volume=faces.reduce((s,f)=>s+vertices[f[0]].reduce((v,x,i)=>v+x*cross(vertices[f[1]],vertices[f[2]])[i],0)/6,0);if(volume<0)for(const f of faces)[f[1],f[2]]=[f[2],f[1]];return {name:'Horn blank - no entry cuts',vertices,faces,closed:true};}
function obj(meshes){let offset=1,lines=['# MEH Studio - millimetres, +Z forward. Separate reference parts; no Boolean union.'];for(const m of meshes){lines.push('o '+safe((m.partId?m.partId+' ':'')+m.name).replace(/ /g,'_'));for(const p of m.vertices)lines.push('v '+p.map(num).join(' '));for(const f of m.faces)lines.push('f '+f.map(i=>i+offset).join(' '));offset+=m.vertices.length;}return lines.join('\n')+'\n';}
function stl(meshes){const count=meshes.reduce((n,m)=>n+m.faces.length,0),bytes=new Uint8Array(84+count*50),view=new DataView(bytes.buffer);const header='MEH Studio | mm | '+(meshes.length===1&&meshes[0].closed?'uncut horn blank':'assembly reference surfaces - not a fused solid');for(let i=0;i<Math.min(80,header.length);i++)bytes[i]=header.charCodeAt(i);view.setUint32(80,count,true);let p=84;for(const m of meshes)for(const f of m.faces){const points=f.map(i=>m.vertices[i]),normal=cross(sub(points[1],points[0]),sub(points[2],points[0])),l=length(normal);for(const x of [...normal.map(v=>v/l),...points.flat()]){if(!Number.isFinite(x))throw Error('Invalid STL coordinate.');view.setFloat32(p,x,true);p+=4;}p+=2;}return bytes;}
function cloud(meshes,quarter=false){const points=new Map();for(const m of meshes)for(const p of m.vertices)if(!quarter||p[0]>=-1e-8&&p[1]>=-1e-8){const q=p.map(v=>Math.abs(v)<1e-8?0:v),line=q.map(num).join(' ');points.set(line,true);}return [...points.keys()].join('\n')+'\n';}
function stepWriter(name,description){let id=0;const lines=[],E=s=>{lines.push('#'+(++id)+'='+s+';');return id;},ref=a=>a.map(i=>'#'+i).join(','),point=p=>E("CARTESIAN_POINT('',("+p.map(num).join(',')+"))");
function finish(items,type='SHAPE_REPRESENTATION'){
 const lu=E('(LENGTH_UNIT()NAMED_UNIT(*)SI_UNIT(.MILLI.,.METRE.))'),au=E('(NAMED_UNIT(*)PLANE_ANGLE_UNIT()SI_UNIT($,.RADIAN.))'),su=E('(NAMED_UNIT(*)SI_UNIT($,.STERADIAN.)SOLID_ANGLE_UNIT())'),unc=E("UNCERTAINTY_MEASURE_WITH_UNIT(LENGTH_MEASURE(0.000001),#"+lu+",'distance_accuracy_value','')"),ctx=E("(GEOMETRIC_REPRESENTATION_CONTEXT(3)GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT((#"+unc+"))GLOBAL_UNIT_ASSIGNED_CONTEXT(("+ref([lu,au,su])+"))REPRESENTATION_CONTEXT('','3D'))"),rep=E(type+"('"+safe(name)+"',("+ref(items)+"),#"+ctx+")"),app=E("APPLICATION_CONTEXT('core data for automotive mechanical design processes')");
 E("APPLICATION_PROTOCOL_DEFINITION('international standard','automotive_design',2000,#"+app+")");const pc=E("PRODUCT_CONTEXT('',#"+app+",'mechanical')"),prod=E("PRODUCT('"+safe(name)+"','"+safe(name)+"','',(#"+pc+"))"),form=E("PRODUCT_DEFINITION_FORMATION('1',$,#"+prod+")"),dc=E("PRODUCT_DEFINITION_CONTEXT('part definition',#"+app+",'design')"),pd=E("PRODUCT_DEFINITION('design',$,#"+form+",#"+dc+")"),shape=E("PRODUCT_DEFINITION_SHAPE('','',#"+pd+")");E('SHAPE_DEFINITION_REPRESENTATION(#'+shape+',#'+rep+')');
 return "ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('"+safe(description)+"'),'2;1');\nFILE_NAME('"+safe(name)+".step','2026-09-29T00:00:00',('MEH Studio'),(''),'MEH Studio','','');\nFILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\nENDSEC;\nDATA;\n"+lines.join('\n')+'\nENDSEC;\nEND-ISO-10303-21;\n';}
return {E,ref,point,finish};}
function facetedStep(meshes){const s=stepWriter('MEH geometry','mm - separate faceted reference surfaces or an uncut horn blank'),items=[];for(const m of meshes){const p=m.vertices.map(s.point),faces=[];for(const f of m.faces){const [a,b,c]=f.map(i=>m.vertices[i]),n=cross(sub(b,a),sub(c,a)),l=length(n),u=sub(b,a),ul=length(u);const dn=s.E("DIRECTION('',("+n.map(v=>num(v/l)).join(',')+"))"),dx=s.E("DIRECTION('',("+u.map(v=>num(v/ul)).join(',')+"))"),axis=s.E("AXIS2_PLACEMENT_3D('',#"+p[f[0]]+',#'+dn+',#'+dx+')'),plane=s.E("PLANE('',#"+axis+')'),loop=s.E("POLY_LOOP('',("+s.ref(f.map(i=>p[i]))+"))"),bound=s.E("FACE_OUTER_BOUND('',#"+loop+",.T.)");faces.push(s.E("FACE_SURFACE('',(#"+bound+"),#"+plane+",.T.)"));}
const shell=s.E((m.closed?'CLOSED_SHELL':'OPEN_SHELL')+"('"+safe(m.name)+"',("+s.ref(faces)+"))");items.push(s.E(m.closed?"FACETED_BREP('"+safe(m.name)+"',#"+shell+")":"SHELL_BASED_SURFACE_MODEL('"+safe(m.name)+"',(#"+shell+"))"));}return s.finish(items);}
function nurbsStep(a){const s=stepWriter('MEH uncut horn surfaces','NURBS horn blank - inner and outer surfaces - no entry cuts or enclosure'),surfaces=[];
// Exact rational circles; linear meridian segments reproduce the sampled profile without spline overshoot.
const circle=[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1],[1,0]],weights=[1,Math.SQRT1_2,1,Math.SQRT1_2,1,Math.SQRT1_2,1,Math.SQRT1_2,1],n=a.pro.length;
for(const outer of [false,true]){const poles=a.pro.map(p=>circle.map(([x,y])=>s.point([x*(outer?p.outerR:p.r),y*(outer?p.outerR:p.r),outer?p.outerZ:p.z]))),uMult=Array.from({length:n},(_,i)=>i===0||i===n-1?2:1),uKnots=Array.from({length:n},(_,i)=>num(i/(n-1)));surfaces.push(s.E("(BOUNDED_SURFACE()B_SPLINE_SURFACE(1,2,("+poles.map(row=>'('+s.ref(row)+')').join(',')+"),.UNSPECIFIED.,.F.,.T.,.F.)B_SPLINE_SURFACE_WITH_KNOTS(("+uMult.join(',')+"),(3,2,2,2,3),("+uKnots.join(',')+"),(0.,0.25,0.5,0.75,1.),.UNSPECIFIED.)GEOMETRIC_REPRESENTATION_ITEM()RATIONAL_B_SPLINE_SURFACE(("+poles.map(()=> '('+weights.map(num).join(',')+')').join(',')+"))REPRESENTATION_ITEM('"+(outer?'Outer':'Inner')+" uncut horn')SURFACE())"));}
const set=s.E("GEOMETRIC_SET('Uncut horn surfaces',("+s.ref(surfaces)+"))");return s.finish([set],'GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION');}
function profileCSV(a,comma=false){const sep=comma?';':',',f=v=>comma?num(v).replace('.',','):num(v);return 't'+sep+'z_mm'+sep+'radius_mm'+sep+'outer_z_mm'+sep+'outer_radius_mm\n'+a.pro.map(p=>[p.t,p.z,p.r,p.outerZ,p.outerR].map(f).join(sep)).join('\n')+'\n';}
function aks(a,A,M){if(a.p.frontFiller!=='none')throw Error('The 1D AKABAK script supports open collectors only; use the mesh package for inserts.');if(a.p.rearConcept==='reflex')throw Error('The 1D AKABAK script currently supports sealed rear chambers; use the mesh package for vent geometry.');const availability=A.availability(a);if(!availability.available)throw Error(availability.reason);const d=A.catalog[a.p.midDriver];if(!d)throw Error('Complete motor data are required for the 1D script.');if(M.mechanicalFitReasons(a).length)throw Error('Resolve geometry fit before exporting an acoustic script.');if(Math.abs(d.sd-a.p.sd)>1e-6)throw Error('The edited piston area differs from the selected motor data.');
const pro=M.frontBranch(a.pro),tap=a.p.tap,z0=pro[0].z,z1=pro.at(-1).z;if(!(tap>z0&&tap<z1))throw Error('Entry station must lie inside the axial horn.');const zs=[...new Set([...Array.from({length:49},(_,i)=>z0+(z1-z0)*i/48),tap])].sort((x,y)=>x-y),area=z=>{let i=1;while(i<pro.length-1&&pro[i].z<z)i++;const p=pro[i-1],q=pro[i],t=(z-p.z)/(q.z-p.z);return Math.PI*(p.r+t*(q.r-p.r))**2;},entry=100+zs.indexOf(tap),mms=d.mmsG*.001,w=2*Math.PI*d.fs,cms=1/(w*w*mms),rms=w*mms/d.qms;
const lines=['| MEH Studio - preliminary 1D multi-entry network, sealed mids only.','| Import/solve in AKABAK has NOT been verified. Inspect all nodes and units.','| Area-law horn; no transverse modes, HF driver, crossover or directivity.','| Equal-phase mids share one axial station. Throat is rigidly closed.','| Set sound speed '+num(a.p.soundSpeed)+' m/s and density 1.204 kg/m3 manually.','| Set electrical source drive to the saved per-mid RMS voltage in the design JSON.','| Catalog Mms is retained; added front/rear air-mass conventions need review.','| Front chamber is lumped. Constant-area entry includes physical neck+3mm and 1.4-radius allowance.','| This is not a proven numerical match to the editor or a voltage-calibrated BEM result.','| AKABAK 3: Lumped Element > General > Script. No placeholder compression driver.','',"Def_Driver 'Mid'",'Sd='+num(d.sd)+'cm2','Bl='+num(d.bl)+'Tm','Cms='+num(cms)+'m/N','Rms='+num(rms)+'Ns/m','fs='+num(d.fs)+'Hz','Le='+num(d.leMH)+'mH','Re='+num(d.re)+'ohm','ExpoLe=1','',"System 'MEH sealed mids'",''];
const shared=a.p.rearLayout==='shared';if(shared)lines.push("Enclosure 'Shared sealed rear'",'Node=10','Vb='+num(a.p.sharedBack)+'L','');
for(let i=0;i<a.p.count;i++){const rear=shared?10:20+i,front=40+i;lines.push("Driver Def='Mid' 'Mid "+(i+1)+"'",'Node=1=0='+rear+'='+front,'');if(!shared)lines.push("Enclosure 'Rear "+(i+1)+"'",'Node='+rear,'Vb='+num(a.p.back)+'L','');lines.push("Enclosure 'Front "+(i+1)+"'",'Node='+front,'Vb='+num(a.frontCavityV/1000)+'L','',"Waveguide 'Entry "+(i+1)+"'",'Node='+front+'='+entry,'STh='+num(a.collectorSmallArea/100)+'cm2','SMo='+num(a.collectorSmallArea/100)+'cm2','Len='+num((a.p.neck+3+1.4*Math.sqrt(a.collectorSmallArea/Math.PI))/10)+'cm','Conical','');}
for(let i=0;i<zs.length-1;i++)lines.push("Waveguide 'Horn "+(i+1)+"'",'Node='+(100+i)+'='+(101+i),'STh='+num(area(zs[i])/100)+'cm2','SMo='+num(area(zs[i+1])/100)+'cm2','Len='+num((zs[i+1]-zs[i])/10)+'cm','Conical','');lines.push("Radiator 'Horn mouth'",'Node='+(99+zs.length),'SD='+num(area(z1)/100)+'cm2','Label=1','');return lines.join('\n');}
const api={simplifyProfile,indexMesh,displayMeshes,hornBlank,obj,stl,cloud,facetedStep,nurbsStep,profileCSV,aks};root.MEHFileFormats=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
