/* CAD handoff: reference assembly plus explicitly selected, separate mounting solids. */
(function(root){'use strict';
const add=(a,b)=>a.map((v,i)=>v+b[i]),mul=(a,k)=>a.map(v=>v*k),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
const copy=v=>JSON.parse(JSON.stringify(v));
const limitations=[
 'Reference assembly surfaces are separate, may overlap, and are not a fused printable or ready-to-build model.',
 'The horn blank has wall thickness and the roll but no entry cuts. Viewer-only horn cuts are not baked into the CAD reference assembly.',
 'Entry outlines are sampled positions on the inner horn wall, not cutter solids, hole depths or fabrication tolerances.',
 'Manufacturer dimensions retain their source and status. Undimensioned frame contours, baskets, cones, hardware, gaskets and clearance envelopes can be approximate.',
 'Selected mounting plates include real cutouts and bolt holes. Finish entry cuts, structural connections, fastener engagement, seals and print segmentation in CAD; verify material thickness, moving clearances, tolerances and interference with actual parts.',
 'Cone inserts use an editable diaphragm surrogate. Real cone, dust cap, surround and excursion clearances require measurement.',
 'The CAD assets are not acoustic domains. Use the separate ABEC / AKABAK or Boundary Lab local solver kit for checked acoustic boundary meshes.'
];
function sourceRecord(record){if(!record)return null;return {id:record.id,name:record.name,variant:record.variant,model_status:record.modelStatus,datum:record.geometry?.datum||null,dimensions:copy(record.dimensions),mounting_patterns:copy((record.geometry?.parts||[]).filter(p=>p.type==='bolt-pattern')),unresolved:copy(record.unresolved||[]),sources:(record.sources||[]).map(s=>Object.fromEntries(['id','url','kind','sha256','inspection','accessDate','inspectionDate','redistribution'].filter(k=>s[k]!==undefined).map(k=>[k,s[k]])))};}
function mountingKit(a,design,{formats=root.MEHFileFormats,model=root.MEH,land=root.MEHMounting,mounting=root.MEHMountParts}={}){
 if(!mounting&&typeof require==='function')mounting=require('./mounting.cjs');
 if(!formats||!model||!mounting)throw Error('Mounting components are unavailable.');
 if(a.errors.length)throw Error('Resolve geometry errors before exporting mounts: '+a.errors.join(' '));
 const result=mounting.build(a,design.mountingParts||{},{model,land});
 if(result.errors.length)throw Error(result.errors.join(' '));
 if(!result.parts.length)throw Error('Select at least one driver mounting part.');
 const prefix='MEH-mounting/',files={},types=new Map();
 for(const part of result.parts){
  if(types.has(part.kind))continue;
  const stem=part.kind+'_mount';types.set(part.kind,stem);
  files[prefix+stem+'.stl']=formats.stl([part.localMesh]);
  files[prefix+stem+'.step']=formats.facetedStep([part.localMesh]);
 }
 const limits=[
  'Separate mounting parts with actual central openings and bolt through-holes; not a joined horn or cabinet assembly.',
  'STL and STEP parts use local millimetre coordinates, one reusable part per driver kind. Quantities and installed transforms are in this manifest; installed_mounts.obj shows all placements.',
  'Mid support plates seat at the recorded rear underside of the flange and extend toward the magnet. The compression flange sits on the horn side of the editor mounting face, 12 mm behind the throat; this adapter distance is an existing design assumption.',
  'Plate thickness, bolt clearance, edge margin and gasket land are design choices. Thread engagement, bolt length, gasket compression, hardware/tool access, strength and print material are not validated.',
  'The plate cutout and bolt holes are checked against each other and the plate boundary. Complete driver, horn, chamber and fastener interference, attachment and sealing still require CAD and physical-fit checks.',
  'These parts do not change the acoustic model or certify a printable assembled loudspeaker. Selected counterbores are cut into the local +Z face: rear side for mids and horn side for the compression flange. Threaded inserts are not generated.'
 ];
 const manifest={schema:'MEH-mounting-kit-v1',units:'mm',settings:copy(result.settings),design_state:copy(a.p),warnings:copy(result.warnings),parts:result.parts.map(p=>({id:p.id,kind:p.kind,driver_id:p.driverId,local_stl:types.get(p.kind)+'.stl',local_step:types.get(p.kind)+'.step',spec:copy(p.spec),transform:copy(p.transform),checks:copy(p.checks)})),quantities:Object.fromEntries([...types.keys()].map(k=>[k,result.parts.filter(p=>p.kind===k).length])),drivers:{mid:sourceRecord(a.midDriver?.record||model.drivers.mid[a.p.midDriver]?.record),compression:sourceRecord(a.compressionDriver?.record)},limitations:limits};
 files[prefix+'installed_mounts.obj']=formats.obj(result.parts.map(p=>({...p.worldMesh,partId:p.id})));
 files[prefix+'mounting_parts.json']=JSON.stringify(manifest,null,2);
 files[prefix+'MEH_design_study.json']=JSON.stringify(design,null,2);
 files[prefix+'START_HERE.txt']=['MEH Studio driver mounting parts','','Import STL or faceted STEP as millimetres. Each local part rests at z=0 and extends to its selected thickness. Print/machine the quantity in mounting_parts.json; the installed OBJ is a positioning reference, not a print layout.','',...limits.map(x=>'- '+x),'','Source and chosen dimensions, measured overrides and the exact saved study accompany the parts.','',...result.warnings].join('\n');
 return {files,manifest,result};
}
function build(a,design,{formats=root.MEHFileFormats,buildMeshes=root.MEHMeshes,model=root.MEH,land=root.MEHMounting,mounting=root.MEHMountParts}={}){
 if(!formats||!model||typeof buildMeshes!=='function')throw Error('CAD handoff components are unavailable.');
 if(a.errors.length)throw Error('Resolve geometry errors before exporting CAD: '+a.errors.join(' '));
 const meshes=formats.displayMeshes(a,buildMeshes),blank=formats.hornBlank(a),mid=model.driverModel(a.p,'mid'),compression=model.driverModel(a.p,'compression');
 const midRecord=sourceRecord(a.midDriver?.record||model.drivers.mid[a.p.midDriver]?.record),compressionRecord=sourceRecord(a.compressionDriver?.record);
 const mounts=a.poses.map((pose,index)=>{const n=pose.driverN||pose.n,offset=mid?.mountOffsetMM??null;return {id:'mid_'+(index+1),driver_id:a.p.midDriver,editor_front_rim_origin_mm:copy(pose.F),catalogue_datum_origin_mm:offset===null?null:add(pose.F,mul(n,offset)),catalogue_datum_offset_from_front_rim_mm:offset,catalogue_datum_offset_status:mid?(mid.record.dimensions.mountingFaceOffset?.status||mid.record.dimensions.flangeThickness?.status||'assumed-zero-offset'):null,basis_x:copy(pose.t),basis_y:copy(pose.v),basis_z_toward_magnet:copy(n),basis_determinant:dot(cross(pose.t,pose.v),n),transform:'world = catalogue_datum_origin_mm + local_x*basis_x + local_y*basis_y + local_z*basis_z_toward_magnet',catalogue_model_placed:!!mid,datum_note:mid?'Reproduces the displayed catalogue model placement, not a verified fabrication datum. Consult the dimension status and unresolved source notes; a default or assumed offset is not a measured mounting face.':'Edited/custom geometry has no matching catalogue model placement. Front-rim pose remains a design reference; do not apply catalogue mounting dimensions as a fabrication template.'};});
 const manifest={schema:'MEH-CAD-handoff-v1',units:{length:'mm',angle:'degrees unless explicitly marked radians'},axes:{origin:'Horn throat center',forward:'+Z',handedness:'right'},scope:'CAD and printing preparation; no fabricated assembly supplied',normalized_design_state:copy(a.p),validation:{errors:copy(a.errors),warnings:copy(a.warnings),mechanical_fit_reasons:copy(model.mechanicalFitReasons(a)),scope:'Editor geometry screening only; no production or physical validation'},files:{'horn_blank_uncut.stl':'Closed uncut horn blank; STL has no formal unit metadata: import as millimetres.','assembly_reference.obj':'Named separate reference parts in world coordinates; import as millimetres.','entry_outlines_mm.csv':'Closed sampled inner-wall entry outlines; first point repeated at the end.','horn_profile_mm.csv':'Sampled inner and outer horn profile.','MEH_design_study.json':'Original reloadable applied design.'},parts:meshes.map(m=>({id:m.partId,name:m.name,obj_object:(m.partId+' '+m.name).replace(/[^a-zA-Z0-9_. -]/g,'_').replace(/[\r\n]/g,' ').slice(0,120).replace(/ /g,'_'),vertex_count:m.vertices.length,triangle_count:m.faces.length,role:'reference surface; solid/manifold status not asserted',provenance:m.provenance})),drivers:{mid:midRecord,compression:compressionRecord},mid_mounts:mounts,compression_mount:compression?{driver_id:a.p.compressionDriver,catalogue_datum_origin_mm:[0,0,-12],basis_x:[1,0,0],basis_y:[0,1,0],basis_z_toward_magnet:[0,0,-1],basis_determinant:-1,datum_note:'Displayed adapter assumption: compression-driver mounting face 12 mm behind throat. Check phase-plug projection, gasket and bolt engagement in CAD.'}:null,limitations};
 const lines=['entry_id,point_index,x_mm,y_mm,z_mm'];for(const [i,pose]of a.poses.entries()){const points=[...pose.edge,pose.edge[0]];points.forEach((p,j)=>lines.push(['mid_'+(i+1),j,...p.map(v=>v.toFixed(9))].join(',')));}
 const guide=['# MEH Studio CAD / 3D-printing handoff','','Open CAD_handoff.json alongside your CAD application. All geometry is in millimetres, origin at the horn throat center, +Z toward the mouth. STL and OBJ may be imported without units by your application: select mm and verify the saved mouth diameter.','','1. Import horn_blank_uncut.stl as a starting blank, or use the individual NURBS STEP download in MEH Studio for editable uncut horn surfaces. The blank is closed; it has no entry holes.','2. Import assembly_reference.obj with object/group separation enabled. Part IDs and original display names are indexed in CAD_handoff.json. The reference-only original-profile overlay is excluded. Do not Boolean-union all parts: drivers, gaskets and hardware are placement references.','3. Use entry_outlines_mm.csv and horn_profile_mm.csv to reconstruct the actual entry cuts and desired CAD surfaces. The CSV entry loops are on the inner wall; they do not define through-wall cutters.','4. For driver mounts, use the exact variant, source URLs, dimension status and local datum in CAD_handoff.json. mid_mounts supplies the editor front-rim pose and the catalogue model transform when it matches. The local basis may have determinant -1; preserve that handedness when transforming coordinates. No drilling template is supplied for these reference driver surfaces; generated mounting plates, when selected, are supplied separately.','5. Use selected mounting parts or add the required mounts, then finish joins and print segmentation; check against the manufacturer drawing and actual driver. Verify seals, fastener access and engagement, material thickness, moving clearances, tolerances and interference before fabrication.','','## Scope and outstanding work','',...limitations.map(x=>'- '+x),'','## Driver source notes','',...[['Mid',midRecord],['Compression',compressionRecord]].flatMap(([label,r])=>r?[label+': '+r.name+' / '+r.variant+' / '+r.model_status,...r.unresolved.map(note=>'- '+note),'See CAD_handoff.json for dimension-by-dimension status and source URLs.','']:[label+': no matching catalogue record; mounting geometry must be established independently.','']),'## Reproduce this handoff','','Reload MEH_design_study.json in MEH Studio and export the CAD handoff again. The JSON manifest preserves the normalized dimensions used for this export. Reference links are supplied without bundling manufacturer CAD or drawings. No internet connection is needed to inspect this package.','','## Geometry checks','','Editor warnings: '+(a.warnings.join(' ')||'None.'),'Mechanical fit advisories: '+(manifest.validation.mechanical_fit_reasons.join(' ')||'None.'),'These checks do not establish production readiness or acoustic performance.',''].join('\n');
 const files={'MEH-CAD-handoff/START_HERE.md':guide,'MEH-CAD-handoff/MEH_design_study.json':JSON.stringify(design,null,2),'MEH-CAD-handoff/horn_blank_uncut.stl':formats.stl([blank]),'MEH-CAD-handoff/assembly_reference.obj':formats.obj(meshes),'MEH-CAD-handoff/entry_outlines_mm.csv':lines.join('\n')+'\n','MEH-CAD-handoff/horn_profile_mm.csv':formats.profileCSV(a)};
 if(['mid','compression'].some(kind=>design.mountingParts?.[kind]?.enabled===true)){
  const kit=mountingKit(a,design,{formats,model,land,mounting});
  for(const [name,data]of Object.entries(kit.files))files['MEH-CAD-handoff/mounting/'+name.slice('MEH-mounting/'.length)]=data;
  manifest.mounting_parts={manifest:'mounting/mounting_parts.json',quantities:kit.manifest.quantities,scope:'Separate solid parts with real cutouts and through-holes; not fused to the reference assembly.'};
  files['MEH-CAD-handoff/START_HERE.md']+='\n\n## Selected mounting parts\n\nThe mounting folder contains separate solid STL and faceted STEP plates with actual holes. Read mounting/START_HERE.txt and mounting/mounting_parts.json for quantities, source dimensions, design choices and installed positions. Reference driver surfaces above remain references; selected plates are separate parts.\n';
 }
 files['MEH-CAD-handoff/CAD_handoff.json']=JSON.stringify(manifest,null,2);
 return {manifest,files};
}
const api={build,mountingKit,sourceRecord,limitations};root.MEHCADHandoff=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
