/* Separate driver mounting parts. Source geometry and editable construction allowances stay distinct. */
(function(root){
'use strict';
const TAU=2*Math.PI,EPS=1e-7,KINDS=['mid','compression'];
const copy=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
const finite=x=>typeof x==='number'&&Number.isFinite(x);
const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const area=p=>p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-a[1]*b[0];},0)/2;
const circle=(r,n=128,c=[0,0])=>Array.from({length:n},(_,i)=>[c[0]+r*Math.cos(TAU*i/n),c[1]+r*Math.sin(TAU*i/n)]);
function segmentDistance(p,a,b){const v=sub(b,a),d=dot(v,v),t=d?Math.max(0,Math.min(1,dot(sub(p,a),v)/d)):0;return Math.hypot(p[0]-a[0]-v[0]*t,p[1]-a[1]-v[1]*t);}
function inside(p,outline){let hit=false;for(let i=0,j=outline.length-1;i<outline.length;j=i++){const a=outline[i],b=outline[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;}
function clearance(p,outline){const d=Math.min(...outline.map((a,i)=>segmentDistance(p,a,outline[(i+1)%outline.length])));return inside(p,outline)?d:-d;}
function hull(points){const p=points.map(q=>q.slice()).sort((a,b)=>a[0]-b[0]||a[1]-b[1]).filter((a,i,all)=>!i||Math.hypot(...sub(a,all[i-1]))>1e-9),turn=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),lo=[],hi=[];for(const q of p){while(lo.length>1&&turn(lo.at(-2),lo.at(-1),q)<=1e-10)lo.pop();lo.push(q);}for(const q of p.slice().reverse()){while(hi.length>1&&turn(hi.at(-2),hi.at(-1),q)<=1e-10)hi.pop();hi.push(q);}return lo.slice(0,-1).concat(hi.slice(0,-1));}
function sourceRecord(r){return r?{id:r.id,name:r.name,variant:r.variant,datum:r.geometry?.datum,dimensions:copy(r.dimensions),mountingPatterns:copy((r.geometry?.parts||[]).filter(p=>p.type==='bolt-pattern')),sources:(r.sources||[]).map(s=>Object.fromEntries(['id','url','sha256','kind','inspection','inspectionDate'].filter(k=>s[k]!==undefined).map(k=>[k,s[k]]))),unresolved:copy(r.unresolved||[])}:null;}
function sourceDimension(r,key,{zero=false}={}){const d=r?.dimensions?.[key],s=r?.sources?.find(s=>s.id===d?.sourceId);return !!(d&&finite(d.value)&&(zero?d.value>=0:d.value>0)&&['drawing-verified','cad-inspected','published','derived'].includes(d.status)&&s);}
function sourcePattern(r){const part=r?.geometry?.parts?.find(p=>p.type==='bolt-pattern'&&p.status==='dimensioned'&&(p.sourceIds||[]).some(id=>r.sources?.some(s=>s.id===id&&['drawing-reviewed','cad-inspected'].includes(s.inspection))));if(!part)return null;const d=r.dimensions,p=part.params;const start=sourceDimension(r,'boltStartAngle',{zero:true})?d.boltStartAngle.value:p.startAngleDeg;if(!finite(start)||!finite(p.count)||!finite(p.circleDiameter))return null;if(p.count!==d.boltCount?.value||Math.abs(p.circleDiameter-d.boltCircleDiameter?.value)>EPS)return null;return {part,start};}
function baseDefaults(kind,r){const hole=r?.dimensions?.boltHoleDiameter?.value,thread=r?.dimensions?.boltThread?.value;return {enabled:false,thicknessMM:6,boltHoleDiameterMM:finite(hole)&&hole>0?hole:(/^M6(?:$|[- ])/.test(thread||'')?6.5:null),edgeMarginMM:3,gasketLandMM:2,counterboreDiameterMM:0,counterboreDepthMM:0,override:null};}
function inspectOne(a,kind,deps){const model=deps.model||root.MEH,land=deps.land||root.MEHMounting,driverId=a.p[kind==='mid'?'midDriver':'compressionDriver'],selected=model?.driverModel?.(a.p,kind),entry=model?.drivers?.[kind==='mid'?'mid':'compression']?.[driverId],r=selected?.record||entry?.record||null,reasons=[],warnings=[],defaults={...baseDefaults(kind,r),driverId};let spec=null;
 if(!selected)reasons.push('The current dimensions do not match an inspected driver model.');
 if(r&&selected&&selected.id!==driverId)reasons.push('The selected model identity does not match the active driver.');
 if(!r||!r.variant)reasons.push('An exact driver variant and source record are required.');
 if(r&&entry?.sourceRecordId&&entry.sourceRecordId!==r.id)reasons.push('The catalogue source record does not match the selected driver.');
 if(kind==='compression'&&entry?.available===false)reasons.push(entry.unavailableReason||'This driver needs a dedicated throat interface that is not implemented.');
 const cutoutKey=kind==='mid'?'cutoutDiameter':'exitDiameter',pattern=sourcePattern(r);
 if(kind==='mid'&&typeof land?.create!=='function')reasons.push('The mounting-outline module is unavailable.');
 for(const key of [cutoutKey,'boltCircleDiameter','boltCount'])if(!sourceDimension(r,key))reasons.push('A resolved, sourced '+key+' is required.');
 if(r&&!Number.isInteger(r.dimensions?.boltCount?.value))reasons.push('Bolt count must be an integer.');
 if(kind==='mid'&&!sourceDimension(r,'mountingFaceOffset',{zero:true}))reasons.push('The mounting-seat offset from the front rim is unresolved.');
 if(kind==='mid'&&!sourceDimension(r,'boltHoleDiameter'))reasons.push('The driver bolt-hole diameter is unresolved or conflicting.');
 if(kind==='compression'&&!/mounting.*(?:face|flange).*z\s*=\s*0|mounting\s+flange\s+face\s+z\s*=\s*0/i.test(r?.geometry?.datum||''))reasons.push('A mounting-face datum at z=0 is required.');
 if(!pattern)reasons.push('The bolt pattern and its angular registration need an inspected drawing.');
 if(!reasons.length){const d=r.dimensions,outline=kind==='mid'?land.create(a.p,r,{gasketLandMM:0,boltEdgeLandMM:0})?.outline:null;if(kind==='mid'&&(!outline||outline.length<3))reasons.push('A usable mounting outline is unavailable.');spec={cutoutDiameterMM:d[cutoutKey].value,outerDiameterMM:kind==='mid'?Math.max(0,...(outline||[]).map(p=>Math.hypot(...p)))*2:d.boltCircleDiameter.value+20,boltCircleDiameterMM:d.boltCircleDiameter.value,boltCount:d.boltCount.value,startAngleDeg:pattern.start,mountOffsetMM:kind==='mid'?d.mountingFaceOffset.value:0,outline:kind==='mid'?copy(outline):null,outlineStatus:kind==='mid'?'source-derived-outline':'designed-circular-flange',driverBoltHoleDiameterMM:sourceDimension(r,'boltHoleDiameter')?d.boltHoleDiameter.value:null,driverBoltThread:d.boltThread?.value||null,origin:'catalogue'};
  if(kind==='mid'&&(!outline||outline.length<3)){reasons.push('A usable mounting outline is unavailable.');spec=null;}
  if(kind==='mid')warnings.push('The plate follows the catalogue frame outline; undimensioned contours remain approximate.');
  else warnings.push('Flange outer diameter is a design allowance. The catalogue mounting-face outline and bolt engagement are not fully defined.');
 }
 const catalogueReasons=reasons.slice(),override=deps.settings?.[kind]?.override;
 if(override){const bad=[];if(override.confirmed!==true)bad.push('Confirm that override dimensions were checked against the physical driver or a measured drawing.');if(override.driverId!==driverId)bad.push('Measured overrides belong to another driver; re-enter them for the current selection.');if(typeof override.note!=='string'||!override.note.trim())bad.push('A source or measurement note is required for overrides.');for(const key of ['cutoutDiameterMM','outerDiameterMM','boltCircleDiameterMM','boltCount'])if(!finite(override[key])||override[key]<=0)bad.push('Override '+key+' must be a positive number.');if(!Number.isInteger(override.boltCount)||override.boltCount>64)bad.push('Override boltCount must be an integer from 1 to 64.');if(!finite(override.startAngleDeg))bad.push('Override startAngleDeg must be a finite number.');if(!finite(override.mountOffsetMM)||override.mountOffsetMM<0)bad.push('Override mountOffsetMM must be a nonnegative number.');
  if(kind==='compression'&&(entry?.phaseProjectionMM>0||entry?.available===false))bad.push('A measured bolt pattern cannot resolve the unsupported forward phase plug or throat coupling.');
  if(kind==='compression'&&finite(override.mountOffsetMM)&&override.mountOffsetMM!==0)bad.push('Compression overrides must use their mounting face as local z=0.');
  if(!bad.length){spec={...Object.fromEntries(['cutoutDiameterMM','outerDiameterMM','boltCircleDiameterMM','boltCount','startAngleDeg','mountOffsetMM'].map(k=>[k,override[k]])),outline:null,outlineStatus:'measured-circular-envelope',driverBoltHoleDiameterMM:null,driverBoltThread:null,origin:'measured-override',measurementNote:override.note.trim()};reasons.length=0;warnings.push('Geometry uses explicit measured overrides; the original catalogue limitations remain in the manifest.');}
  else reasons.push(...bad);
 }
 if(spec){spec.boltCenters=Array.from({length:spec.boltCount},(_,i)=>{const t=spec.startAngleDeg*Math.PI/180+TAU*i/spec.boltCount;return [spec.boltCircleDiameterMM/2*Math.cos(t),spec.boltCircleDiameterMM/2*Math.sin(t)];});if(!spec.outline)spec.outline=circle(spec.outerDiameterMM/2);}
 warnings.push('Plate thickness, hole clearance, gasket land and edge margin are editable construction assumptions. Verify fastener access, engagement, material strength, seals and assembly interference.');
 return {available:reasons.length===0,reasons,warnings,driverId,name:r?.name||entry?.name||driverId,variant:r?.variant||null,source:sourceRecord(r),spec,defaults,catalogueReasons};
}
function inspect(a,deps={}){if(!a?.p)throw Error('An analyzed design is required.');return Object.fromEntries(KINDS.map(kind=>[kind,inspectOne(a,kind,deps)]));}
function settingsFor(input,inspection){return Object.fromEntries(KINDS.map(kind=>[kind,{...inspection[kind].defaults,...copy(input?.[kind]||{}),enabled:input?.[kind]?.enabled===true}]));}
function resolveSpec(info,settings){const errors=[],spec={...copy(info.spec),thicknessMM:settings.thicknessMM,boltHoleDiameterMM:settings.boltHoleDiameterMM,edgeMarginMM:settings.edgeMarginMM,gasketLandMM:settings.gasketLandMM,counterboreDiameterMM:settings.counterboreDiameterMM,counterboreDepthMM:settings.counterboreDepthMM};
 for(const key of ['thicknessMM','boltHoleDiameterMM'])if(!finite(spec[key])||spec[key]<=0)errors.push(key+' must be a positive number.');
 for(const key of ['edgeMarginMM','gasketLandMM'])if(!finite(spec[key])||spec[key]<0)errors.push(key+' must be a nonnegative number.');
 for(const key of ['counterboreDiameterMM','counterboreDepthMM'])if(!finite(spec[key])||spec[key]<0)errors.push(key+' must be a nonnegative number.');
 spec.hasCounterbores=spec.counterboreDiameterMM>0||spec.counterboreDepthMM>0;
 if(spec.hasCounterbores&&(!(spec.counterboreDepthMM>0)||!(spec.counterboreDepthMM<spec.thicknessMM)))errors.push('Counterbore depth must be greater than zero and less than plate thickness.');
 if(spec.hasCounterbores&&!(spec.counterboreDiameterMM>spec.boltHoleDiameterMM))errors.push('Counterbore diameter must exceed the through-hole diameter.');
 if(spec.thicknessMM>1000||spec.boltHoleDiameterMM>1000||spec.edgeMarginMM>1000||spec.gasketLandMM>1000)errors.push('Plate dimensions exceed the supported 1000 mm construction range.');
 if(!spec.outline?.length)return {spec,errors:[...errors,'No mounting outline is available.']};
 if(errors.length)return {spec,errors};
 // Circumscribed hole polygons retain at least the requested aperture across flats.
 const cut=spec.cutoutDiameterMM/2/Math.cos(Math.PI/128),through=spec.boltHoleDiameterMM/2/Math.cos(Math.PI/48),recess=spec.hasCounterbores?spec.counterboreDiameterMM/2/Math.cos(Math.PI/48):through,bolt=Math.max(through,recess),centers=spec.boltCenters,outer=spec.outline,supports=[];
 spec.holeApproximation={method:'circumscribed polygons; requested diameter is minimum across flats',centralSegments:128,boltSegments:48,centralMaximumRadialAllowanceMM:cut-spec.cutoutDiameterMM/2,boltMaximumRadialAllowanceMM:through-spec.boltHoleDiameterMM/2,counterboreMaximumRadialAllowanceMM:spec.hasCounterbores?recess-spec.counterboreDiameterMM/2:0};
 if(clearance([0,0],outer)<cut+spec.gasketLandMM-EPS)supports.push(...circle((cut+spec.gasketLandMM)/Math.cos(Math.PI/128)));
 for(const q of centers){if(Math.hypot(...q)-bolt-cut<spec.gasketLandMM-EPS)errors.push('A bolt hole or counterbore intersects the central opening or leaves less than the requested gasket land.');if(clearance(q,outer)<bolt+spec.edgeMarginMM-EPS)supports.push(...circle((bolt+spec.edgeMarginMM)/Math.cos(Math.PI/32),32,q));}
 for(let i=0;i<centers.length;i++)for(let j=i+1;j<centers.length;j++)if(Math.hypot(...sub(centers[i],centers[j]))-2*bolt<spec.edgeMarginMM-EPS)errors.push('Adjacent bolt holes or counterbores intersect or leave less than the requested edge margin.');
 if(supports.length)spec.outline=hull([...outer,...supports]);
 spec.expandedForAllowances=supports.length>0;spec.outerDiameterMM=2*Math.max(...spec.outline.map(p=>Math.hypot(...p)));spec.holes=[circle(cut),...centers.map(q=>circle(through,48,q))];spec.topHoles=[circle(cut),...centers.map(q=>circle(recess,48,q))];spec.counterboreFace='local +Z; mid rear fastener side or compression horn-facing side';
 spec.clearances={outerGasketLandMM:clearance([0,0],spec.outline)-cut,boltToOpeningMM:Math.min(...centers.map(q=>Math.hypot(...q)-bolt-cut)),boltToOuterEdgeMM:Math.min(...centers.map(q=>clearance(q,spec.outline)-bolt)),boltToBoltMM:centers.length>1?Math.min(...centers.flatMap((q,i)=>centers.slice(i+1).map(v=>Math.hypot(...sub(q,v))-2*bolt))):null};
 return {spec,errors:[...new Set(errors)]};
}
function checkMesh(mesh){let volume=0;const edges=new Map();for(const f of mesh.faces){if(f.length!==3||new Set(f).size!==3)throw Error('A mounting triangle has invalid indices.');const [a,b,c]=f.map(i=>mesh.vertices[i]);if(![a,b,c].every(p=>p?.length===3&&p.every(finite)))throw Error('A mounting vertex is invalid.');if(Math.hypot(...cross(sub(b,a),sub(c,a)))<1e-10)throw Error('A mounting triangle is degenerate.');volume+=dot(a,cross(b,c))/6;for(let i=0;i<3;i++){const x=f[i],y=f[(i+1)%3],k=x<y?x+':'+y:y+':'+x;if(!edges.has(k))edges.set(k,[]);edges.get(k).push(x<y?1:-1);}}
 for(const signs of edges.values())if(signs.length!==2||signs[0]+signs[1]!==0)throw Error('Mounting mesh is not a closed consistently oriented surface.');if(!(volume>0))throw Error('Mounting mesh has nonpositive volume.');return {closed:true,oriented:true,positiveVolume:true,signedVolumeMM3:volume,vertexCount:mesh.vertices.length,triangleCount:mesh.faces.length};}
function extrude(spec,triangulate){
 const oriented=(loop,outer)=>{const p=loop.map(q=>q.slice());if((area(p)>0)!==outer)p.reverse();return p;},bottomLoops=[spec.outline,...spec.holes].map((p,i)=>oriented(p,i===0)),topLoops=[spec.outline,...spec.topHoles].map((p,i)=>oriented(p,i===0)),bottom=bottomLoops.flat(),top=topLoops.flat(),starts=[];let n=0;for(const loop of bottomLoops){starts.push(n);n+=loop.length;}
 const vertices=[...bottom.map(p=>[...p,0]),...top.map(p=>[...p,spec.thicknessMM])],faces=[];
 function cap(points,offset,up){const indices=triangulate(points.flat(),starts.slice(1),2);if(!Array.isArray(indices)||!indices.length||indices.length%3)throw Error('Triangulation failed.');for(let i=0;i<indices.length;i+=3){let f=indices.slice(i,i+3),a=points[f[0]],b=points[f[1]],c=points[f[2]];if((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])<0)f=[f[0],f[2],f[1]];if(!up)f=[f[0],f[2],f[1]];faces.push(f.map(j=>j+offset));}}
 cap(bottom,0,false);cap(top,n,true);
 function wall(lower,upper,count){for(let i=0;i<count;i++){const j=(i+1)%count,a=lower+i,b=lower+j,c=upper+j,d=upper+i;faces.push([a,b,c],[a,c,d]);}}
 for(let k=0;k<bottomLoops.length;k++){
  const count=bottomLoops[k].length,start=starts[k];
  if(k<2||!spec.hasCounterbores){wall(start,n+start,count);continue;}
  const shoulderZ=spec.thicknessMM-spec.counterboreDepthMM,smallStart=vertices.length;for(const p of bottomLoops[k])vertices.push([...p,shoulderZ]);const largeStart=vertices.length;for(const p of topLoops[k])vertices.push([...p,shoulderZ]);wall(start,smallStart,count);wall(largeStart,n+start,count);
  // Upward-facing annular shoulder shares vertices with both cylindrical walls.
  for(let i=0;i<count;i++){const j=(i+1)%count,a=smallStart+i,b=smallStart+j,c=largeStart+j,d=largeStart+i;faces.push([a,b,c],[a,c,d]);}
 }
 const mesh={vertices,faces,closed:true},checks=checkMesh(mesh),throughArea=spec.holes.reduce((s,p)=>s+Math.abs(area(p)),0),topArea=spec.topHoles.reduce((s,p)=>s+Math.abs(area(p)),0),expected=(Math.abs(area(spec.outline))-throughArea)*spec.thicknessMM-(topArea-throughArea)*spec.counterboreDepthMM;
 if(!(expected>0)||Math.abs(checks.signedVolumeMM3-expected)>Math.max(1e-5,expected*1e-8))throw Error('Triangulated volume differs from the plate area; holes may be invalid.');checks.polygonalVolumeMM3=expected;checks.volumeErrorMM3=checks.signedVolumeMM3-expected;return {mesh,checks};
}
function transformMesh(mesh,transform){const {origin,basisX:x,basisY:y,basisZ:z}=transform;if(![origin,x,y,z].every(p=>Array.isArray(p)&&p.length===3&&p.every(finite)))throw Error('Invalid mounting placement.');const determinant=dot(cross(x,y),z);if(Math.abs(Math.abs(determinant)-1)>1e-6||[x,y,z].some(v=>Math.abs(dot(v,v)-1)>1e-6)||Math.abs(dot(x,y))+Math.abs(dot(x,z))+Math.abs(dot(y,z))>1e-6)throw Error('Mounting placement requires an orthonormal basis.');transform.determinant=determinant;return {...mesh,vertices:mesh.vertices.map(p=>origin.map((v,i)=>v+p[0]*x[i]+p[1]*y[i]+p[2]*z[i])),faces:mesh.faces.map(f=>determinant<0?[f[0],f[2],f[1]]:f.slice())};}
function build(a,input={},deps={}){const inspection=inspect(a,{...deps,settings:input}),settings=settingsFor(input,inspection),parts=[],errors=[],warnings=[],triangulate=deps.triangulate||root.MEHEarcut||(typeof require==='function'?require('./vendor/earcut.cjs'):null);
 for(const kind of KINDS){const info=inspection[kind],opt=settings[kind];if(!opt.enabled)continue;if(opt.driverId!==info.driverId){errors.push(info.name+': Mounting settings belong to another driver; review them for the current selection.');continue;}if(!info.available){errors.push(...info.reasons.map(s=>info.name+': '+s));continue;}const result=resolveSpec(info,opt);if(result.errors.length){errors.push(...result.errors.map(s=>info.name+': '+s));continue;}const spec=result.spec;
  try{if(typeof triangulate!=='function')throw Error('The polygon triangulator is unavailable.');if(kind==='mid'&&(!Array.isArray(a.poses)||!a.poses.length))throw Error('No mid-driver placement is available.');const {mesh,checks}=extrude(spec,triangulate),poses=kind==='mid'?a.poses:[null],kindParts=[];for(let i=0;i<poses.length;i++){const pose=poses[i],id=kind==='mid'?'mid_mount_'+(i+1):'compression_mount',name=kind==='mid'?'Mid '+(i+1)+' mounting plate':'Compression-driver mounting flange',axis=pose&&(pose.driverN||pose.n),transform=kind==='mid'?{origin:pose.F.map((v,j)=>v+axis[j]*spec.mountOffsetMM),basisX:copy(pose.t),basisY:copy(pose.v),basisZ:copy(axis),note:'Plate starts at the underside driver flange and extends toward the magnet.'}:{origin:[0,0,-12],basisX:[1,0,0],basisY:[0,1,0],basisZ:[0,0,1],note:'Plate extends toward the horn from the displayed mounting face 12 mm behind the throat; the adapter placement is a design assumption.'};const localMesh={...mesh,name,partId:id,role:'separate-mounting-part',units:'mm'},worldMesh=transformMesh(localMesh,transform),worldChecks=checkMesh(worldMesh);kindParts.push({id,kind,driverId:info.driverId,name,variant:info.variant,spec:copy(spec),source:info.source,transform,localMesh,worldMesh,checks:{...checks,worldSignedVolumeMM3:worldChecks.signedVolumeMM3},warnings:info.warnings.slice()});}parts.push(...kindParts);warnings.push(...info.warnings);
  }catch(error){errors.push(info.name+': '+error.message);}
 }
 return {schema:'MEH-mounting-parts-v1',units:'mm',settings,inspection,parts,errors:[...new Set(errors)],warnings:[...new Set(warnings)],scope:'Separate mounting solids with through holes and optional top-face counterbores; no assembly union, structural rating, fastener engagement or completed horn entry cuts.'};
}
const api={inspect,build,checkMesh};root.MEHMountParts=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
