(function(root){'use strict';
function init(host,{getDesign,save}={}){if(!host)return;const F=root.MEHFileFormats,M=root.MEH;
host.innerHTML=`<h3>CAD &amp; 3D</h3><div class="export-row"><label>Geometry<select data-ex-scope><option value="blank">Horn blank · no entry cuts</option><option value="assembly">Assembly · reference surfaces</option></select></label><label>File type<select data-ex-format><option value="stl">STL (.stl)</option><option value="obj">OBJ (.obj)</option><option value="step">STEP · faceted (.step)</option><option value="nurbs">STEP · NURBS horn surfaces (.step)</option><option value="xyz">Point cloud (.xyz)</option><option value="quarter">Quarter horn cloud (.xyz)</option></select></label></div><p class="note" data-ex-scope-note>The horn blank includes wall thickness and the roll, without entry holes. Finish openings and mounting in CAD.</p><button type="button" data-ex-download>Download STL (.stl)</button><p class="note" data-ex-status role="status" aria-live="polite"></p>`;
const q=s=>host.querySelector(s),format=q('[data-ex-format]'),scope=q('[data-ex-scope]'),button=q('[data-ex-download]'),status=q('[data-ex-status]');let busy=false;
function sync(){const special=['nurbs','quarter'].includes(format.value);if(special)scope.value='blank';scope.disabled=special;button.textContent='Download '+({stl:'STL (.stl)',obj:'OBJ (.obj)',step:'faceted STEP (.step)',nurbs:'NURBS STEP (.step)',xyz:'point cloud (.xyz)',quarter:'quarter horn cloud (.xyz)'}[format.value]);q('[data-ex-scope-note]').textContent=format.value==='nurbs'?'Inner and outer NURBS horn surfaces, including the roll. Uncut surfaces only; add entries and closures in CAD.':format.value==='quarter'?'Uncut horn only, X ≥ 0 and Y ≥ 0, in mm. This point cloud has no solver boundaries or driver sources.':scope.value==='assembly'?'Separate assembly surfaces, including driver envelopes. Horn entry cuts shown in the viewer are not baked into these reference surfaces; finish cuts and joins in CAD.':'The horn blank includes wall thickness and the roll, without entry holes. Finish openings and mounting in CAD.';status.textContent='';}
async function run(){if(busy)return;busy=true;button.disabled=true;const kind=format.value,target=scope.value;status.textContent='Preparing download…';await new Promise(r=>root.setTimeout(r,0));try{const design=getDesign(),a=M.analyze(design.state);if(a.errors.length)throw Error('Resolve geometry errors before exporting CAD: '+a.errors.join(' '));let data,type='text/plain',ext=kind,name='MEH_'+(target==='assembly'?'assembly_reference':'horn_blank');if(kind==='nurbs'){data=F.nurbsStep(a);ext='step';name='MEH_horn_uncut_NURBS_surfaces';}else{const meshes=target==='assembly'?F.displayMeshes(a,root.MEHMeshes):[F.hornBlank(a)];if(kind==='stl'){data=F.stl(meshes);type='model/stl';}else if(kind==='obj')data=F.obj(meshes);else if(kind==='step')data=F.facetedStep(meshes);else{data=F.cloud(meshes,kind==='quarter');ext='xyz';if(kind==='quarter')name+='_'+kind;}}save(name+'.'+ext,data,type);status.textContent='Downloaded '+name+'.'+ext+' · millimetres.';}catch(e){status.textContent='Export unavailable: '+e.message;}finally{busy=false;button.disabled=false;}}
format.addEventListener('change',sync);scope.addEventListener('change',sync);button.addEventListener('click',run);sync();return {run,sync};}
root.MEHFileExportPanel={init};if(typeof module!=='undefined'&&module.exports)module.exports={init};
})(typeof globalThis!=='undefined'?globalThis:this);
