/* ZIP32 writer and append-only packager: preserves the embedded runner's compressed entries. */
(function(root){'use strict';
const bytes=v=>typeof v==='string'?new TextEncoder().encode(v):v instanceof Uint8Array?v:new Uint8Array(v);
function crc32(data){let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function join(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length;}return out;}
function append(base,files){base=base?bytes(base):new Uint8Array();let oldCount=0,offset=0,oldLocal=base,oldDirectory=new Uint8Array();if(base.length){const v=new DataView(base.buffer,base.byteOffset,base.byteLength),e=base.length-22;if(e<0||v.getUint32(e,true)!==0x06054b50||v.getUint16(e+20,true)!==0)throw Error('Unsupported runner ZIP structure.');oldCount=v.getUint16(e+10,true);offset=v.getUint32(e+16,true);const size=v.getUint32(e+12,true);if(offset+size!==e)throw Error('Invalid runner ZIP directory.');oldLocal=base.slice(0,offset);oldDirectory=base.slice(offset,e);}
const local=[oldLocal],directory=[oldDirectory],entries=Object.entries(files);for(const [name,input]of entries){if(name.startsWith('/')||name.split('/').includes('..'))throw Error('Unsafe ZIP filename.');const filename=bytes(name),data=bytes(input),crc=crc32(data),h=new Uint8Array(30),v=new DataView(h.buffer),c=new Uint8Array(46),w=new DataView(c.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,filename.length,true);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(14,33,true);w.setUint32(16,crc,true);w.setUint32(20,data.length,true);w.setUint32(24,data.length,true);w.setUint16(28,filename.length,true);w.setUint32(42,offset,true);local.push(h,filename,data);directory.push(c,filename);offset+=h.length+filename.length+data.length;}
const d=join(directory),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,oldCount+entries.length,true);v.setUint16(10,oldCount+entries.length,true);v.setUint32(12,d.length,true);v.setUint32(16,offset,true);return join([...local,d,end]);}
const api={append,create:files=>append(null,files),crc32};root.MEHDownloadZip=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
